### PR TITLE
Fix compiling on Mac

### PR DESCRIPTION
**Pull request by mkuron**
What works now:
- CMake without CUDA
- Autotools without CUDA -- though this requires `make install` due to wrong library install names
- Autotools with CUDA -- again, `make install` is needed

What doesn't work:
- CMake with CUDA (see below)

What is untested:
- building with mpifake

------

~~CUDA on Mac currently requires explicitly setting the host compiler (via `cmake .. -DCUDA_HOST_COMPILER=$(which clang)`). This appears to be a bug in either the nvcc compiler wrapper or the host compiler.~~

Even then, there appears to be a cyclic dependency between libEspresso and libEspressoCuda:

```
[  5%] Linking CXX shared library libEspressoCuda.dylib
Undefined symbols for architecture x86_64:
  "cuda_mpi_send_forces(float*, float*, CUDA_fluid_composition*)", referenced from:
      copy_forces_from_GPU() in EspressoCuda_generated_cuda_common_cuda.cu.o
  "cuda_mpi_get_particles(CUDA_particle_data*)", referenced from:
      copy_part_data_to_gpu() in EspressoCuda_generated_cuda_common_cuda.cu.o
  "copy_CUDA_energy_to_energy(CUDA_energy)", referenced from:
      copy_energy_from_GPU() in EspressoCuda_generated_cuda_common_cuda.cu.o
  "cuda_bcast_global_part_params()", referenced from:
      p3m_gpu_init(int, int*, double, double*) in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "errexit()", referenced from:
      _cuda_safe_mem(cudaError, char const*, unsigned int) in EspressoCuda_generated_cuda_common_cuda.cu.o
      _cuda_check_errors(dim3 const&, dim3 const&, char const*, char const*, unsigned int) in EspressoCuda_generated_cuda_common_cuda.cu.o
      gpu_change_number_of_part_to_comm() in EspressoCuda_generated_cuda_common_cuda.cu.o
      gpu_init_particle_comm() in EspressoCuda_generated_cuda_common_cuda.cu.o
      copy_forces_from_GPU() in EspressoCuda_generated_cuda_common_cuda.cu.o
  "EspressoSystemInterface::m_instance", referenced from:
      p3m_gpu_init(int, int*, double, double*) in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "EspressoSystemInterface::const_iterator<Vector<3, double> >::operator=(SystemInterface::const_iterator<Vector<3, double> > const&)", referenced from:
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "EspressoSystemInterface::const_iterator<Vector<3, double> >::operator++()", referenced from:
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "EspressoSystemInterface::const_iterator<double>::operator=(SystemInterface::const_iterator<double> const&)", referenced from:
      vtable for EspressoSystemInterface::const_iterator<double> in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "EspressoSystemInterface::const_iterator<double>::operator++()", referenced from:
      vtable for EspressoSystemInterface::const_iterator<double> in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "EspressoSystemInterface::const_iterator<Vector<3, double> >::operator*() const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "EspressoSystemInterface::const_iterator<Vector<3, double> >::operator==(SystemInterface::const_iterator<Vector<3, double> > const&) const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "EspressoSystemInterface::const_iterator<Vector<3, double> >::operator!=(SystemInterface::const_iterator<Vector<3, double> > const&) const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "EspressoSystemInterface::const_iterator<double>::operator*() const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<double> in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "EspressoSystemInterface::const_iterator<double>::operator==(SystemInterface::const_iterator<double> const&) const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<double> in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "EspressoSystemInterface::const_iterator<double>::operator!=(SystemInterface::const_iterator<double> const&) const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<double> in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "vtable for EspressoSystemInterface", referenced from:
      p3m_gpu_init(int, int*, double, double*) in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "_coulomb", referenced from:
      p3m_gpu_add_farfield_force() in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "_idum", referenced from:
      gpu_change_number_of_part_to_comm() in EspressoCuda_generated_cuda_common_cuda.cu.o
  "_iv", referenced from:
      gpu_change_number_of_part_to_comm() in EspressoCuda_generated_cuda_common_cuda.cu.o
  "_iy", referenced from:
      gpu_change_number_of_part_to_comm() in EspressoCuda_generated_cuda_common_cuda.cu.o
  "_n_part", referenced from:
      gpu_change_number_of_part_to_comm() in EspressoCuda_generated_cuda_common_cuda.cu.o
      assign_forces(CUDA_particle_data const*, P3MGpuData, float*, float) in EspressoCuda_generated_p3m_gpu_cuda.cu.o
  "_this_node", referenced from:
      _cuda_check_errors(dim3 const&, dim3 const&, char const*, char const*, unsigned int) in EspressoCuda_generated_cuda_common_cuda.cu.o
      gpu_change_number_of_part_to_comm() in EspressoCuda_generated_cuda_common_cuda.cu.o
      gpu_init_particle_comm() in EspressoCuda_generated_cuda_common_cuda.cu.o
      copy_part_data_to_gpu() in EspressoCuda_generated_cuda_common_cuda.cu.o
      copy_forces_from_GPU() in EspressoCuda_generated_cuda_common_cuda.cu.o
      cuda_get_device_props(int, EspressoGpuDevice&) in EspressoCuda_generated_cuda_init_cuda.cu.o
      p3m_gpu_init(int, int*, double, double*) in EspressoCuda_generated_p3m_gpu_cuda.cu.o
      ...
```

### CODE REVIEW

**Comment by mkuron** [comment]
I fixed the missing system includes issue. Now the only thing remaining for @fweik to do is to fix libEspressoCuda's dependency on symbols from libEspresso.

**Comment by fweik** [comment]
Adding -undefined dynamic_lookup to the linker options should solve the problems with the symbols. But this means actually missing symbols are not detected until runtime, so this seems also not to be the perfect solution.

**Comment by mkuron** [comment]
I thought about doing something along those lines. However, why does that problem not even come up on Linux? After all, the dependency situation is the same there.

**Comment by fweik** [comment]
Apparently this is the default behavior on Linux.

**Comment by mkuron** [comment]
Looks like the default behavior of the linker on Mac OS X is equivalent to linking with `--no-undefined` on Linux. So we should just add that linker flag on Mac OS X to get identical behavior everywhere. I'll do that tomorrow.

**Comment by mkuron** [comment]
Ok, that resolves this issue, but the missing symbols for EspressoSystemInterface::const_iterator remain.
```
$ make
[  6%] Built target EspressoCuda
[ 46%] Built target EspressoCore
[ 47%] Built target Vector_test
[ 47%] Linking CXX executable Espresso
Undefined symbols for architecture x86_64:
  "EspressoSystemInterface::const_iterator<Vector<3, double> >::operator=(SystemInterface::const_iterator<Vector<3, double> > const&)", referenced from:
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in Ewaldgpu_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in HarmonicOrientationWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in HarmonicWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in Mmm1dgpu_tcl.cpp.o
  "EspressoSystemInterface::const_iterator<Vector<3, double> >::operator++()", referenced from:
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in Ewaldgpu_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in HarmonicOrientationWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in HarmonicWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in Mmm1dgpu_tcl.cpp.o
  "EspressoSystemInterface::const_iterator<double>::operator=(SystemInterface::const_iterator<double> const&)", referenced from:
      vtable for EspressoSystemInterface::const_iterator<double> in Ewaldgpu_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in HarmonicOrientationWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in HarmonicWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in Mmm1dgpu_tcl.cpp.o
  "EspressoSystemInterface::const_iterator<double>::operator++()", referenced from:
      vtable for EspressoSystemInterface::const_iterator<double> in Ewaldgpu_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in HarmonicOrientationWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in HarmonicWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in Mmm1dgpu_tcl.cpp.o
  "EspressoSystemInterface::const_iterator<Vector<3, double> >::operator*() const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in Ewaldgpu_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in HarmonicOrientationWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in HarmonicWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in Mmm1dgpu_tcl.cpp.o
  "EspressoSystemInterface::const_iterator<Vector<3, double> >::operator==(SystemInterface::const_iterator<Vector<3, double> > const&) const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in Ewaldgpu_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in HarmonicOrientationWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in HarmonicWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in Mmm1dgpu_tcl.cpp.o
  "EspressoSystemInterface::const_iterator<Vector<3, double> >::operator!=(SystemInterface::const_iterator<Vector<3, double> > const&) const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in Ewaldgpu_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in HarmonicOrientationWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in HarmonicWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<Vector<3, double> > in Mmm1dgpu_tcl.cpp.o
  "EspressoSystemInterface::const_iterator<double>::operator*() const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<double> in Ewaldgpu_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in HarmonicOrientationWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in HarmonicWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in Mmm1dgpu_tcl.cpp.o
  "EspressoSystemInterface::const_iterator<double>::operator==(SystemInterface::const_iterator<double> const&) const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<double> in Ewaldgpu_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in HarmonicOrientationWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in HarmonicWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in Mmm1dgpu_tcl.cpp.o
  "EspressoSystemInterface::const_iterator<double>::operator!=(SystemInterface::const_iterator<double> const&) const", referenced from:
      vtable for EspressoSystemInterface::const_iterator<double> in Ewaldgpu_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in HarmonicOrientationWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in HarmonicWell_tcl.cpp.o
      vtable for EspressoSystemInterface::const_iterator<double> in Mmm1dgpu_tcl.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/tcl/Espresso] Error 1
make[1]: *** [src/tcl/CMakeFiles/Espresso.dir/all] Error 2
make: *** [all] Error 2
```
Oddly enough, I can see that these symbols are there:
```
$ nm src/core/libEspressoCore.dylib | c++filt | grep 'EspressoSystemInterface::const_iterator'
000000000002d3f0 unsigned short EspressoSystemInterface::const_iterator<Vector<3, double> >::operator=(SystemInterface::const_iterator<Vector<3, double> > const&)
000000000002d450 unsigned short EspressoSystemInterface::const_iterator<Vector<3, double> >::operator++()
000000000002d470 unsigned short EspressoSystemInterface::const_iterator<double>::operator=(SystemInterface::const_iterator<double> const&)
000000000002d4d0 unsigned short EspressoSystemInterface::const_iterator<double>::operator++()
000000000002dc70 unsigned short EspressoSystemInterface::const_iterator<int>::operator=(SystemInterface::const_iterator<int> const&)
000000000002dcd0 unsigned short EspressoSystemInterface::const_iterator<int>::operator++()
000000000002d3c0 unsigned short EspressoSystemInterface::const_iterator<Vector<3, double> >::operator*() const
000000000002d410 unsigned short EspressoSystemInterface::const_iterator<Vector<3, double> >::operator==(SystemInterface::const_iterator<Vector<3, double> > const&) const
000000000002d430 unsigned short EspressoSystemInterface::const_iterator<Vector<3, double> >::operator!=(SystemInterface::const_iterator<Vector<3, double> > const&) const
000000000002d460 unsigned short EspressoSystemInterface::const_iterator<double>::operator*() const
000000000002d490 unsigned short EspressoSystemInterface::const_iterator<double>::operator==(SystemInterface::const_iterator<double> const&) const
000000000002d4b0 unsigned short EspressoSystemInterface::const_iterator<double>::operator!=(SystemInterface::const_iterator<double> const&) const
000000000002dc60 unsigned short EspressoSystemInterface::const_iterator<int>::operator*() const
000000000002dc90 unsigned short EspressoSystemInterface::const_iterator<int>::operator==(SystemInterface::const_iterator<int> const&) const
000000000002dcb0 unsigned short EspressoSystemInterface::const_iterator<int>::operator!=(SystemInterface::const_iterator<int> const&) const
000000000011d650 D typeinfo for EspressoSystemInterface::const_iterator<Vector<3, double> >
000000000011d670 D typeinfo for EspressoSystemInterface::const_iterator<double>
000000000011d9c0 D typeinfo for EspressoSystemInterface::const_iterator<int>
00000000000fca50 S typeinfo name for EspressoSystemInterface::const_iterator<Vector<3, double> >
00000000000fca90 S typeinfo name for EspressoSystemInterface::const_iterator<double>
00000000000fcde0 S typeinfo name for EspressoSystemInterface::const_iterator<int>
000000000011d8f0 D vtable for EspressoSystemInterface::const_iterator<Vector<3, double> >
000000000011d928 D vtable for EspressoSystemInterface::const_iterator<double>
000000000011d978 D vtable for EspressoSystemInterface::const_iterator<int>
```

**Comment by mkuron** [comment]
Looks like these symbols are automatically marked as hidden:
```
$ nm -m ./src/core/CMakeFiles/EspressoCore.dir/EspressoSystemInterface.cpp.o | c++filt 
[...] 
00000000000006a0 (__TEXT,__textcoal_nt) weak external automatically hidden EspressoSystemInterface::const_iterator<Vector<3, double> >::operator*() const
[...]
```
Is there any GCC-specificy symbol visibility behavior we're relying on here? There's a LLVM bug report marked as _won't fix_ that looks like it's exactly this issue: https://llvm.org/bugs/show_bug.cgi?id=8205

**Comment by mkuron** [comment]
I've moved the `const_iterator` to the header file for now. That obviously fixes the problem.
The pull request is ready for merging now.

**Pull request merged**
