### PR TITLE
fixed that build failed if h5md is not present

### PR DESCRIPTION
**Pull request by dschwoerer**
If h5md is not present and configure is run with:
./configure  --with-h5md=no
The build failed as the header file was still tried to be included.

### CODE REVIEW

**Comment by dschwoerer** [comment]
The fix for issue #337 allows a sd_radius of -1
Other negative values are not allowed, in order to avoid to accidentally set a negative timestep.

**Comment by dschwoerer** [comment]
I didn't change anything in the lb part, therefore i think it should be save to merge anyway.

**Comment by fweik** [comment]
Have you tried --without-h5md ?

**Comment by dschwoerer** [comment]
I tried 
./configure  --with-h5md=no
Without that, configure failed.
With that, configure succeeded, but the build failed, as the #include h5md.h was outside the #ifdef, and therefore the compiler looked for it, irrespective of the configuration.

**Pull request merged**
