### PR TITLE
utils: get_linear_index + cleanup

### PR DESCRIPTION
**Pull request by fweik**

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
its unfortunate that the unravel index uses a different convention, couldn't we merge your logic into the unravel/ravel index functions without a lot of effort?

**Comment by fweik** [comment]
Since this is performance relevant in some places I'd keep the version with static dimension (=3). Also from a quick inspection I'd say that one is row-major and one is column-major, because why not?

**Comment by KaiSzuttor** [comment]
yes it's fine to have both versions, but maybe we want to have names that imply that the functions do the same (besides column/row -majorness)

**Comment by fweik** [comment]
The proper way I think (since `ravel_index` already takes a range) would be to keep one name and specialize it for `Vector`. Also neither the name nor documentation of the functions says what they actually do. Also `ravel_index` and `unravel_index` seem not to be common names for this, I'm aware of the numpy function, but otherwise these names apparently are not use much.

**Comment by fweik** [comment]
@KaiSzuttor so?

**Comment by KaiSzuttor** [comment]
I agree, maybe we can add a static switch for the row/column-major logic?

**Comment by fweik** [comment]
@KaiSzuttor I agree that this should be refactored, but this PR still is an improvement, so we should merge it.

**Review by KaiSzuttor — APPROVED** [review]

**Pull request merged**
