### PR TITLE
Skip long-running (timeout-prone) tests on exotic archs

### PR DESCRIPTION
**Pull request by RudolfWeeber**

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
How can I manually trigger the exotic arch tests for this?

**Comment by mkuron** [comment]
This is a terrible solution. The tests should be fixed, not skipped.

**Comment by KaiSzuttor** [comment]
it's an intermediate solution

**Review by KaiSzuttor — APPROVED** [review]

**Comment by RudolfWeeber** [comment]
While I understand the discomfort, as long as no PR with a better solution is provided,
this PR aims to resolve an untenable situation keeping most of the tests on uncommen architectures.
Except for coulomb_tuning, all tests exlucded here run in less than 10 seconds on my desktop. P3m_Tuning takes 21 seconds.
So the tests are not inherently over the top in terms of computational effort.

I'll gladly withdraw this PR, if there is an alternative one solving the frequent false-positives.

**Pull request merged**
