### PR TITLE
testsuite: Corrected proc limit for coulomb_mixed_periodicity

### LINKED ISSUE #2061: Test `#67: coulomb_mixed_periodicity` fails when run in parallel (X>3 cores)
Test `#67: coulomb_mixed_periodicity` fails on with:
```
.ERROR: number of cells 3 is smaller than minimum 4 (interaction range too large or min_num_cells too large)
ERROR: number of cells 3 is smaller than minimum 4 (interaction range too large or min_num_cells too large)
ERROR: number of cells 3 is smaller than minimum 4 (interaction range too large or min_num_cells too large)
ERROR: number of cells 3 is smaller than minimum 4 (interaction range too large or min_num_cells too large)
E
======================================================================
ERROR: test_zz_p3mElc (__main__.CoulombMixedPeriodicity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pathtoespresso/build/testsuite/coulomb_mixed_periodicity.py", line 118, in test_zz_p3mElc
    self.S.actors.add(p3m)
  File "espressomd/actors.pyx", line 186, in espressomd.actors.Actors.add (/pathtoespresso/build/src/python/espressomd/actors.cpp:5237)
  File "espressomd/actors.pyx", line 49, in espressomd.actors.Actor._activate (/pathtoespresso/build/src/python/espressomd/actors.cpp:2009)
  File "espressomd/electrostatics.pyx", line 347, in espressomd.electrostatics.P3M._activate_method (/pathtoespresso/build/src/python/espressomd/electrostatics.cpp:5138)
  File "espressomd/electrostatics.pyx", line 338, in espressomd.electrostatics.P3M._tune (/pathtoespresso/build/src/python/espressomd/electrostatics.cpp:4910)
  File "espressomd/electrostatics.pxd", line 134, in espressomd.electrostatics.python_p3m_adaptive_tune (/pathtoespresso/build/src/python/espressomd/electrostatics.cpp:11013)
  File "espressomd/utils.pyx", line 268, in espressomd.utils.handle_errors (/pathtoespresso/build/src/python/espressomd/utils.cpp:7111)
Exception: Error in p3m_adaptive_tune
```
when run on more than three cores (checked up to 7 cores).

### PR DESCRIPTION
**Pull request by fweik**
Fixes #2061.

Description of changes:
 - 

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Review by KaiSzuttor — APPROVED** [review]
Metaquestion, what is the criterion for MAX_NUM_PROC in general?

**Comment by RudolfWeeber** [comment]
I got this issue with 4 procs, which should work.

**Comment by fweik** [comment]
Hm, I don't know, I'll look at the test.

**Comment by fweik** [comment]
@RudolfWeeber why do you assume that 4 should work?

**Comment by RudolfWeeber** [comment]
> @RudolfWeeber why do you assume that 4 should work?
It worked for me once the node_grid issues were sorted out. See #2061 and #1211.

**Review by pkreissl — APPROVED** [review]

**Pull request closed without merging**
