### PR TITLE
System, Integrator, Thermostat

### PR DESCRIPTION
**Pull request by tobiasrau**
Adresses #741, #742 and #739

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
Thx. I'll have a look.

**Comment by RudolfWeeber** [comment]
In general, it looks good.
Please address the following issues, though:
* When building with the maxset myconfig, not all py tests pass
* In cellsystem.pyx, please remove the setter for node_grid, as this is not user-settable
* I had the notion that diffrent integrators woudl go into different classes,
  but I'm also with the way it's done here, as it also unifies the interface
* The tutorials scripts and tex files need to be adapted

**Comment by RudolfWeeber** [comment]
* There still is a prob with the cellsystem test case
* (fragments of) the tutorial scripts are also in the .tex-files and also need to be changed

**Comment by RudolfWeeber** [comment]
Looks good. I think, it can be merged.

**Comment by fweik** [comment]
Handled elsewhere

**Pull request closed without merging**
