### PR TITLE
Store non-bonded interaction parameters only once per pair

### PR DESCRIPTION
**Pull request by fweik**
Description of changes:
 - Index function for upper triangular matrices
 - Store non-bonded interaction parameters only once per pair

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
could you please adapt ```realloc_ia_params```

**Comment by fweik** [comment]
Obviously `max_seen_particle_type` is not the largest seen particle type...

**Review by KaiSzuttor — APPROVED** [review]
it's definitely an improvement

**Pull request merged**
