### PR TITLE
units: added header file for usage of boost units.

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Review by hmenke — COMMENTED** [review]
What does this do?  It doesn't seem to be used anywhere.  Is there more to come in this PR?

**Comment by KaiSzuttor** [comment]
It's not yet clear

**Comment by fweik** [comment]
This is only for discussion purposes. Maybe we should keep in a feature branch instead of a PR? This *could* be the start of a longer project after all.

**Comment by KaiSzuttor** [comment]
I'll push it to a branch

**Pull request closed without merging**
