### PR TITLE
Rotational gamma miscellaneous

### PR DESCRIPTION
**Pull request by psci2195**
1. Usage improvement (e.g. ability to set thermostat parameters ```gamma_translation!=0``` and ```gamma_rotational==0``` simultaneously)
2. Code refactoring
3. Python functionality increase
4. Related User Guide contribution

### CODE REVIEW

**Comment by fweik** [comment]
Looks reasonable to me.

**Comment by psci2195** [comment]
After latest changes in the Espresso master, I need to fix this pull request in order to make Python tests passing. I will work on this.

**Comment by RudolfWeeber** [comment]
On Wed, Aug 24, 2016 at 04:12:06PM -0700, Dr. Bogdan Tanygin wrote:
> After latest changes in the Espresso master, I need to fix this pull request in order to make Python tests passing. I will work on this.
Actually, what changed is that now CI testing runs the full python
testsuite with all myconfig.hpp's stored in maintainer/configs.
Turns out, the tests don't pass :-(
So it might well be unrelated to your work.I'm curently preparing
a pull request to fix the py tests. Once it's merged, I suggest you
merge with the master again and check whether the probems go away.

**Comment by psci2195** [comment]
@RudolfWeeber , thanks, clear.

**Comment by RudolfWeeber** [comment]
The testcases have been fixed. Please merge the current master into
your branch.

**Comment by psci2195** [comment]
Done

**Comment by RudolfWeeber** [comment]
I think, this can be merged.

**Pull request merged**
