### PR TITLE
cmake: add cluster_analysis to the EspressoCore target.

### PR DESCRIPTION
**Pull request by KaiSzuttor**
Since it depends on the core.

### CODE REVIEW

**Comment by fweik** [comment]
Why?

**Comment by KaiSzuttor** [comment]
because we agreed on having a clean library structure.

**Comment by fweik** [comment]
`EspressoCore` does not actually depend on `cluster_analysis`, only the other way round. This should stay it's own target, that depends on `EspressoCore`.

**Review by fweik — CHANGES_REQUESTED** [review]
Don't add the cluster analysis to the `EspressoCore` target, remove dependency of `EspressoCore` on `cluster_analysis` and link `cluster_analysis` in the script interface where it is actually used. `cluster_analysis` can also be moved out of the core folder.

**Pull request closed without merging**
