### PR TITLE
Testcase for ELC and MMM2D

### PR DESCRIPTION
**Pull request by reinaual**
Analytical testcase for ELC and MMM2D

### CODE REVIEW

**Comment by jngrad** [comment]
Once the pylint issues are fixed, you can probably squash all commits into a single one.

**Review by fweik — CHANGES_REQUESTED** [review]
I think this a good start. I think you should also test the case where the system is not neutral (e.g. the two charges don't have equal magnitude). There is some interaction with implicit background charge that is present in P3M in that case, which should also be test. And please use a different charge magnitude than 1. in the neutral case. I think you can just add an additional loop around the body of the `scan` function the sets different charges. The modification of the analytical solution should be straight forward.

**Comment by RudolfWeeber** [comment]
Wasn't the non-neutral case the one that didn't work and that we disabled?
IIRC, we so far didn't succeed in fixing it.

**Comment by fweik** [comment]
Well, we'll find out soon. Also the potential difference case should be tested. So far this only tests dielectric contrast.

**Comment by jngrad** [comment]
Offline discussion with @reinaual: no analytical solution for the potential difference case. If a non-analytical approximation can be found, a new PR will be opened. This test can already be shipped in the 4.1.2 release.

**Review by fweik — APPROVED** [review]

**Comment by jngrad** [comment]
bors r=fweik

**Pull request merged**
