### PR TITLE
Adding Slitpore as LB_Boundary

### PR DESCRIPTION
**Pull request by Harmanjit**
https://github.com/Harmanjit

### CODE REVIEW

**Comment by fweik** [comment]
Thank you for your contribution. Due to our current workload it may take some time until we review and merge your code. You will not be forgotten.

**Comment by mkuron** [comment]
These commits are not ready for merging. They (I assume inadvertedly) revert parts of recent commits in the files you edited and likely don't compile. Please make sure you base your edits on the current master and resubmit.

**Comment by Harmanjit** [comment]
Dear Michael,
Your assumption is right, I had made changes in the files from 3.3.0
version; but when I am trying to install master on my system I get the
following error while executing 'make' (after running bootstrap, and
configure).
Thanks and regards
Harman

P.S.:

:~/espresso-master$ make
Making all in config
make[1]: Entering directory `/home/harmanjit/espresso-master/config'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/harmanjit/espresso-master/config'
Making all in src
make[1]: Entering directory `/home/harmanjit/espresso-master/src'
make  all-recursive
make[2]: Entering directory `/home/harmanjit/espresso-master/src'
Making all in core
make[3]: Entering directory `/home/harmanjit/espresso-master/src/core'
  GEN      myconfig-final.hpp <= ./myconfig-default.hpp
make  all-am
make[4]: Entering directory `/home/harmanjit/espresso-master/src/core'
  GEN      myconfig-final.hpp <= ./myconfig-default.hpp
  GEN      config-version.cpp
make[4]: Leaving directory `/home/harmanjit/espresso-master/src/core'
make[3]: Leaving directory `/home/harmanjit/espresso-master/src/core'
Making all in tcl
make[3]: Entering directory `/home/harmanjit/espresso-master/src/tcl'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/harmanjit/espresso-master/src/tcl'
Making all in python/espressomd
make[3]: Entering directory
`/home/harmanjit/espresso-master/src/python/espressomd'
make  all-am
make[4]: Entering directory
`/home/harmanjit/espresso-master/src/python/espressomd'
  GEN      python-all
  GEN      _init.so
  CXXLD    _system.la
  GEN      _system.so
  CXXLD    particle_data.la
  GEN      particle_data.so
  CXXLD    analyze.la
  GEN      analyze.so
  CXXLD    cellsystem.la
  GEN      cellsystem.so
  GEN      changeVolume.so
  GEN      code_info.so
  GEN      cuda_init.so
  GEN      debye_hueckel.so
  GEN      integrate.so
  CYTHON   interactions.cpp

Error compiling Cython file:
------------------------------------------------------------
...
  cdef extern from "interaction_data.hpp":
    cdef enum OverlappedBondedInteraction: OVERLAP_UNKNOWN = 0,
OVERLAP_BOND_LENGTH, OVERLAP_BOND_ANGLE,\
      OVERLAP_BOND_DIHEDRAL
  cdef extern from "overlap.hpp":
    int overlapped_bonded_set_params(int bond_type,
OverlappedBondedInteraction overlap_type,\
      char * filename);
                     ^
------------------------------------------------------------

interactions.pxd:284:22: Syntax error in C variable declaration

Error compiling Cython file:
------------------------------------------------------------
...
        if self._params["cutoff"]<0:
          raise ValueError("Lennard-Jones cutoff has to be >=0")
        return True

      def _getParamsFromEsCore(self):
        cdef IA_parameters* iaParams
            ^
------------------------------------------------------------

interactions.pyx:154:13: 'IA_parameters' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
          raise ValueError("Lennard-Jones cutoff has to be >=0")
        return True

      def _getParamsFromEsCore(self):
        cdef IA_parameters* iaParams
        iaParams =  get_ia_param(self._partTypes[0],self._partTypes[1])
                               ^
------------------------------------------------------------

interactions.pyx:155:32: undeclared name not builtin: get_ia_param

Error compiling Cython file:
------------------------------------------------------------
...
        # Handle the case of shift="auto"
        if self._params["shift"]=="auto":
          # Calc shift
          self._params["shift"]= -(
(self._params["sigma"]/self._params["cutoff"])**12 -
(self._params["sigma"]/self._params["cutoff"])**6 )

        if lennard_jones_set_params(self._partTypes[0],self._partTypes[1],\
                                  ^
------------------------------------------------------------

interactions.pyx:174:35: undeclared name not builtin:
lennard_jones_set_params

Error compiling Cython file:
------------------------------------------------------------
...
    if len(key) != 2 or (not isinstance(key[0],int)) or (not
isinstance(key[1],int)):
      raise ValueError("NonBondedInteractions[] expects two particle types
as indices.")
    return NonBondedInteractionHandle(key[0],key[1])

  def setForceCap(self,cap):
   if forcecap_set_params(cap):
                        ^
------------------------------------------------------------

interactions.pyx:242:25: undeclared name not builtin: forcecap_set_params

Error compiling Cython file:
------------------------------------------------------------
...
  def setForceCap(self,cap):
   if forcecap_set_params(cap):
     raise Exception("Could not set forcecap")

  def getForceCap(self):
    return force_cap
                   ^
------------------------------------------------------------

interactions.pyx:246:20: undeclared name not builtin: force_cap

Error compiling Cython file:
------------------------------------------------------------
...
       Or called with keyword arguments describing a new interaction."""
    # Interaction id as argument
    if len(args)==1 and isinstance(args[0],int):
      bondId=args[0]
      # Check, if the bond in Espresso core is really defined as a FENE bond
      if bonded_ia_params[bondId].type != self.typeNumber():
                        ^
------------------------------------------------------------

interactions.pyx:262:25: undeclared name not builtin: bonded_ia_params

Error compiling Cython file:
------------------------------------------------------------
...
      {"k":bonded_ia_params[self._bondId].p.fene.k,\
       "d_r_max":bonded_ia_params[self._bondId].p.fene.drmax,\
       "r_0":bonded_ia_params[self._bondId].p.fene.r0}

  def _setParamsInEsCore(self):

fene_set_params(self._bondId,self._params["k"],self._params["d_r_max"],self._params["r_0"])
                  ^
------------------------------------------------------------

interactions.pyx:376:19: undeclared name not builtin: fene_set_params

Error compiling Cython file:
------------------------------------------------------------
...
      {"k":bonded_ia_params[self._bondId].p.harmonic.k,\
       "r_0":bonded_ia_params[self._bondId].p.harmonic.r,\
       "r_cut":bonded_ia_params[self._bondId].p.harmonic.r_cut}

  def _setParamsInEsCore(self):

harmonic_set_params(self._bondId,self._params["k"],self._params["r_0"],self._params["r_cut"])
                      ^
------------------------------------------------------------

interactions.pyx:402:23: undeclared name not builtin: harmonic_set_params

Error compiling Cython file:
------------------------------------------------------------
...
      {"mult":bonded_ia_params[self._bondId].p.dihedral.mult,\
       "bend":bonded_ia_params[self._bondId].p.dihedral.bend,\
       "phase":bonded_ia_params[self._bondId].p.dihedral.phase}

  def _setParamsInEsCore(self):

dihedral_set_params(self._bondId,self._params["mult"],self._params["bend"],self._params["phase"])
                      ^
------------------------------------------------------------

interactions.pyx:428:23: undeclared name not builtin: dihedral_set_params

Error compiling Cython file:
------------------------------------------------------------
...
         "minval":bonded_ia_params[self._bondId].p.tab.minval,\
         "maxval":bonded_ia_params[self._bondId].p.tab.maxval,\
         "invstepsize":bonded_ia_params[self._bondId].p.tab.invstepsize}

    def _setParamsInEsCore(self):
      tabulated_bonded_set_params(self._bondId, self._params["type"],
self._params["filename"])
                                ^
------------------------------------------------------------

interactions.pyx:459:33: undeclared name not builtin:
tabulated_bonded_set_params

Error compiling Cython file:
------------------------------------------------------------
...
    return \
      {"k":bonded_ia_params[self._bondId].p.subt_lj.k,\
       "r":bonded_ia_params[self._bondId].p.subt_lj.r}

  def _setParamsInEsCore(self):
    subt_lj_set_params(self._bondId,self._params["k"],self._params["r"])
                     ^
------------------------------------------------------------

interactions.pyx:508:22: undeclared name not builtin: subt_lj_set_params

Error compiling Cython file:
------------------------------------------------------------
...
    return \
      {"bend":bonded_ia_params[self._bondId].p.angle_harmonic.bend,\
       "phi0":bonded_ia_params[self._bondId].p.angle_harmonic.phi0}

  def _setParamsInEsCore(self):

angle_harmonic_set_params(self._bondId,self._params["bend"],self._params["phi0"])
                            ^
------------------------------------------------------------

interactions.pyx:684:29: undeclared name not builtin:
angle_harmonic_set_params

Error compiling Cython file:
------------------------------------------------------------
...
    return \
      {"bend":bonded_ia_params[self._bondId].p.angle_cosine.bend,\
       "phi0":bonded_ia_params[self._bondId].p.angle_cosine.phi0}

  def _setParamsInEsCore(self):

angle_cosine_set_params(self._bondId,self._params["bend"],self._params["phi0"])
                          ^
------------------------------------------------------------

interactions.pyx:709:27: undeclared name not builtin:
angle_cosine_set_params

Error compiling Cython file:
------------------------------------------------------------
...
    return \
      {"bend":bonded_ia_params[self._bondId].p.angle_cossquare.bend,\
       "phi0":bonded_ia_params[self._bondId].p.angle_cossquare.phi0}

  def _setParamsInEsCore(self):

angle_cossquare_set_params(self._bondId,self._params["bend"],self._params["phi0"])
                             ^
------------------------------------------------------------

interactions.pyx:734:30: undeclared name not builtin:
angle_cossquare_set_params

Error compiling Cython file:
------------------------------------------------------------
...
    return \
      {"r0":bonded_ia_params[self._bondId].p.stretching_force.r0,\
       "ks":bonded_ia_params[self._bondId].p.stretching_force.ks}

  def _setParamsInEsCore(self):

stretching_force_set_params(self._bondId,self._params["r0"],self._params["ks"])
                              ^
------------------------------------------------------------

interactions.pyx:759:31: undeclared name not builtin:
stretching_force_set_params

Error compiling Cython file:
------------------------------------------------------------
...
    return \
      {"A0_l":bonded_ia_params[self._bondId].p.area_force_local.A0_l,\
       "ka_l":bonded_ia_params[self._bondId].p.area_force_local.ka_l}

  def _setParamsInEsCore(self):

area_force_local_set_params(self._bondId,self._params["A0_l"],self._params["ka_l"])
                              ^
------------------------------------------------------------

interactions.pyx:784:31: undeclared name not builtin:
area_force_local_set_params

Error compiling Cython file:
------------------------------------------------------------
...
    return \
      {"phi0":bonded_ia_params[self._bondId].p.bending_force.phi0,\
       "kb":bonded_ia_params[self._bondId].p.bending_force.kb}

  def _setParamsInEsCore(self):

bending_force_set_params(self._bondId,self._params["phi0"],self._params["kb"])
                           ^
------------------------------------------------------------

interactions.pyx:809:28: undeclared name not builtin:
bending_force_set_params

Error compiling Cython file:
------------------------------------------------------------
...
    return \
      {"V0":bonded_ia_params[self._bondId].p.volume_force.V0,\
       "kv":bonded_ia_params[self._bondId].p.volume_force.kv}

  def _setParamsInEsCore(self):

volume_force_set_params(self._bondId,self._params["V0"],self._params["kv"])
                          ^
------------------------------------------------------------

interactions.pyx:834:27: undeclared name not builtin:
volume_force_set_params

Error compiling Cython file:
------------------------------------------------------------
...
    return \
      {"A0_g":bonded_ia_params[self._bondId].p.area_force_global.A0_g,\
       "ka_g":bonded_ia_params[self._bondId].p.area_force_global.ka_g}

  def _setParamsInEsCore(self):

area_force_global_set_params(self._bondId,self._params["A0_g"],self._params["ka_g"])
                               ^
------------------------------------------------------------

interactions.pyx:859:32: undeclared name not builtin:
area_force_global_set_params

Error compiling Cython file:
------------------------------------------------------------
...
    return \
      {"r0":bonded_ia_params[self._bondId].p.stretchlin_force.r0,\
       "kslin":bonded_ia_params[self._bondId].p.stretchlin_force.kslin}

  def _setParamsInEsCore(self):

stretchlin_force_set_params(self._bondId,self._params["r0"],self._params["kslin"])
                              ^
------------------------------------------------------------

interactions.pyx:884:31: undeclared name not builtin:
stretchlin_force_set_params
make[4]: *** [interactions.cpp] Error 1
make[4]: Leaving directory
`/home/harmanjit/espresso-master/src/python/espressomd'
make[3]: *** [all] Error 2
make[3]: Leaving directory
`/home/harmanjit/espresso-master/src/python/espressomd'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/harmanjit/espresso-master/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/harmanjit/espresso-master/src'
make: *** [all-recursive] Error 1


On Thu, Feb 26, 2015 at 2:52 AM, Georg Rempfer <notifications@github.com>
wrote:

> Closed #211 <https://github.com/espressomd/espresso/pull/211>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/espressomd/espresso/pull/211#event-242050756>.
>

**Comment by mkuron** [comment]
The Python interface is currently broken. There is an option for the configure script to build without it, though I can't think of what it's called.

**Comment by mkuron** [comment]
--with_python_interface=no

**Comment by rempferg** [comment]
./configure --without-python-interface should work. I thought those problems were fixed in the current master, though. So better try using an updated master first.

**Pull request closed without merging**
