### PR TITLE
Core: Explicitly include debug.hpp for FORCE_TRACE()

### PR DESCRIPTION
**Pull request by RudolfWeeber**
Build on a compute cluster failed without this. Include what you use...

Fixes #

Description of changes:
 - 

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Review by jngrad — APPROVED** [review]
LGTM. However keep in mind we're currently removing debug macros in project [Interaction Kernel Refactoring](https://github.com/espressomd/espresso/projects/6), see e.g. 0c63f76. `FORCE_TRACE` seems useless, and `GHOST_FORCE_TRACE` is unused, so we will probably remove both of them in the future.

**Comment by fweik** [comment]
I think we should remove all the debug macros. They are less powerful than a debugger and add a lot of coupling.

**Comment by KaiSzuttor** [comment]
bors r=jngrad

**Pull request merged**
