### PR TITLE
cmake: workaround for cmake bug#18349

### PR DESCRIPTION
**Pull request by junghans**
https://gitlab.kitware.com/cmake/cmake/issues/18349

Usually I am against adding random workarounds to any code base, but this is a bug in such wide range of CMake versions that you guys will have users with this issue for years....

### CODE REVIEW

**Review by mkuron — APPROVED** [review]

**Review by hmenke — APPROVED** [review]

**Comment by KaiSzuttor** [comment]
@junghans have you checked if doing the following would fix the issue?:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${MPI_CXX_COMPILE_FLAGS}")
```
The [documentation](https://cmake.org/cmake/help/v3.0/module/FindMPI.html) says:
>In new projects, please use the MPI_<lang>_XXX equivalents

**Comment by junghans** [comment]
@KaiSzuttor the problem persists. If you look at [my fix](https://gitlab.kitware.com/cmake/cmake/merge_requests/2361), the problem is actually in `MPI_COMPILE_OPTIONS`, which then becomes `MPI_${LANG}_COMPILE_OPTIONS`, which is then part of `MPI_CXX_COMPILE_FLAGS`.

**Comment by junghans** [comment]
@KaiSzuttor: You guys required cmake-3.0 which came with https://gitlab.kitware.com/cmake/cmake/blob/v3.0.0/Modules/FindMPI.cmake, so this might be a good time to switch to `MPI_CXX_COMPILE_FLAGS` anyhow.

**Comment by KaiSzuttor** [comment]
thanks, @junghans Could you please switch to the new syntax since you are touching this?

**Comment by junghans** [comment]
@KaiSzuttor  Done

**Comment by KaiSzuttor** [comment]
thanks @junghans

**Review by KaiSzuttor — APPROVED** [review]

**Comment by junghans** [comment]
Fixed in CMake: https://gitlab.kitware.com/cmake/cmake/merge_requests/2368

**Pull request merged**
