### PR TITLE
Travis: Use boost-mpi from Homebrew

### LINKED ISSUE #991: Travis Mac builds: need pre-built boost-mpi libraries from Homebrew
Currently we rebuild Boost (https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb) with the optional MPI variant during Travis build and cache the resulting binary. That is a hack and it requires manual resubmission of a Travis job whenever Boost releases a new version (see #980).

To solve this problem, a pull request should be filed with @homebrew that makes boost-mpi a separate formula, similar to what they already do with boost-python. That way, it would no longer be an optional variant but a formula in its own right, meaning it would be built on @homebrew's buildbots and available for binary download.

Please assign to me, I will take care of this on the next coding day.

### PR DESCRIPTION
**Pull request by mkuron**
Fixes #991. Please also merge to python branch.

Note that this depends on https://github.com/Homebrew/homebrew-core/pull/9598, so wait until that one is merged.

### CODE REVIEW

**Comment by mkuron** [comment]
Homebrew has merged my change, so this pull request is ready to be merged to master and master needs to then be merged to python.

I resubmitted the build, but there are erratic segfaults in `mpi_stop()` -- though only in the Python tests, which aren't relevant for master anyway. I don't think it's Mac-specific and more likely due to newer Boost and OpenMPI versions being used than on the Linux build jobs. @fweik, any suggestion? I am able to reproduce the issue outside of Travis.

**Comment by fweik** [comment]
I'll look into that. That seems to be the same issue we had before, there seems to be some issue with the boost datatype cache and arrays. Unfortunately the datatype cache construction in boost mpi is rather involved...

**Comment by mkuron** [comment]
Ugh. So you are able to reproduce it on Linux?

**Comment by mkuron** [comment]
So this is the likely culprit: https://github.com/boostorg/mpi/blob/415a41f6ea87ce8636d6397dfa5251446f6f0d93/src/environment.cpp#L143 . Indeed, setting a breakpoint there reveals that `boost::mpi::detail::mpi_datatype_map::clear` is called before Espresso's `mpi_stop`:
```
* thread #1: tid = 0x5ed6, 0x0000000101705dc0 libboost_mpi-mt.dylib`boost::mpi::detail::mpi_datatype_map::clear(), queue = 'com.apple.main-thread', stop reason = breakpoint 2.1
  * frame #0: 0x0000000101705dc0 libboost_mpi-mt.dylib`boost::mpi::detail::mpi_datatype_map::clear()
    frame #1: 0x0000000101705ece libboost_mpi-mt.dylib`boost::mpi::detail::mpi_datatype_map::~mpi_datatype_map() + 14
    frame #2: 0x00007fffcfe09178 libsystem_c.dylib`__cxa_finalize_ranges + 332
    frame #3: 0x00007fffcfe094b2 libsystem_c.dylib`exit + 55
    frame #4: 0x0000000100170dfd Python`handle_system_exit + 333
    frame #5: 0x0000000100170a39 Python`PyErr_PrintEx + 41
    frame #6: 0x0000000100170392 Python`PyRun_SimpleFileExFlags + 754
    frame #7: 0x0000000100186b1d Python`Py_Main + 2925
    frame #8: 0x00007fffcfd74255 libdyld.dylib`start + 1

* thread #1: tid = 0x5ed6, 0x00000001012cc744 libEspressoCore.4.dylib`mpi_stop() + 4 at communication.cpp:313, queue = 'com.apple.main-thread', stop reason = breakpoint 3.1
  * frame #0: 0x00000001012cc744 libEspressoCore.4.dylib`mpi_stop() + 4 at communication.cpp:313
    frame #1: 0x00007fffcfe0917f libsystem_c.dylib`__cxa_finalize_ranges + 339
    frame #2: 0x00007fffcfe094b2 libsystem_c.dylib`exit + 55
    frame #3: 0x0000000100170dfd Python`handle_system_exit + 333
    frame #4: 0x0000000100170a39 Python`PyErr_PrintEx + 41
    frame #5: 0x0000000100170392 Python`PyRun_SimpleFileExFlags + 754
    frame #6: 0x0000000100186b1d Python`Py_Main + 2925
    frame #7: 0x00007fffcfd74255 libdyld.dylib`start + 1
```

Any idea what's wrong in our destruction order?

**Comment by mkuron** [comment]
Turns out static variables are destroyed in reverse order of the function that contains them first being called. These destructions are part of the same sequence as `atexit`'s. Therefore, manually calling the function containing the static variable first fixes the issue. 

My fix depends on non-public API of Boost. However, it has been unchanged since Boost 1.36. @fweik, can you please merge the pull request and then merge master to python?

**Pull request merged**
