### PR TITLE
Make call to nvidia-smi conditional on cuda tag

### LINKED ISSUE #2776: CI build failed for merged PR
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/7001

### PR DESCRIPTION
**Pull request by jngrad**
Fixes #2776 (regression introduced by #2774)

### CODE REVIEW

**Review by fweik — APPROVED** [review]

**Review by fweik — CHANGES_REQUESTED** [review]
It think this most robust way is to call it only when it exists, like so:
```bash
command -v nvidia-smi && nvidia-smi
```

**Comment by jngrad** [comment]
But then the nvidia-smi splash screen will be displayed on all jobs, even those that don't require or explicitly forbid the use of a GPU, if the runner happens to have a GPU card.

**Comment by KaiSzuttor** [comment]
@jngrad that does not matter, it's for debugging purposes only

**Comment by jngrad** [comment]
Nevermind, didn't see all non-gpu jobs just failed. The conditional had no effect.

**Review by fweik — DISMISSED** [review]

**Comment by fweik** [comment]
@jngrad the active matter tutorial test failed in staging. Could you please look at this, it does not seem to be deterministic, but it should be if I understand your testing harness correctly... (https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/106664)

**Comment by jngrad** [comment]
did you cancel it?

**Comment by fweik** [comment]
We both did restart it and then I canceled one, there is still a job running it is just not correctly shown in the UI. Should be fine

**Comment by fweik** [comment]
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/106680

**Comment by jngrad** [comment]
the CI interface is confusing, on this run from the same pipeline it shows cancel:
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/106681
I'm currently fixing the tutorial

**Comment by jngrad** [comment]
ok, makes sense
I increased the sampling time for the tutorial test that failed and decreased the sensitivity of a sample test that failed in another PR last week.

**Review by fweik — APPROVED** [review]

**Pull request merged**
