### PR TITLE
Testing: fix IBMVolCons test

### PR DESCRIPTION
**Pull request by biermanncarl**
Description of changes:
The IBMVolCons test includes a test of a contracting or expanding cube. The underlying LB fluid, however, was not able to move due to too low resolution of the grid. This pull request fixes the test and allows the cube to actually relax with a reasonable rate. The cost is a higher LB fluid resolution and consequently more computational effort needed to complete the test.

### CODE REVIEW

**Comment by biermanncarl** [comment]
Should have checked that... this fix does not work since the domain cannot be sub-partitioned (7 is a prime number)

**Comment by RudolfWeeber** [comment]
It should in principle not be necessary to check the IBM volume conservation with LB. The LB particle coupling is independently tested in the VS tracers tests. You should be able to jut use Langevin with kT=0.

**Comment by biermanncarl** [comment]
> It should in principle not be necessary to check the IBM volume conservation with LB. The LB particle coupling is independently tested in the VS tracers tests. You should be able to jut use Langevin with kT=0.

Do we test the `act_on_virtual=False` option of the LB thermostat, though?

**Comment by RudolfWeeber** [comment]
The lb_thermo_virtual test should do that.

**Comment by biermanncarl** [comment]
The current version uses the Langevin thermostat instead of InertialessTracers in a LB fluid and should correctly test IBMVolCons.

**Review by jngrad — APPROVED** [review]
LGTM

**Pull request merged**
