### PR TITLE
Recursive variant

### LINKED ISSUE #889: Script interface: VariantMap in call_method
- c++:
  - The method `T& operator[]` of `std::map` is not a const method. Using `parameters["foo"]` in `call_method` will not compile, because the input argument 'parameters' of `call_method` is a `const VariantMap&`.
- python:
  - When setting `parameters[name] = kwargs[name]` in `call_method` of the class `PScriptInterface`, we need to wrap `kwargs[name]` with `self.make_variant` with the appropriate type, otherwise this will result in a bad `boost::get` at runtime. (same way it is done in `set_params`). As far as I understand it, the supported `**kwargs` for call_method should be arbitrary (?) so we can't rely on the list of valid params to derive the type.

### PR DESCRIPTION
**Pull request by fweik**
- Made the variant type in the script interface recursive, so that functions can return structured data
- Corresponding translation functions in python
- some clean up of the ObjectId handling (needs further improvement)
- Cleanup and fix of the variant conversion

Fixes #889, #856, #855, #854,

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
The python code looks good. 
However, just from reading it, it's hard to judge whether it really does what it should.
I'd suggest putting in a testcase in the python testsuite together with a c++ function returning a recursive variant to check that the conversion really happens as intended.

**Comment by rbardak** [comment]
I'll take a look on friday. Since I'll probably be using this feature, I might as well design some test cases.

**Comment by fweik** [comment]
Tests are included, but I just realized that this broke the Vector?d parameters. Will add a fix.

**Comment by RudolfWeeber** [comment]
Looks good. Can be merged

**Pull request merged**
