### PR TITLE
Remove boost::mpi dependency in CUDA code

### PR DESCRIPTION
**Pull request by mkuron**
@fweik @RudolfWeeber @trau @rempferg 

_constraints.hpp_ included, by means of a very long dependency chain, _boost/mpi/communicator.hpp_.

### CODE REVIEW

**Comment by mkuron** [comment]
The underlying error was this one: https://svn.boost.org/trac/boost/ticket/10998, which is due to insufficiencies in @nvidia's template parser.

**Comment by fweik** [comment]
Can you tell me what the actual include path was?

**Comment by mkuron** [comment]
I can't because I didn't save it. However, `gcc -H` can tell you.

**Comment by mkuron** [comment]
Here is the include chain:
src/core/electrokinetics_cuda.cu
. src/core/constraints.hpp
.. src/core/energy.hpp
... src/core/statistics.hpp
.... src/core/grid.hpp
..... src/core/communication.hpp
...... /usr/include/boost/mpi/communicator.hpp

**Comment by fweik** [comment]
I'm not sure whether we need all those MPI warnings. Also NVCC and MPI should work fine since some time.

**Comment by mkuron** [comment]
We already had them in a couple CUDA files, I just added them to the ones that didn't have them. And actually, CUDA and MPI don't get along on all systems if you use the Autotools build system instead of CMake -- we don't pass the MPI include path to nvcc (CMake's `FindMPI` internally does `mpicc -show` to get them and those do get passed on to nvcc).

**Pull request merged**
