### PR TITLE
maintainer: Escape module python in wrapper script

### LINKED ISSUE #3237: Paths not properly escaped in {i,}pypresso wrapper script
As reported by @jonaslandsgesell:
> If the full path of the build directory contains a space then the pypresso/ipypresso scripts do not work. The paths needs to be set in quotes in the scripts. I can describe this offline.

### PR DESCRIPTION
**Pull request by fweik**
Fixes #3237.

Description of changes:
 - Added quotes around the module path in python wrapper script.

### CODE REVIEW

**Review by jngrad — APPROVED** [review]

**Review by mkuron — APPROVED** [review]

**Comment by jngrad** [comment]
The staging commit ended up outside a branch and could not be reached from the CI.

**Comment by jngrad** [comment]
bors cancel

**Comment by jngrad** [comment]
seriously? not only bors fails the merge and fails to catch the CI failure webhook, it **also** randomly spawns duplicate CI pipelines for already canceled batches? https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/commit/6dbcec3c35fd5f4e98fcf23a6160ab0d3012bf13/pipelines?ref=staging

**Comment by jngrad** [comment]
bors r-
(failed CI)

**Pull request merged**
