### PR TITLE
Thermo translational anisotropic test

### PR DESCRIPTION
**Pull request by bogdan-tanygin**
Description of changes:
- The typo fix in the langevin thermostat Python setter
- Making the translational thermo test anisotropic as the rotational one is already
- Proposed required feature for the whole test: `PARTICLE_ANISOTROPY`. It will stick the present test to fully (translationally and rotationally) anisotropic particles only. This is just a suggestion, I can be wrong
- Stability: 200 runs

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Comment by bogdan-tanygin** [comment]
UPD: the translational deceleration test case has been added

**Comment by RudolfWeeber** [comment]
Could you please modify the test case mass_and_rinertia.py in such a way that everything which does not neeed the PARTICLE_ANISOTROPY feature is still tested, when that feature is not compiled in

**Comment by bogdan-tanygin** [comment]
I'm in progress. It was a technical merge.

**Comment by bogdan-tanygin** [comment]
Done. Stability (of maxset configuration): 144 runs.

**Comment by bogdan-tanygin** [comment]
Disable of `PARTICLE_ANISOTROPY` is also a quite stable test. At least, 10 runs were OK.

**Comment by RudolfWeeber** [comment]
Merged as part of #1081

**Pull request closed without merging**
