### PR TITLE
Bump Python packages version requirements

### PR DESCRIPTION
**Pull request by jngrad**
Description of changes:
- fix numpy 1.20 warnings about deprecated builtin types
- bump Python packages to the versions available in Ubuntu 20.04 (as per #3421)
- prevent running the constant pH tutorial with an unsupported `pint` version

### CODE REVIEW

**Comment by jngrad** [comment]
`pylint` is taking 4 to 12 min to run in the CI environment, while outside the CI environment (using the same docker image on the same runner), it takes 15 seconds. When running a debug session on the runner, executing `pylint` on a single file takes 3 min:
```
$> time pylint --score=no --reports=no --output-format=text testsuite/python/save_checkpoint.py
real    3m12.496s
user    0m6.168s
sys     0m0.217s
```
Re-running the CI job multiple times decreases the `pylint` runtime, which is now down to 26 seconds for `save_checkpoint.py` in the debug session and around 2 min for `pre-commit` in the CI job. Is `pre-commit` using a persistent cache?

**Comment by KaiSzuttor** [comment]
As far as i understand our CI configuration, we are not using any persistent cache. Thus, I cannot explain your observations.

**Comment by jngrad** [comment]
The docker images run with the following bind: `/scratch/cache:/cache`. However the folder `~/.cache/pre-commit` is created the first time we call `pre-commit`, so it's not an issue with caching. The issue probably comes from Python, it takes too long to load the `pylint` tool. In CI:
```
espresso@coyote:~$ time pylint --version
pylint 2.4.4
astroid 2.3.3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]

real    0m20.020s
user    0m0.742s
sys     0m0.091s
```
Outside CI:
```
espresso@8e4a7ed3e5bd:~$ time pylint --version
pylint 2.4.4
astroid 2.3.3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]

real	0m0.458s
user	0m0.401s
sys	0m0.056s
```

**Comment by jngrad** [comment]
@KaiSzuttor can this be merged?

**Review by KaiSzuttor — APPROVED** [review]

**Pull request merged**
