### PR TITLE
Callback refactor

### PR DESCRIPTION
**Pull request by fweik**
Description of changes:
 - This allows mpi callbacks with (almost) arbitraty arguements
- Simplified some of the  callbacks

There are lots of callbacks that can be simplified with this.

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
maybe a stupid question... why donwe have this master slave model at all? cant we have a python interpreter running on all nodes and let each instance call collective functions in the core?

**Comment by fweik** [comment]
Well this is how it is.

**Comment by KaiSzuttor** [comment]
i see

**Comment by fweik** [comment]
It's there for historic reasons, this is just how the chose to implement it. If one wanted to change that the had to be a well defined parallel interface. This could then be either directly exposed e.g. to python, or via the script interface.

**Review by KaiSzuttor — APPROVED** [review]

**Pull request merged**
