### PR TITLE
Test dipolar direct sum methods

### PR DESCRIPTION
**Pull request by jngrad**
Partial fix for #2071

Description of changes:
- add test cases for dds without replica on CPU/GPU, with replica, with DLC

### CODE REVIEW

**Comment by jngrad** [comment]
offline discussion: the test doesn't pass anymore if the dipoles are relaxed with steepest descent:
```diff
diff --git a/testsuite/python/dipolar_mdlc_dds_scafacos_direct.py b/testsuite/python/dipolar_mdlc_dds_scafacos_direct.py
index 7ddcb6c65..0a470baff 100644
--- a/testsuite/python/dipolar_mdlc_dds_scafacos_direct.py
+++ b/testsuite/python/dipolar_mdlc_dds_scafacos_direct.py
@@ -157,6 +157,17 @@ class dds(ut.TestCase):
             system.integrator.set_steepest_descent(
                 f_max=1, gamma=0.001, max_displacement=0.01)
             system.integrator.run(100)
+            dds_cpu = espressomd.magnetostatics.DipolarDirectSumCpu(
+                prefactor=1.2)
+            system.actors.add(dds_cpu)
+            system.integrator.set_steepest_descent(
+                f_max=5,
+                gamma=0.001,
+                max_displacement=0.01)
+            print(system.analysis.energy()["dipolar"])
+            print(system.integrator.run(100))
+            print(system.analysis.energy()["dipolar"])
+            system.actors.clear()
             system.integrator.set_vv()
 
             # compute forces and energies for dawaanr
```

**Comment by RudolfWeeber** [comment]
The difference between Espresso's and Scafacos' direct sum with replica seems to be that Espresso uses a spherical cutoff, i.e.
sqrt(i_x^2 +i_y^2 +i_z^2) <= n_replica^2
whereas scafacos does the full cube.
We probably better check, whether the dds with replica gets monotonically closer to p3m with increasing number of replica or compare or a tiny system against results calculate din Python.

**Comment by jngrad** [comment]
I tried with 2 to 8 replica, with and without DLC, but the deviation to ScaFaCoS did not decrease, while the runtime increased to the order of 1 min.

**Comment by RudolfWeeber** [comment]
It is not possible to make Espressos direct sum with replica agree to scafacos direct sum with replica. 
They use different cutoff rules:

* Espresso: Spherical cutoff on the replica lavel. Only include boxes when i_x^2+i_y^2+i_z^2 <=n_replica^2, ix,y,z in N
* Scafacos: Either don't use spherical cutoff at all (i.e., n_replica=4,4,4 also cinludes i_x=-4,i_y=-4, i_z=-4, or cutoff on the particle distance level (using the cutoff argument).

I'm therefore removing this test.

**Comment by RudolfWeeber** [comment]
Dipolar direct sum with replica is broken for 0 replica. In that case, it should match with the direct summation for open boundaries, which it doesn't
dds_cpu without replica, dds from scafacos, dds gpu match

**Comment by jngrad** [comment]
> Dipolar direct sum with replica is broken for 0 replica. In that case, it should match with the direct summation for open boundaries, which it doesn't

Then why does my test pass?

**Comment by jngrad** [comment]
Also, if you test DDS with replica using 0 replica against ScaFaCoS direct summation, you get the same results after energy minimization (using the diff in the second post of this PR), whereas DDS with open borders doesn't match ScaFaCoS anymore.

**Comment by RudolfWeeber** [comment]
dds_cpu and dds_gpu use minimum image convention in case of perioidic bc, dds with replica and scafacos don't.

**Pull request closed without merging**
