### PR TITLE
Update CI images

### PR DESCRIPTION
**Pull request by jngrad**
Description of changes:
- replace `intel:18` with `intel:19`
- remove `s390x`

### CODE REVIEW

**Comment by mkuron** [comment]
Do we have ppc64 (not ppc64le) testing on Fedora? The reason we tested on s390x was that it's Ubuntu's only big-endian platform and @junghans's builds always discovered endianness bugs in every release.

**Comment by mkuron** [comment]
While you're at it, you can also drop the 32-bit architectures. Ubuntu 20.04 is only weeks away from being released, and that was how long we wanted to support them.

**Comment by junghans** [comment]
Fedora is still building 32-bit packages, but I can always exclude these architectures.

**Comment by RudolfWeeber** [comment]
>Fedora is still building 32-bit packages, but I can always exclude these architectures.

IMO, they can stay active, as long as they work, but no more time should be invested, once they break. Since we’re taking 32bit out of our CI, this will happen sooner or later.

**Comment by junghans** [comment]
Plus you guys get some testing through CoPR as well.

**Review by junghans — APPROVED** [review]

**Review by fweik — APPROVED** [review]

**Pull request merged**
