### PR TITLE
Improve maintainability of build_cmake.sh

### PR DESCRIPTION
**Pull request by jngrad**
The number of pitfalls in a shell script can be reduced if Google's [Shell Style Guide](https://google.github.io/styleguide/shell.xml#Variable_expansion) is followed:
- no more cryptic `if [ ! -z "${var+x}" ]` to test if a variable is undeclared (also, the conditional was used incorrectly and caused the error message `line 94: curl: command not found` in Travis-CI without triggering the trap)
- use CMake-like boolean values and test explicitly if a variable is equal to  `true` or `false` (we had a mix of `true`, `yes` and empty strings)
- every variable is brace-quoted
- every string variable is quoted (no more `build_dir="build maxset"; cd ${build_dir}` causing `bash: cd: too many arguments`)

### CODE REVIEW

**Review by fweik — APPROVED** [review]

**Comment by fweik** [comment]
I think next time something is added to this script we should consider transforming it into python.

**Comment by jngrad** [comment]
I'm not looking forward to rewriting this script as a series of Python `subprocess` commands...

**Comment by fweik** [comment]
There is things like the [`sh`](https://amoffat.github.io/sh/) module that let's you use shell commands as if they were python functions. That is a nice thing to know in general. Maybe we'll just refrain to add further stuff to the ci script then ^^

**Pull request merged**
