### PR TITLE
Moved p3m stresstest to the correct location.

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
@richter-t , did you check?

**Comment by KaiSzuttor** [comment]
@fweik  please let the tests run again. On my repo all tests went well. Went wrong by chance according to @richter-t .

**Comment by fweik** [comment]
Can I merge this except for the failed test?

**Comment by KaiSzuttor** [comment]
yes, can be merged.

**Pull request merged**
