### PR TITLE
CI: automatically closing CI created issues

### PR DESCRIPTION
**Pull request by KaiSzuttor**
for convenience

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
this won't work across pushes :cry:

**Comment by mkuron** [comment]
Why don't you just use the GitHub API to search for the auto-created issue that references the correct pull request?

**Comment by KaiSzuttor** [comment]
we currently only reference the pipeline in the issue

**Comment by mkuron** [comment]
Then search all issues for the pipeline ID.

**Comment by KaiSzuttor** [comment]
You don't know the pipeline ID

**Comment by mkuron** [comment]
Why? `${CI_PIPELINE_ID}` doesn't change between retries.

**Comment by KaiSzuttor** [comment]
But it changes if I push, right?

**Comment by mkuron** [comment]
Yes. I was only talking about a pipeline that fails, but passes after someone clicks the "retry" button.

**Comment by mkuron** [comment]
And if it's the master branch, just close all open auto-created issues.

**Comment by KaiSzuttor** [comment]
that's already possible with this PR

**Pull request closed without merging**
