### PR TITLE
Fix failing sample test in CI

### LINKED ISSUE #3546: CI build failed for merged PR
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/11204

### LINKED ISSUE #3548: CI build failed for merged PR
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/11221

### PR DESCRIPTION
**Pull request by jngrad**
Fixes #3546, fixes #3548

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
why does is fail now and not in the PR adding those tests?

**Comment by jngrad** [comment]
We only test the samples with maxset config in PRs to reduce the load on CI. The empty config is tested on the python branch.

**Comment by KaiSzuttor** [comment]
So I guess you now checked with the empty config?

**Comment by jngrad** [comment]
yes

**Review by KaiSzuttor — APPROVED** [review]

**Pull request merged**
