### PR TITLE
Fix warnings

### LINKED ISSUE #606: Runtime warnings are treated as errors
Creating a runtime warning leads to abort with background_error.

### PR DESCRIPTION
**Pull request by fweik**
Closes #606 .

### CODE REVIEW

**Comment by fweik** [comment]
Espresso now continous on Runtime Warnings. Warnings are in tcl only returned as the result of the command, so they are only displayed if explicitly printed. Not sure if this is what we want.
This is now build in a way that it can easily be extended to a complete runtime message/logging system,
which probably is cleaner as all the printfs.

**Comment by fweik** [comment]
Ok we can not just return the warnings as result... That may overwrite the result of the command.

**Comment by fweik** [comment]
Ok now the warnings are just writen to stderr or stdout, in tcl only if warnings = 1. I can't think of a better mechanism right now.
Possible improvements: Limit number of errors/warnings, sort by level (related, you don't want warnings to shadow errors), rename to runtime messages, use for logging/debuging?

**Comment by RudolfWeeber** [comment]
I think, this can be merged.
See separate issue (#609) regarding error handling in python

**Pull request merged**
