### PR TITLE
ci: Limit tests with non-standard architectures to scheduled pipeline…

### PR DESCRIPTION
**Pull request by fweik**
… runs. Because they take to long.

### CODE REVIEW

**Comment by mkuron** [comment]
Good idea, but nobody will notice if the build fails. You need to enable email notifications or write a bot that opens an issue when a scheduled build fails.

**Comment by fweik** [comment]
Yes, I agree. Email notifications are enable but they go to `espressomd@icp.uni-stuttgart.de` which nobody reads.

**Comment by fweik** [comment]
We could also consider a slack channel or similar.

**Comment by mkuron** [comment]
I'd prefer Mattermost over Slack as that is already built into Gitlab. However we would still need to convince people to actually use it...

**Comment by fweik** [comment]
We should discuss that independent of this issue. It also turns out that @KaiSzuttor gets the email for the pipeline status.

**Comment by mkuron** [comment]
If this pull request gets merged before we have someone monitoring build failures, it's almost certain that builds will be broken within a few days...

**Comment by fweik** [comment]
Doesn't matter, they are all read anyway because they take too long.

**Review by RudolfWeeber — APPROVED** [review]

**Comment by RudolfWeeber** [comment]
Since Kai gets the notifications, I think this can go ahaed. In the normal developing process, both, the long lag times and the false positives are distracting.

**Comment by KaiSzuttor** [comment]
well, i get an email for every job. Therefore, I don't read the notification.

**Comment by fweik** [comment]
You can change it so that it only notifies you if it fails

**Pull request merged**
