### PR TITLE
Adapt lj-demo to recent API changes

### PR DESCRIPTION
**Pull request by mkuron**
This isn't quite working yet. `system.analyze.pressure` returns unreasonable values and `system.analyze.energy['kinetic'] * 2/(3*len(system.part))` does not match the temperature set on the thermostat. According to git-bisect, that was broken by #1418.

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
I don't get why the tests are still parsing despite you saying that energy and pressure calculation is broken.

**Comment by RudolfWeeber** [comment]
On Thu, Jul 05, 2018 at 09:45:39AM -0700, Kai Szuttor wrote:
> I don't get why the tests are still parsing despite you saying that energy and pressure calculation is broken.
If I understand correctly, force capping is active in the demo.
The old capping code ignored thermostat forces, while the new one
probably doesn't.

**Comment by fweik** [comment]
For the demo script this can probably be fixed by just increasing the cap to at least the maximal thermostat noise amplitude.

**Comment by mkuron** [comment]
> For the demo script this can probably be fixed by just increasing the cap to at least the maximal thermostat noise amplitude.

I have tried that and don't see a difference. Either I am underestimating the amplitude by orders of magnitude or something else is broken.

**Comment by mkuron** [comment]
Please merge. I now switch on the thermostat only when parameters have changed. Pressue and temperature measured now looks reasonable. It is not possible anymore to crash the simulation by drastic temperature, particle number or volume changes. Drastic pressure changes can occasionally still cause crashes (negative volumes encountered), but that's not a new problem and may be related to what kind of thermostat is used (I find the "piston mass" choice quite arbitrary, by the way).

**Review by fweik — APPROVED** [review]

**Pull request merged**
