### PR TITLE
Parametric weight function for DPD....

### PR DESCRIPTION
**Pull request by bindgens1**
... with a parabolic weight function

Description of changes:
- New optional parameter "k" in `DPDInteraction` for the exponent for the weight function

### CODE REVIEW

**Comment by fweik** [comment]
~~In principle the `type` parameter is obsolete now, no? `type = 0` is just the same as `k = 0`.~~
Ah sorry, this is of course nonsens.

**Comment by bindgens1** [comment]
yeah 1- x^0 is zero and the weight function is totally gone.

Couldn't find a way to simplify it even more.

**Review by fweik — CHANGES_REQUESTED** [review]
Ok, this looks good to me, but you should add a bit more documentation. In the main docs of the
DPD interaction (6.1.14. DPD interaction in `doc/sphinx/inter_non-bonded.rst`) you should
include the exponent factor into the formulas for the weight function and maybe add a literature
reference to the paper that describes the physical effect of changing the parameter.

**Comment by fweik** [comment]
LGTM, thank you for your contribution. I'll take it from here.

**Review by fweik — APPROVED** [review]

**Pull request merged**
