### PR TITLE
Eigenvectors from gyration_tensor()

### PR DESCRIPTION
**Pull request by davidsean**
Fixes wrong output from the principal component analysis of analysis.gyration_tensor(). The eigenvalues were correct, but the eigenvectors were wrong. Instead of finding what was wrong with the code I just replaced it with GSL's solver.

Description of changes:
 - removed calc_eigenvalues_3x3() and calc_eigenvector_3x3() from utils.cpp (only used by the gyration_tensor())
 - replaced by GSL's linear algebra solver
 - added a unittest that compares results to numpy.linalg's solver

PR Checklist
------------
 - [x] Tests?
   - [ ] Interface
   - [x] Core 
 - [ ] Docs?

### CODE REVIEW

**Comment by davidsean** [comment]
hrm.. looks like using GSL may not have been the best solution, as it is not a REQUIRED package but an OPTIONAL one.

**Comment by KaiSzuttor** [comment]
I think we don't want a gsl dependency, I suggest to remove the wrong code in the core and use numpy for the calculation (we don't have to provide that in the interface) @fweik whats your opinion on that?

**Comment by hmenke** [comment]
Or you could use LAPACK which has to be installed anyway, because it is a dependency of NumPy.

**Comment by RudolfWeeber** [comment]
On Wed, Jun 13, 2018 at 12:46:29AM -0700, Kai Szuttor wrote:
> I think we don't want a gsl dependency, I suggest to remove the wrong code in the core and use numpy for the calculation (we don't have to provide that in the interface)
I don't think, calling np.eig in the interface would be too much of a sin.
Please do not remove the (optional) gsl stuff from the build system, as some cluster analysis features require it.

**Pull request closed without merging**
