### PR TITLE
Tag CI jobs that cannot run in the cloud

### PR DESCRIPTION
**Pull request by mkuron**
I'm going to try to set up some runners on https://www.bw-cloud.org/ soon.

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
Could you please add documentation in the wiki for all of the CI changes you will perform

**Comment by mkuron** [comment]
Will do that once it's running. I can't (or shouldn't) test it before this PR is merged.

**Review by jngrad — APPROVED** [review]

**Pull request merged**
