### PR TITLE
Sphinx-ified Developer's Guide

### PR DESCRIPTION
**Pull request by hmenke**
Ported the developer's guide to Sphinx using Pandoc.  Some handwork was done to correct the hyperlinks.

### CODE REVIEW

**Comment by fweik** [comment]
Not sure if it would be a better idea to start from scratch. The information in the DG is almost completely outdated.

**Comment by KaiSzuttor** [comment]
Maybe put a warning in there notifying a user that the information is outdated, but maybe it's still a good starting point for s.o. (in the sense of a lower barrier to even start) to write the DG.

**Comment by hmenke** [comment]
@KaiSzuttor Warning added.

@fweik Starting from scratch is inevitable but the current DG already gives a nice outline which can be adapted as is.

**Review by KaiSzuttor — APPROVED** [review]
Looks good to me, can be merged.

**Pull request merged**
