### PR TITLE
WIP added particle property for propagation #4603

### PR DESCRIPTION
**Pull request by ThPaul**
Description of changes:
added particle property for propagation

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
I'm currently looking at this PR, because I need to use two types of virtual sites in teh same simulation, which will bi supported by this in the end.

while doing so, I noted a few things. thilo, could you maybe address, those?
* Change the PartilceRange.filter() function such that takes a predicate rather than the `int criterion`. The current  unokenebtauitb nue=xes detauks of the propagation into the particle range, eventhough they are unrelated
* Teh PropagationPredicate and a function filter_particles_by_propagation(ParticleRange& particles, int porpagation) should go into a separate file such as propagation.hpp. The PropagationModes could go thee, too.
* The list of splittable integrators and the perParticleIntegraiotn appear in integrate_step_1 and step_2. this should be centralized into a function, unless they are different
* Please note the naming convention of loer_case_with_underscore for variable names. CamelCase for classes/types
* The logic that chekcs if the (propagation of a particle is x) or (propagaiton of a particle is system default and system_default is x) appears several times. Since the nested conditions are hard to read, this could be outsourced into a function should_propagate_with(mode, p.propagagation, ssytem_default_propagation)

Thanks

**Comment by RudolfWeeber** [comment]
My work in progress on virtual sites base on this pr is in the vs_propagation branch on my Github. 
Basically, I removed teh VirtualSties class hierarchy and instead put the code into free functions taking a CellStructure or a ParticleRange.
These funcitons (e.g., `lb_traers_propagate()` or `vs_relative_update_particles()` filter the particle by propagation type so they ac only on the correct particles.
the Particel::virtual() flag still exists but is no longer used.

I'll still 
* adapt the various vitual sites tests
* add a tests that checks that lb traers and vs relative can successfully be combined in a simulation


Thilo, I tried to steared clear of the parts you are currently working on. I suggest you hold off on merging my branch, until the tests are green.

**Comment by RudolfWeeber** [comment]
I resolve dthe remaining parallelizaoitn issue with overriding the cutoff heck for virtual sites relative. I think the vs_propagaiont branch from my github can now be merged into this.

**Comment by jngrad** [comment]
closing in favor of #4820

**Pull request closed without merging**
