### PR TITLE
Refactor and benchmark Particle

### PR DESCRIPTION
**Pull request by jngrad**
This PR is not meant to be merged (yet).

Following our exchange on #2239, I've developed a benchmarking suite to measure the integration time of pre-equilibrated particle simulations. The suite currently provides scripts for a LJ gas, a LJ liquid, a P3M saline solution and a P3M ionic gas, and runs them using 1/2/4/8/16 cores, 1k/10k particles per core, and 3 versions of `myconfig.hpp`.

The benchmarks are activated in CMake with `-DWITH_BENCHMARKS=ON`. To add your own benchmarks, use `/src/maintainer/benchmarks/lj.py` as a template and add a new line in `/src/maintainer/benchmarks/CMakeLists.txt`. Pass option `--visualize` to `lj.py` to start OpenGL and visualize the simulation.

Execute `/maintainer/benchmarks/suite.sh` to run the benchmarks. The script loops over various `myconfig.hpp` files and measures the impact of including more features in the `struct Particle`. The script also loops over commits in the git history to measure the performance of various implementations of `struct Particle`. The results are stored in `benchmarks.csv`, where the relevant fields are:

* `commit`: git commit (currently testing the original `struct Particle` implementation, a raw pointer implementation and a unique_ptr implementation)
* `config`: version of `myconfig.hpp` (currently testing minimal, default and maxset)
* `script`: benchmark file (currently running `lj.py` and `p3m.py`)
* `arguments`: space-separated list of arguments passed to the benchmark
* `cores`: MPI cores (1 if `mpiexec` was not used)
* `MPI`: `True` if `mpiexec` was used, `False` otherwise
* `mean`: mean execution time of a single integration step (seconds)
* `ci`: 95% confidence interval for the mean

Debug fields:

* `steps_per_tick`: sample size of the mean
* `duration`: duration of the simulation (seconds), should be 1-2 min long
* `E1`, `E2`, `E3`: energy values from the final state of the simulations (to check the benchmark is reproducible)

The benchmark takes 20 hours on my workstation, you can get the raw results [here](https://github.com/jngrad/espresso/blob/4b8ac7d773cf8dc9387e3dc467b35d24fee9a348/data/benchmarks-workstation.csv) (I'll run it on bee next week). The pointer implementation of `struct Particle` runs 23% slower than the original implementation, for both raw and smart pointers. Using the original implementation and default features as a baseline, the increase in integration time can be broken down as follows:

| implementation  | minimal | default | maxset |
|-----------------|---------|---------|--------|
| original        |   91%   |  100%   |  175%  |
| raw pointers    |  111%   |  130%   |  217%  |
| unique pointers |  110%   |  128%   |  215%  |

The pointer implementation reduces the struct size from 928 to 208 bytes. Adding more features increases the execution time in the same way no matter the implementation. We need to change that by re-shuffling the members of Particle substructs to minimize the slow-down.

### CODE REVIEW

**Comment by jngrad** [comment]
As suggested by @RudolfWeeber and @fweik, the ParticleForce member is now contiguous:
```c++
struct Particle {
  ParticlePosition r;
  ParticleForce f;
  std::unique_ptr<ParticleProperties> p;
  std::unique_ptr<ParticleLocal> l;
  std::unique_ptr<ParticleMomentum> m;
  /* followed by feature-enabled members */
};
```
Using a subset of the tests (LJ gas and P3M saline solution), the slow down is now 16% instead of 23%. Adding more features still affects performance:

| implementation  | minimal | default | maxset |
|-----------------|---------|---------|--------|
| original        |   91%   |  100%   |  182%  |
| raw pointers    |  114%   |  132%   |  228%  |
| unique pointers |  113%   |  131%   |  226%  |
| ParticleForce   |  106%   |  119%   |  209%  |

**Comment by jngrad** [comment]
Moved charge and type to the main Particle struct to make the short range loop evaluate faster. LJ liquid is still 10% slower, LJ gas is 20% slower. Electrostatics is now slightly faster. The benchmarks run without `GHOSTS_HAVE_BONDS`.

<table>
  <col>
  <colgroup span="2"></colgroup>
  <colgroup span="2"></colgroup>
  <tr>
    <td></td>
    <th colspan="3" scope="colgroup">LJ gas (dens=0.02)</th>
    <th colspan="3" scope="colgroup">LJ liquid (dens=0.50)</th>
  </tr>
  <tr>
    <th scope="col">implementation</th>
    <th scope="col">minimal</th>
    <th scope="col">default</th>
    <th scope="col">maxset</th>
    <th scope="col">minimal</th>
    <th scope="col">default</th>
    <th scope="col">maxset</th>
  </tr>
  <tr>
    <td>original</td>
    <td>91%</td>
    <td>100%</td>
    <td>169%</td>
    <td>87%</td>
    <td>100%</td>
    <td>182%</td>
  </tr>
  <tr>
    <td>current</td>
    <td>111%</td>
    <td>118%</td>
    <td>188%</td>
    <td>100%</td>
    <td>111%</td>
    <td>191%</td>
  </tr>
</table>
<br>
<table>
  <col>
  <colgroup span="2"></colgroup>
  <colgroup span="2"></colgroup>
  <tr>
    <td></td>
    <th colspan="3" scope="colgroup">P3M gas</th>
    <th colspan="3" scope="colgroup">P3M solvated</th>
  </tr>
  <tr>
    <th scope="col">implementation</th>
    <th scope="col">minimal</th>
    <th scope="col">default</th>
    <th scope="col">maxset</th>
    <th scope="col">minimal</th>
    <th scope="col">default</th>
    <th scope="col">maxset</th>
  </tr>
  <tr>
    <td>original</td>
    <td>97%</td>
    <td>100%</td>
    <td>133%</td>
    <td>89%</td>
    <td>100%</td>
    <td>159%</td>
  </tr>
  <tr>
    <td>current</td>
    <td>97%</td>
    <td>101%</td>
    <td>129%</td>
    <td>86%</td>
    <td>95%</td>
    <td>151%</td>
  </tr>
</table>

**Comment by fweik** [comment]
@jngrad could you please put the benchmarks into a separate pull request? I think we can merge those quickly and there is already interest to extend them.

**Comment by RudolfWeeber** [comment]
@jngrad, could you please  run the corrected benchmarks on the various particle implementations again?

**Comment by jngrad** [comment]
<table>
  <col>
  <colgroup span="2"></colgroup>
  <colgroup span="2"></colgroup>
  <tr>
    <td></td>
    <th colspan="3" scope="colgroup">LJ (vol. fraction=0.02)</th>
    <th colspan="3" scope="colgroup">LJ (vol. fraction=0.50)</th>
    <th colspan="3" scope="colgroup">P3M (vol. fraction=0.25)</th>
  </tr>
  <tr>
    <th scope="col">implement.</th>
    <th scope="col">min</th>
    <th scope="col">def.</th>
    <th scope="col">max</th>
    <th scope="col">min</th>
    <th scope="col">def.</th>
    <th scope="col">max</th>
    <th scope="col">min</th>
    <th scope="col">def.</th>
    <th scope="col">max</th>
  </tr>
  <tr>
    <th scope="row">original</th>
    <td>91%</td>
    <td>100%</td>
    <td>175%</td>
    <td>87%</td>
    <td>100%</td>
    <td>195%</td>
    <td>93%</td>
    <td>100%</td>
    <td>152%</td>
  </tr>
  <tr>
    <th scope="row">current</th>
    <td>108%</td>
    <td>118%</td>
    <td>195%</td>
    <td>94%</td>
    <td>107%</td>
    <td>196%</td>
    <td>91%</td>
    <td>94%</td>
    <td>133%</td>
  </tr>
  <tr>
    <th scope="row">pr2394</th>
    <td>73%</td>
    <td>83%</td>
    <td>127%</td>
    <td>80%</td>
    <td>99%</td>
    <td>157%</td>
    <td>92%</td>
    <td>105%</td>
    <td>136%</td>
  </tr>
</table>

Using commits `c1d850e`, `6fb0487`, `345fd4b`, discarding LJ 10k 0.02 on 8 cores.

**Comment by KaiSzuttor** [comment]
@jngrad can this be closed for now?

**Comment by jngrad** [comment]
Yes, this has derived too much. It will be easier to restart directly from `python`.

**Pull request closed without merging**
