### PR TITLE
CI: do not perform checks if merge.

### PR DESCRIPTION
**Pull request by KaiSzuttor**
Description of changes:
 - remove check jobs from merge branch "doc"

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
why should the registry *not* be public?

**Comment by mkuron** [comment]
Because it contains the Intel image, which we cannot redistribute. Your revert commit didn‘t work, by the way. Just do `git push -f 967cda1:check_skip` to delete it, it isn‘t even needed.

**Review by mkuron — APPROVED** [review]

**Comment by fweik** [comment]
Hm, the merge version should be tested somehow. I'd prefer to merge the PRs before mergin, as travis does.

**Comment by KaiSzuttor** [comment]
We somehow have to distinguish a merge (which triggers a documentation deployment) and pull requests on ~~travis~~gitlab. Therefore, we push merges to a special branch named ``doc``. So how do you want to trigger a job that only runs for merge?

**Comment by KaiSzuttor** [comment]
Btw. travis does not merge, it checks out the PR hash directly.

**Comment by mkuron** [comment]
> We somehow have to distinguish a merge (which triggers a documentation deployment) and pull requests on travis. Therefore, we push merges to the a special branch named doc.

You probably meant Gitlab. Travis doesn't know about the doc branch.

> Btw. travis does not merge, it checks out the PR hash directly.

Well, Travis looks like it builds the merged commit (301d68b) because that is what it shows in the top box. What it actually does though is this, which is identical to what Gitlab does:
```
git fetch origin +refs/pull/1927/merge:
git checkout -qf FETCH_HEAD
```

By the way, what was the original reason why you didn't want to build the documentation on pull requests?

**Comment by fweik** [comment]
The doc build includes deployment of the docs, which you would not want run on PRs.

**Comment by KaiSzuttor** [comment]
Yes, it's only the deployment.

**Comment by mkuron** [comment]
Ok, so let's get this merged.

**Comment by KaiSzuttor** [comment]
@fweik please merge if you are happy

**Pull request merged**
