### PR TITLE
Lb thermo virtual

### LINKED ISSUE #2157: LB Thermostat: acton_on_virtual should default to True

### PR DESCRIPTION
**Pull request by fweik**
Fixes #2157.

Description of changes:
 - Default `thermo_virtual` to `true`.

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
thermostat.turn_off() needs to restore the core value to true, otherwise
using lb after lgv leads to different result than using lb directly.

**Comment by RudolfWeeber** [comment]
Can be merged.

**Comment by fweik** [comment]
Resetting the flag in `turn_off()` breaks the langevin test. This is confusing.

**Comment by fweik** [comment]
Maybe this is to brittle after all....

**Comment by RudolfWeeber** [comment]
On Mon, Aug 20, 2018 at 01:52:40PM +0000, Florian Weik wrote:
> Maybe this is to brittle after all....
The Langevin test also fails in the Python branch on 3 cores for me with the same deviation.
Probably, the accuracy target on the checks for the Maxwell-Boltzmann distribution need to be lowerd.

**Comment by fweik** [comment]
Why is this so sensitive to the number of procs?

**Pull request merged**
