### PR TITLE
Forcecap

### LINKED ISSUE #625: Rework force capping mechanism to get rid of if-blocks in the individual potentials

### PR DESCRIPTION
**Pull request by fweik**
Fixes #625.

Description of changes:
 - Removed individual force capping mechanisms from potentials
 - Introduced global force capping that actually caps the force
 - Moved force capping from NonBondedInteractions to System in
   interface to reflect that it acts on all forces.

PR Checklist
------------
 - [x] Tests?
   - [x] Interface
   - [x] Core 
 - [x] Docs?

### CODE REVIEW

**Review by hmenke — COMMENTED** [review]
You forgot to adapt this signature:

https://github.com/fweik/espresso/blob/64cd2ae962b6102285d48848f953243bda2696b4/src/python/espressomd/interactions.pyx#L395-L405

**Comment by RudolfWeeber** [comment]
This is good to have.
Before merging, please document the force_cap property in the System class.
Also, the old code call on_short_range_ia_change() after setting a cap.
Your code doesn't, as far as I can tell. 
This is correct for your implementation. However, you probably still need to call
invalidate_obs();

Generally speaking, please do not apply clang-format and the like on changed code. It is very difficult to judge, whether something changed by accident in the force and energy functions.

**Comment by fweik** [comment]
@RudolfWeeber ready for review.

**Comment by RudolfWeeber** [comment]
Can be merged

**Pull request merged**
