### PR TITLE
coverage: ignoring testsuite folders.

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Review by fweik — APPROVED** [review]

**Comment by fweik** [comment]
Are you sure that this works? The unit test files seem to be still in the coverage report:
https://codecov.io/gh/espressomd/espresso/pull/1679/tree/src/core/unit_tests

**Comment by KaiSzuttor** [comment]
The reason seems to be a bug of codecov: see https://github.com/codecov/support/issues/426

**Comment by fweik** [comment]
The benefit of having the unit tests in the coverage is that it can be easily seen if they are executed completely. I tend to keep them in.

**Comment by RudolfWeeber** [comment]
I'd also keep them in. In the end, test coverage reporting serves to help us identify holes, which this does.

**Pull request closed without merging**
