### PR TITLE
4.1.3rc

### PR DESCRIPTION
**Pull request by jngrad**
4.1.3 bugfix release. See [release notes](https://github.com/espressomd/espresso/wiki/es-413-release-notes).

### CODE REVIEW

**Comment by christophlohrmann** [comment]
I can have a look if the visualizer and the active matter tutorial work

**Comment by christophlohrmann** [comment]
From visual inspection: Visualizers are working properly. Also the active matter tutorial produces good results

**Review by KaiSzuttor — APPROVED** [review]

**Comment by jngrad** [comment]
@junghans: merged, tagged and released. The official announcement will me made shortly.
https://github.com/espressomd/espresso/releases/tag/4.1.3

**Comment by junghans** [comment]
https://build.opensuse.org/request/show/819607

**Comment by junghans** [comment]
F33, F32 and F31 done.

On EPEL8 I get:
```
The following tests FAILED:
	 73 - minimize_energy (Timeout)
	 78 - hat (Timeout)
	107 - random_pairs (Timeout)
	109 - cluster_analysis (Timeout)
```
on x86_64 and aarch64, see https://koji.fedoraproject.org/koji/taskinfo?taskID=46828288 for details

**Comment by jngrad** [comment]
@junghans Thanks! I also got timeouts with random python tests on [armhf](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/240038) and [i386](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/240039) and unit tests on [ppc64le](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/240359) (all emulated on Ubuntu). I got the tests to pass by simply restarting the CI jobs. Are timeouts on Koji reproducible?

**Comment by RudolfWeeber** [comment]
Thank you for taking care of the bugfix release, Jean-Noël!

**Comment by junghans** [comment]
@jngrad retesting https://koji.fedoraproject.org/koji/taskinfo?taskID=46867060

**Comment by jngrad** [comment]
Only `x86_64` fails now, with a different subset of tests timing out:
```
The following tests FAILED:
	 52 - rotational_inertia (Timeout)
	 97 - npt (Timeout)
	110 - pair_criteria (Timeout)
```
To me this looks like an issue with the Koji build environment. I had a similar experience on Copr with espresso 4.1.1 and 4.1.2, where python tests would randomly time out, especially on EPEL8 ([build 1125553](https://copr.fedorainfracloud.org/coprs/jngrad/espresso-ci/build/1125553/), [build 1125555](https://copr.fedorainfracloud.org/coprs/jngrad/espresso-ci/build/1125555/)).

**Comment by junghans** [comment]
another try https://koji.fedoraproject.org/koji/taskinfo?taskID=46871745

**Comment by junghans** [comment]
After 3 rebuilds it wents through: https://koji.fedoraproject.org/koji/taskinfo?taskID=46871745

**Comment by jngrad** [comment]
Looking again at the Koji build logs, the random timeouts only happen on the OpenMPI version of espresso... The MPICH version, which is tested beforehand, never timed out.

**Comment by junghans** [comment]
> https://build.opensuse.org/request/show/819607

A bunch of tests segfault on openSUSE:
```
[ 1064s] The following tests FAILED:
[ 1064s] 	  2 - RuntimeErrorCollector_test (SEGFAULT)
[ 1064s] 	  6 - MpiCallbacks_test (Failed)
[ 1064s] 	  7 - ParallelScriptInterface_test (Failed)
[ 1064s] 	 14 - ParticleCache_test (Failed)
[ 1064s] 	 63 - gather_buffer_test (Failed)
[ 1064s] 	 64 - scatter_buffer_test (Failed)
[ 1064s] 	 65 - all_compare_test (Failed)
[ 1064s] 	 66 - gatherv_test (SEGFAULT)
[ 1064s] 	 67 - all_gatherv_test (SEGFAULT)
[ 1064s] 	 68 - sendrecv_test (Failed)
[ 1064s] Errors while running CTest
```

**Pull request merged**
