### PR TITLE
Lees edwards rebase

### PR DESCRIPTION
**Pull request by pdebuyl**
Description of changes:
 - Work on #2051
- The implemenation works, passes the test and has a sampel
- Limited to nsquare for now, see #2051 

The PR is submitted to test the CI stuff but I think it would be good to merge already.

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
Thanks a lot.

I took an initial look over the code. Please see the comments below.

```diff
diff --git a/samples/lees_edwards_vis.py b/samples/lees_edwards_vis.py
new file mode 100644
index 0000000..f2dfe23
--- /dev/null
+++ b/samples/lees_edwards_vis.py
@@ -0,0 +1,67 @@
Please add a docstring for the sample

please add
required_featuers = [...] 
and
espressomd.assert_features(required_features)

[...]

+args = np.empty(1)
+
+if len(sys.argv) < 2:
+  print("Please provide the protocol you want to use for testing")
+  sys.exit()
Please provide explanations for the correct commandline syntax or ideally use argparse.


diff --git a/src/core/dpd.cpp b/src/core/dpd.cpp
index 26d843b..c5b0c56 100644
--- a/src/core/dpd.cpp
+++ b/src/core/dpd.cpp
[...]
+#ifdef LEES_EDWARDS
+static Vector3d vel_diff(Vector3d const &x, Vector3d const &y,
+                         Vector3d const &u, Vector3d const &v) {
+  auto shear_velocity = lees_edwards_protocol.velocity;
+  auto ret = u - v;
+
+  auto const dy = std::abs(x[1] - y[1]);
+  if(dy > 0.5 * box_l[1] ) {
+    ret[0] += Utils::sgn(dy) * shear_velocity;
+  }
This funciton might have clients aside from dpd (thermalized drude bonds, virtual sites) and should be somewhere more general.
It should probably also be used unconditionally and just contain 
return u - v;
if LE is not complied in.

The LE shear direciton should not be hard-coded but settable at runtime. Currently several features have incompatible hard-coded directions.

+

diff --git a/src/core/global.cpp b/src/core/global.cpp
index 9164c5e..3d5444d 100644
--- a/src/core/global.cpp
+++ b/src/core/global.cpp
@@ -39,6 +39,10 @@
 #include "tuning.hpp"
 #include "utils/mpi/all_compare.hpp"
 
+#ifdef LEES_EDWARDS
+#include "lees_edwards.hpp"
+#endif
+
 #include <boost/functional/hash.hpp>
 
 #include <functional>
@@ -51,7 +55,7 @@ namespace {
 /** Type describing global variables. These are accessible from the
     front end, and are distributed to all compute nodes. */
 typedef struct {
-  enum class Type { INT = 0, DOUBLE = 1, BOOL = 2 };
+  enum class Type { INT = 0, DOUBLE = 1, BOOL = 2, LEES_EDWARDS_MPI = 3};
   /** Physical address of the variable. */
   void *data;
   /** Type of the variable, either \ref TYPE_INT or \ref TYPE_DOUBLE.*/
@@ -85,6 +89,11 @@ const std::unordered_map<int, Datafield> fields{
      {langevin_gamma.data(), Datafield::Type::DOUBLE, 3,
       "gamma"}}, /* 5  from thermostat.cpp */
 #endif // PARTICLE_ANISOTROPY
+#ifdef LEES_EDWARDS
+     {FIELD_LEES_EDWARDS,
+     //TODO Send correct struct to all nodes
+     {&lees_edwards_protocol, Datafield::Type::LEES_EDWARDS_MPI, 1, "lees_edwards"}}, /* 6  from lees_edwards.cpp */
+#endif
     {FIELD_INTEG_SWITCH,
      {&integ_switch, Datafield::Type::INT, 1,
       "integ_switch"}}, /* 7  from integrate.cpp */
@@ -234,6 +243,12 @@ std::size_t hash_value(Datafield const &field) {
     auto ptr = reinterpret_cast<double *>(field.data);
     return hash_range(ptr, ptr + field.dimension);
   }
+#ifdef LEES_EDWARDS
+  case Datafield::Type::LEES_EDWARDS_MPI: {
+    auto ptr = reinterpret_cast<int *>(field.data);
+    return hash_range(ptr, ptr + field.dimension);
+  }
+#endif
I'd much prefer if LE used the script interface for parameter setting/getting and communication across nodes.

   default:


diff --git a/src/core/grid.hpp b/src/core/grid.hpp
index 7c2e8d6..8463b1a 100644
--- a/src/core/grid.hpp
+++ b/src/core/grid.hpp
[...]
 template <typename T, typename U, typename V>
 inline void get_mi_vector(T &res, U const &a, V const &b) {
Again, please do not hard-code Le direciton.



diff --git a/src/core/initialize.cpp b/src/core/initialize.cpp
index 0b49e74..3d454b7 100644
--- a/src/core/initialize.cpp
+++ b/src/core/initialize.cpp
@@ -48,6 +48,9 @@
 #include "grid_based_algorithms/lb.hpp"
 #include "grid_based_algorithms/lbboundaries.hpp"
 #include "lattice.hpp"
+#ifdef LEES_EDWARDS
+#include "lees_edwards.hpp"
+#endif
 #include "metadynamics.hpp"
 #include "nemd.hpp"
 #include "nonbonded_interactions/reaction_field.hpp"
@@ -116,6 +119,24 @@ void on_program_start() {
   reaction.swap = 0;
 #endif
 
+#ifdef LEES_EDWARDS
+  lees_edwards_protocol.type = LEES_EDWARDS_PROTOCOL_OFF;
Please outsource this to a funciotn in lees_edwards.cpp.
The initializeation of the data structure can be done in its constructur.

@@ -667,6 +688,10 @@ void on_parameter_change(int field) {
     /* Thermalized distance bonds needs ghost velocities */
     on_ghost_flags_change();
     break;
+#ifdef LEES_EDWARDS
+  case FIELD_LEES_EDWARDS:
+    break;
+#endif
Are you sure you don't need at least resort_particles=1? or does that happen somewhere else?

   }
diff --git a/src/core/integrate.cpp b/src/core/integrate.cpp
index c18d878..0f1fd41 100644
--- a/src/core/integrate.cpp
+++ b/src/core/integrate.cpp
+      if (p.r.p[1] >= box_l[1]) {
+	p.m.v[0] -= shear_velocity/2 ;
+	p.r.p[0] -= (offset_at_half_time_step - dround(offset_at_half_time_step * box_l_i[0]) * box_l[0]);
+	p.p.lees_edwards_flag = -1;
Please insert a comment about the value stored in the le flag.

diff --git a/src/core/lees_edwards.cpp b/src/core/lees_edwards.cpp
new file mode 100644
index 0000000..06ffc13
--- /dev/null
+++ b/src/core/lees_edwards.cpp
@@ -0,0 +1,87 @@
+/*
+  Copyright (C) 2018 The ESPResSo project
+
+  This file is part of ESPResSo.
+
+  ESPResSo is free software: you can redistribute it and/or modify
+  it under the terms of the GNU General Public License as published by
+  the Free Software Foundation, either version 3 of the License, or
+  (at your option) any later version.
+
+  ESPResSo is distributed in the hope that it will be useful,
+  but WITHOUT ANY WARRANTY; without even the implied warranty of
+  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+  GNU General Public License for more details.
+
+  You should have received a copy of the GNU General Public License
+  along with this program.  If not, see <http://www.gnu.org/licenses/>.
+*/
+/** \file lees_edwards.cpp
+ */
+
+#include <cmath>
+#include "lees_edwards.hpp"
+#include "integrate.hpp"
+
+lees_edwards_protocol_struct lees_edwards_protocol;
+
+/* Functions to determine the current offset and shear rate with respect to the chosen protocol */
+
+void setup_lees_edwards_protocol() {
+  if (lees_edwards_protocol.type == LEES_EDWARDS_PROTOCOL_OFF) {
switch()?

+double lees_edwards_get_offset(double time) {
+
+  if (lees_edwards_protocol.type == LEES_EDWARDS_PROTOCOL_OFF) {
switch()?
+    return 0.;
+  } else if (lees_edwards_protocol.type == LEES_EDWARDS_PROTOCOL_STEP) {
+    return lees_edwards_protocol.offset;
+  } else if (lees_edwards_protocol.type == LEES_EDWARDS_PROTOCOL_STEADY_SHEAR) {
+    return lees_edwards_protocol.velocity * (time-lees_edwards_protocol.time0);
If you use anything time-dependent, you have to force a resort every time step, force skin or extend the verlet criterion. 
Where does that happen?



diff --git a/src/core/lees_edwards.hpp b/src/core/lees_edwards.hpp
new file mode 100644
index 0000000..f58d530
--- /dev/null
+++ b/src/core/lees_edwards.hpp
@@ -0,0 +1,27 @@
+typedef struct {
+  LeesEdwardsProtocolType type;
+  double time0;
+  double offset;
+  double velocity;
+  double amplitude;
+  double frequency;
+} lees_edwards_protocol_struct;
+void setup_lees_edwards_protocol();
Please provide doxygen docs


diff --git a/src/core/particle_data.hpp b/src/core/particle_data.hpp
index 05bc13a..61bfbc5 100644
--- a/src/core/particle_data.hpp
+++ b/src/core/particle_data.hpp
@@ -130,6 +130,10 @@ struct ParticleProperties {
   constexpr static double q{0.0};
 #endif
 
+#ifdef LEES_EDWARDS
+  int lees_edwards_flag = 0;
+#endif
If this alwasy in [-1,0,1]. Then you can use something with a smaller memory footprint.
Does it have to be stored with the particles in the first place?

diff --git a/src/features.def b/src/features.def
index a78f052..13b10b0 100644
--- a/src/features.def
+++ b/src/features.def
@@ -28,6 +28,7 @@ GHMC
+LEES_EDWARDS                    requires not NPT and not ELECTROSTATICS
Please do not make them compile-teim incompatible. Otherwise they cannot be tested with maxset.hpp.
Instead, please check that nothing incompatible is set during runtime.


diff --git a/testsuite/lees_edwards.py b/testsuite/lees_edwards.py
new file mode 100644
index 0000000..d8de716
--- /dev/null
+++ b/testsuite/lees_edwards.py
@@ -0,0 +1,98 @@
+from __future__ import print_function
+
+import espressomd
+import unittest as ut
+import numpy as np
+
+@ut.skipIf(not espressomd.has_features(["LEES_EDWARDS"]),
+  "Feature not available, skipping test!")
+class LeesEdwards(ut.TestCase):
The test case needs to test for correct calculation of bonded an non-bonded interactions.
+    self.assertEqual(system.lees_edwards[0], "oscillatory_shear")
I'd much prefer a dict-like structure for the system.lees_edwards attribute.

```

**Comment by pdebuyl** [comment]
Hi @RudolfWeeber thank you for the review, I appreciate :-)

I already updated the sample for the `required_features` list and the use of argparse. @bindgens1  and I will work on the remaining issues.

Regarding the use of a user-defined direction for the shear, is it really necessary? It will require a more complex implementation of the columnar cell system, probably introduce more bugs, and we'll need to check at runtime whether the user has not changed the shear or cell system parameters. The tests will also be more complex.

The plan for LE now is to work on the columnar cell system. Once we have a working LE *with the performance* of an actual cell system instead of the n-square system, we can discuss of improvements. What do you think of that?

Regarding the flag `lees_edwards_flag`, is there somewhere else that we can store it while being sure that the property will be kept between the various stages of velocity Verlet? Would a short int be ok here?

**Comment by pdebuyl** [comment]
With respect to the script interface, we did model the interface on other existing interfaces. I just gave a look at the script interface and it is not obvious what the plan is as the current features there have been developed with the script interface in mind.

Is there an example of a feature where the script interface is "only" used to set existing parameters?

**Comment by fweik** [comment]
I think in general that LE should be a boundary condition setting, like periodic and open. To that end I  think you should replace global `int periodic` from `gird.hpp` with something that has ternary state. I think this is cleaner, and it makes compatibility checking easier. Already your feature requirements are too strict. Also I think if this is done properly neighter LEES_EDWARDS nor PARTIAL_PERIODIC needs to be a compile time feature, but of course this has to be benchmarked. Also you have bugs in your folding code: After adding the shift you should fold with the direction you have added the shift to (x), and not with the LE direction (y). Also this should only be folded if the system is periodic in that direction.

**Comment by fweik** [comment]
As for the interface: You can just use the script interface with a global, like

```c++
namespace SI {
class LeesEdwards : public AutoParameters<LeesEdwards> {
  LeesEdwards() {
     add_parameters({"offset", lees_edwards.offset},
                                 {"frequency", lees_edwards.frequency},
                                 ...});
  }
};
}
```

**Comment by RudolfWeeber** [comment]
On Wed, Sep 26, 2018 at 02:05:12AM -0700, Pierre de Buyl wrote:
> Regarding the use of a user-defined direction for the shear, is it really necessary? It will require a more complex implementation of the columnar cell system, probably introduce more bugs, and we'll need to check at runtime whether the user has not changed the shear or cell system parameters. The tests will also be more complex.
You can just store the two indexes (shear direction and shear plane
nourmal) in the parameter structure, then the differences in the
remaining code would be minimal.

Since the columnar cell system is basically a special case of domain
decomposition, which can handle arbitrary grids, this should not be
an issue there, either.

So I find the limitation and potential incompatibility with other
algorithms making similar limitations justified.


> The plan for LE now is to work on the columnar cell system. Once we have a working LE *with the performance* of an actual cell system instead of the n-square system, we can discuss of improvements. What do you think of that?
The free choic4e of directions  has to be planned for from the
beginning, particularly with the cell system.

> Regarding the flag `lees_edwards_flag`, is there somewhere else that we can store it while being sure that the property will be kept between the various stages of velocity Verlet? Would a short int be ok here?
Short int would do. It could only be stored elsewhere efficiently,
if the order of particles is guaranteed not to change between the
two usages. Not sure.

**Comment by pdebuyl** [comment]
Hey @RudolfWeeber @fweik 

We (@bindgens1  and I) are making some progress with the script interface. We had a look at `src/script_interface/README.org` and at the existing features that use the script interface.

The result is in `src/script_interface/lees_edwards` and in `src/python/espressomd/lees_edwards.pyx`.

However, when trying to access the features from the sample file `samples/lees_edwards_vis.py`

    ./pypresso ../samples/lees_edwards_vis.py  steady_shear 1

 we have the error

```python-traceback
Traceback (most recent call last):
  File "../samples/lees_edwards_vis.py", line 35, in <module>
    system = espressomd.System(box_l=[10, 10, 10], time_step=1e-2)
  File "system.pyx", line 143, in espressomd.system.System.__init__
  File "lees_edwards.pyx", line 36, in espressomd.lees_edwards.LeesEdwards.__init__
  File "script_interface.pyx", line 256, in espressomd.script_interface.ScriptInterfaceHelper.__init__
  File "script_interface.pyx", line 29, in espressomd.script_interface.PScriptInterface.__init__
ValueError: Class 'LeesEdwards::LeesEdwards' not found.
```

At this point, we have no idea how to resolve the issue. Would you have a look?

**Comment by bindgens1** [comment]
Hey @pdebuyl @RudolfWeeber @fweik,

I think I solved the issue with the Class. It can now be found.

**Comment by pdebuyl** [comment]
@RudolfWeeber 

Concerning "thermalized bond", which is of use for Drude bonds, we had a look at the code. The issue is that the routine `calc_thermalized_bond_forces` does two things:
1. Use the relative velocity for thermalization. This is fine.
2. Use the center of mass velocity. This does not work with Lees-Edwards enabled. Any "center of mass" reference in Lees-Edwards is meaningless.

So, we can easily use `vel_diff` in `calc_thermalized_bond_forces` but its use with Lees-Edwards would be unphysical. What is your opinion?

**Comment by fweik** [comment]
In my opinion the center of mass thermalization should be removed there anyway.

**Comment by fweik** [comment]
@bindgens1 can this be closed?

**Comment by bindgens1** [comment]
This has been opened by @pdebuyl 

My current working branch is le_merge as it contains the new version of the ghost shift removal. I can open a new pull request with this.

**Comment by fweik** [comment]
@bindgens1 @pdebuyl I just noticed that this isn't the version you are currently working on, so I think to reduce confusion this should probably closed.

**Comment by fweik** [comment]
Superseded by #2976.

**Pull request closed without merging**
