### PR TITLE
Testsuite bug fixes

### LINKED ISSUE #3204: CI build failed for merged PR
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/9379

### PR DESCRIPTION
**Pull request by jngrad**
Fixes #3204 (race condition in eletrokinetics tutorial) and testsuite errors.

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
seems to work now?

**Comment by jngrad** [comment]
it should work, that's essentially the same patch we've been using from April until August
I'm still investigating the error without the patch, but in the meantime we can merge this one.

**Review by KaiSzuttor — APPROVED** [review]

**Comment by jngrad** [comment]
bors retry

**Pull request merged**
