### PR TITLE
Fixed flush for h5md output.

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Comment by fweik** [comment]
Should not ``h5mdfile H5Fclose`` run flush? That would be the same behavior as for regular files.

**Comment by KaiSzuttor** [comment]
According to evangelos it doesnt. But I'll check it myself tomorrow.

**Comment by fweik** [comment]
I would argue that it should.

**Comment by KaiSzuttor** [comment]
According to the API of hdf5 it should, youre right.

**Comment by fortysixandtwo** [comment]
Oops, looks like I didn't call h5md_close.
Sorry for spreading missinformation :[

**Comment by KaiSzuttor** [comment]
Forgot to check, so thanks Evangelos!

**Pull request closed without merging**
