### PR TITLE
Various py fixes and extensions

### PR DESCRIPTION
**Pull request by RudolfWeeber**
See commit summary.

This should be merged after the complete_system_class branch from @fweik, which contains refactoring done by @tobiasrau.

### CODE REVIEW

**Comment by fweik** [comment]
Is there a reason why I should not merge the whole thing here? My branch does not contain anything additional... (On a related note: you know that you can merge?)

**Comment by RudolfWeeber** [comment]
Yes, this branch is based on yours, actually.
I know I can merge, but I didn't want to merge significant
interface chagnes during the course of the coding day to avoid
confusion.

**Comment by fweik** [comment]
Yes, but this branch contains all the commits from my branch :-)

**Comment by RudolfWeeber** [comment]
On Mon, Aug 29, 2016 at 12:11:44PM -0700, Florian Weik wrote:
> > Yes, this branch is based on yours, actually.
> Yes, but this branch contains all the commits from my branch :-)
That's what I meant. :-)

**Comment by fweik** [comment]
This is now handled in #821

**Pull request closed without merging**
