### PR TITLE
Fix failing CI

### LINKED ISSUE #3669: CI build failed for merged PR
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/11800

### LINKED ISSUE #3670: CI build failed for merged PR
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/11801

### LINKED ISSUE #3671: Add GPU fixture in lb_profile sample test
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/11802

### LINKED ISSUE #3672: cmake-format error does not post the style patch
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/224599
is probably not what should happen?

### LINKED ISSUE #3674: CI build failed for merged PR
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/11815

### PR DESCRIPTION
**Pull request by jngrad**
Description of changes:
- add GPU fixture in `lb_profile` (fixes #3671, closes #3669, closes #3670, closes #3674)
- fix incorrect `mesh` checks in P3M methods
- post the style patch (fixes #3672)

### CODE REVIEW

**Review by fweik — DISMISSED** [review]

**Comment by fweik** [comment]
That is a lot of issues!

**Comment by jngrad** [comment]
we don't know yet if it works, and one commit needs to be removed

**Comment by fweik** [comment]
It won't merge until you remove draft...

**Comment by fweik** [comment]
Ah, but the review is dismissed :-)

**Comment by KaiSzuttor** [comment]
i think we should not dismiss reviews on pushing it's very inconvenient

**Review by fweik — DISMISSED** [review]

**Review by fweik — APPROVED** [review]

**Pull request merged**
