### PR TITLE
Disable codecov comments

### PR DESCRIPTION
**Pull request by fweik**

### CODE REVIEW

**Review by hmenke — COMMENTED** [review]
Maybe make all the tests deterministic rather than disabling the coverage comments.  Until then you might want to lower the threshold for failure due to a reduction of coverage.

**Comment by fweik** [comment]
This just disables the comments posted by the bot, not the codecov gh intergration.

**Comment by hmenke** [comment]
What happened to this one?  Why was it closed?

**Comment by RudolfWeeber** [comment]
> What happened to this one?  Why was it closed?
Presumably, because there wasn't agreement on whether it should be
done.
What plan to do is to make the tests fully deterministic, to get rid
of the coverage fluctutations. It would be relevant to know, which
test is responsible for them, because that indicates that there are
two situations which need to be tested explicitly.

**Comment by fweik** [comment]
Turned out that the change did disable all codecov reporting to github, which wasn't what I intended.

**Pull request closed without merging**
