### PR TITLE
Fixed LB Tutorial scripts: updated syntax, fixed imports

### PR DESCRIPTION
**Pull request by KunTares**

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
Isn't there an IPy Notebook for that one? If so, changes need to be ported

**Comment by KaiSzuttor** [comment]
there is an open PR from @iammmiru #1605

**Comment by fweik** [comment]
Ah sorry, 8 dod not think of that. Yes this needs to be ported.

**Comment by jonaslandsgesell** [comment]
Ipy notebooks should be running, irrespectively of the changes here. Please close this PR.

**Pull request closed without merging**
