### PR TITLE
LB function signature

### PR DESCRIPTION
**Pull request by KaiSzuttor**
@pkreissl likes bool more than int

### CODE REVIEW

**Review by pkreissl — CHANGES_REQUESTED** [review]
The `Checkpointing LB` section of the sphinx documentation (in lb.rst) has to be updated, basically doing two replacements (``binary=0`` and  ``binary=1`` to the respective `bool`).

**Comment by RudolfWeeber** [comment]
On Tue, Feb 25, 2020 at 02:30:08AM -0800, Kai Szuttor wrote:
> @pkreissl likes bool more than int
I'd prefer not merging not-so-critical changes into LB to reduce merge conflicts with the Walberla branch.
This PR might fall into that category.

**Comment by pkreissl** [comment]
> On Tue, Feb 25, 2020 at 02:30:08AM -0800, Kai Szuttor wrote: @pkreissl likes bool more than int
> I'd prefer not merging not-so-critical changes into LB to reduce merge conflicts with the Walberla branch. This PR might fall into that category.

I get the point. This PR, however, only makes the signature of the lb load/save checkpoint functions consistent with the rest of the interface (see issue #1942) &ndash; as far as I understand it, this should not conflict with waLBerla integration. If I am wrong, feel free to close this PR.

**Comment by jngrad** [comment]
We could merge it in 4.1.3 only.

**Review by pkreissl — APPROVED** [review]

**Comment by KaiSzuttor** [comment]
@RudolfWeeber

**Comment by fweik** [comment]
@jngrad I think this should be merged and the trivial patch also applied to the walberla branch.

**Review by jngrad — APPROVED** [review]

**Pull request merged**
