### PR TITLE
 Barnes-Hut gpu: Volta, Turing arch and AMD Vega fixes of deadlocks

### LINKED ISSUE #2579: Deadlock in dipolar Barnes-Hutt on the GPU
On an NVidai rtx 2080.

This happens in `sortBH()`, at the device synchronize after launching the `sortKernel()`
The likely cause is that some threads enter an endless loop:

```cuda
__global__ __launch_bounds__(THREADS4, FACTOR4) void sortKernel() {
  int i, k, ch, dec, start, bottom;

  bottom = bottomd;
  dec = blockDim.x * gridDim.x;
  // Start from the end of the nnodesd == 8 * nbodiesd.
  // Reverse order is required now cause octant cells which are more close
  // to the root have a larger count of entities inside (countd[k]).
  // Particles should be sorted over all entities count in the tree array
  // representation made by treeBuildingKernel.
  k = bhpara->nnodes + 1 - dec + threadIdx.x + blockIdx.x * blockDim.x;

  // iterate over all cells assigned to thread
  while (k >= bottom) {
    start = bhpara->start[k];
    // Let's start from the root which has only startd=0 defined
    // in boundingBoxKernel. All other bodies and cells have -1.
    if (start >= 0) {
      for (i = 0; i < 8; i++) {
        ch = bhpara->child[k * 8 + i];
        if (ch >= bhpara->nbodies) {
          // child is a cell
          bhpara->start[ch] = start;  // set start ID of child
          start += bhpara->count[ch]; // add # of bodies in subtree
        } else if (ch >= 0) {
          // Child is a body.
          // This particle should be saved with a stepping over
          // a count of particles in the cells.
          // treeBuildingKernel already has ordered cells in a
          // linear array way. The sortKernel just order random particle
          // indices in the same order. Hence, they will be much faster accessed
          // by forceCalculationKernel and energyCalculationKernel.
          bhpara->sort[start] = ch; // record body in 'sorted' array
          start++;
        }
      }
      k -= dec; // move on to next cell
    }
    __syncthreads(); // throttle
  }
}
```

If `start = bhpara->start[k]`  is less than zero, k is not decremented in the loop.
The deadlock happens most of the time, but not always.
There seems to be an undefined behavior or race condition.
The card's specs are

```
--- device 0: ---
device name: GeForce RTX 2080
compute capability: 7.5
number of multiprocessors: 46
global memory: 8338604032 bytes
size of L2 cache: 4194304 bytes
maximum shared memory per block: 49152 bytes
maximum number of registers per block: 65536
warp size: 32
maximum number of threads per block: 1024
maximum block dimensions : (1024,1024,64)
maximum grid dimensions: (2147483647,65535,65535)
maximum number of threads per multiprocessor: 1024
GPU clock frequency: 1710.000000 MHz
memory clock frequency: 7000.000000 MHz
memory bus width: 256 bits
peak memory bandwidth: 448.000000 GB/s
total constant memory: 65536 bytes
can execute multiple kernels concurrently: yes
can overlap data transfer and computation: yes
can overlap data transfers from/to device: yes
can map host memory: yes
unified address space enabled: yes
compute mode: default (multiple processes/threads per device)
kernel timeout enabled: no
ECC memory enabled: no
is integrated device: no
can access memory of peer device 1: no
```

@psci2195, would you be willing to take a look at this?

### PR DESCRIPTION
**Pull request by bogdan-tanygin**
Fixes #2579, psci2195#223
Does not fix (a matter of a separate PR from me?): #2500

Description of changes:
- An issue was much more complex: deadlocks have been reproduced in different kernels (treeBuildingKernel(), summarizationKernel(), sortKernel()) depending on GPU brand and architecture and depending on parameters. These issues started only since the latest GPU architectures (Volta and Turing level). These issues do not reproduce till Pascal inclusive.
 - The fix was a securing the summarizationKernel() logic by additional iterations count and some additional thread synchronization measures in all complex kernels.
- A number of threads and blocks also have been more precisely aligned between multiprocessors. Threads count was more precisely aligned with the warp (very important since Volta).
- All the fixes have been validated on different GPUs of Pascal and Volta architectures: **GeForce GTX 1070**, **Tesla V100**. According to a research, the Volta fixes should be probably fine for the Turing as well (probably a reporter of #2579 could kindly run the test dawaanr-and-bh-gpu.py on the NVidai rtx 2080).
- The AMD-specific fixes have been introduced and validated on **Radeon Vega Frontier Edition**.

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Comment by bogdan-tanygin** [comment]
+ according to the Gitlab, this works on the Kepler as well.

**Comment by RudolfWeeber** [comment]
Thanks alot.
It also works on the NVidia RTX 2080.

Why are the extra __syncthreads() calls on the AMD card necessary?

**Comment by bogdan-tanygin** [comment]
> Why are the extra __syncthreads() calls on the AMD card necessary?

The treeBuildingKernel() (and some further kernels) is based on a mutex, hence, this is a cuda critical section case. This kind of patterns are known to be sensitive to the GPU hardware architecture specific compilation. I've seen reports of the similar issue. So, as one usually goes in such cases, a syntactic "trick" has been found: it leads to the required machine code.. Even though the algorithm pseudo-code would not require this.

**Review by RudolfWeeber — APPROVED** [review]
Tricking the compiler is probably not a sustainable solution.
I'm merging this, so we can continue to run the test suite on machines with recent gpus.

**Comment by bogdan-tanygin** [comment]
> Tricking the compiler is probably not a sustainable solution.
> I'm merging this, so we can continue to run the test suite on machines with recent gpus.

I agree with this. If the compiler issues will resume on new hardware architectures then this feature should be developed from scratch using non-mutex approach. Even though it could lead to some reduction of the performance. Basically, it can become equal to the existing DDS-GPU magnetostatics. Will see..

**Pull request merged**
