### PR TITLE
Parallel testsuite

### LINKED ISSUE #1195: Python testsuite not run in parallel
The test suite seems to be run only on a single core on Travis. It is also not clear to me, whether the CMAke based testsuite even allows for running the tests in parallel.

### PR DESCRIPTION
**Pull request by fweik**
Fixes #1195 

Description of changes:
 - 

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Review by hmenke — APPROVED** [review]

**Comment by KaiSzuttor** [comment]
Hangs on coulomb_cloud_wall with maxset.hpp (and maybe other featuresets as well) if I test locally.

**Comment by fweik** [comment]
That seems to be the P2NFFT tuning, which is out of our control.... Fixing tha cao and grid in the test did not help.

**Comment by fweik** [comment]
I'm not sure if testing p2nfft and the p3m from scafacos makes sens, the methods are tested within scafacos, and to test the bindings one method should be enough. @RudolfWeeber what do you think about that?

**Comment by fweik** [comment]
Aaaaand there is another mpi deadlock in the energy calc, will fix.

**Comment by fweik** [comment]
@KaiSzuttor should now work (w/o scafacos)

**Comment by RudolfWeeber** [comment]
> I'm not sure if testing p2nfft and the p3m from scafacos makes sens, the methods are tested within scafacos, and to test the bindings one method should be enough. @RudolfWeeber what do you think about that? 
If both of them either do or don't use short range delegation, only one
needs to be tested. If they do the short range differently, both.

**Pull request closed without merging**
