### PR TITLE
System: make box_l a required parameter.

### LINKED ISSUE #1708: min_global_cut can not be set before box_l
MWE:
```python
import espressomd

system = espressomd.System()
system.periodicity = [1, 1, 1]
system.cell_system.skin = 0.4
system.time_step = 0.01
system.min_global_cut = 2.5      
system.box_l = [10.0, 10.0, 10.0]

system.part.add(pos=[2, 2, 2])

system.integrator.run(10)
```
This results in

```bash
ERROR: box_l in direction 0 is too small
ERROR: box_l in direction 1 is too small
ERROR: box_l in direction 2 is too small
ERROR: interaction range 2.9 in direction 0 is larger than the local box size 1
ERROR: interaction range 2.9 in direction 1 is larger than the local box size 1
ERROR: interaction range 2.9 in direction 2 is larger than the local box size 1
ERROR: number of cells 1 is smaller than minimum 8 (interaction range too large or min_num_cells too large)
```

### PR DESCRIPTION
**Pull request by KaiSzuttor**
Fixes #1708 

Description of changes:
 - added box_l to the init arguments of System
 - made required changes to tutorials and tests

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
@RudolfWeeber

**Comment by RudolfWeeber** [comment]
Please merge the branch pr1734 from my github repo, which solves some regressions in the testsuite.

After that, this pr can be merged.
In the future, please do not apply autopep8 or similar formatting before review. It makes it difficult to check whether there are unintended extra changes in there.

**Comment by KaiSzuttor** [comment]
You can directly push to this branch. Sometimes the reformatting of a file is part of the PR and can be forgotten if not done straightaway if many files are involved like in this PR.

**Comment by KaiSzuttor** [comment]
can this be merged? because samples and some documentation depends on the new box_l syntax.

**Comment by RudolfWeeber** [comment]
On Fri, Feb 02, 2018 at 02:46:18AM -0800, Kai Szuttor wrote:
> can this be merged?
From my side, yes.

**Pull request merged**
