### PR TITLE
added python interface for tabulated nonbonded

### PR DESCRIPTION
**Pull request by richter-t**

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
@richter-t testcase? :)

**Comment by KaiSzuttor** [comment]
Can be merged.

**Comment by RudolfWeeber** [comment]
There are still 2 issues with the test case.
1. Please cast the testcase into the python unit-test framework. See coulomb_cloud_wall ore something similar.
2. Please add the test to the CMAKeList.txt, so it actually gets run.

**Comment by richter-t** [comment]
To point 1: not applicable, this is a physical test, point 2 done

**Comment by fweik** [comment]
We use the unittest framework for all tests in python.

**Pull request merged**
