### PR TITLE
Adapt Warning in virtual_sites_relative code to python interface

### PR DESCRIPTION
**Pull request by pkreissl**

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
Shouldn't the core warnings be independent from the interface?

**Comment by pkreissl** [comment]
I guess ideally they should. However, the suggestion to set the minimal cutoff via `setmd min_global_cut` doesn't make sense anymore. Thus the update.
If desired I could just delete the suggestion part, only leaving the warning itself.

**Comment by RudolfWeeber** [comment]
Above all, core warnings should be helpful to the user. We are also currently only shipping one interface.
I'd keep the solution suggestion to avoid user frustration.

**Comment by fweik** [comment]
LGTM

**Pull request merged**
