### PR TITLE
LB: interpolation test: make other than unity velocity boundary condi…

### LINKED ISSUE #2727: LB Interpolation test works only for a particular velocity value
In relation to #2702 it was found that if the boundary velocity in lb_interpolation.py is changed, the test fails (assertions become unequal). Even a slight deviation in velocity (from 1.0 to 1.001) leads to a failure.

### PR DESCRIPTION
**Pull request by KaiSzuttor**
…tion work.

Fixes #2727

### CODE REVIEW

**Comment by jainka** [comment]
It works fine now for different velocity values, thanks!

**Comment by KaiSzuttor** [comment]
could you then please approve the pull request?

**Review by jainka — DISMISSED** [review]

**Comment by KaiSzuttor** [comment]
bors retry

**Review by fweik — APPROVED** [review]

**Pull request merged**
