### PR TITLE
Tuning test

### PR DESCRIPTION
**Pull request by fweik**
Description of changes:
 - New test for the tuning of P3M and P3M_GPU

### CODE REVIEW

**Comment by mkuron** [comment]
The bug #1207 appears to be spreading. It has now infected coulomb_cloud_wall_tune. I'm not sure what these issues have in common, but they are both non-deterministically accessing out-of-bounds memory on macOS.

```
[Traviss-Mac-596:46283] *** Process received signal ***
[Traviss-Mac-596:46283] Signal: Segmentation fault: 11 (11)
[Traviss-Mac-596:46283] Signal code: Address not mapped (1)
[Traviss-Mac-596:46283] Failing at address: 0x7ff00b944000
[Traviss-Mac-596:46283] [ 0] 0   libsystem_platform.dylib            0x00007fff9d67852a _sigtramp + 26
[Traviss-Mac-596:46283] [ 1] 0   libfftw3.3.dylib                    0x0000000108b75f32 fftw_mkstride + 23
[Traviss-Mac-596:46283] [ 2] 0   libEspressoCore.4.dylib             0x0000000109309f91 _Z22calc_long_range_forcesv + 81
[Traviss-Mac-596:46283] [ 3] 0   libEspressoCore.4.dylib             0x0000000109309daf _Z10force_calcv + 1423
[Traviss-Mac-596:46283] [ 4] 0   libEspressoCore.4.dylib             0x000000010931b8dd _Z12integrate_vvii + 173
[Traviss-Mac-596:46283] [ 5] 0   libEspressoCore.4.dylib             0x00000001092deb92 _Z13mpi_integrateii + 66
[Traviss-Mac-596:46283] [ 6] 0   libEspressoCore.4.dylib             0x00000001093aa837 _Z15time_force_calci + 71
[Traviss-Mac-596:46283] [ 7] 0   libEspressoCore.4.dylib             0x000000010936fdbd _ZL11p3m_mc_timePPcPiiddPdS2_S2_ + 1245
[Traviss-Mac-596:46283] [ 8] 0   libEspressoCore.4.dylib             0x000000010936e6c0 _Z17p3m_adaptive_tunePPc + 1936
[Traviss-Mac-596:46283] [ 9] 0   electrostatics.so                   0x000000010afe8977 _ZL51__pyx_pw_10espressomd_14electrostatics_3P3M_15_tuneP7_objectS0_ + 871
[Traviss-Mac-596:46283] [10] 0   electrostatics.so                   0x000000010afe2b6c _ZL24__Pyx_PyObject_CallMethOP7_objectS0_ + 92
[Traviss-Mac-596:46283] [11] 0   electrostatics.so                   0x000000010afe9940 _ZL62__pyx_pw_10espressomd_14electrostatics_3P3M_17_activate_methodP7_objectS0_ + 416
[Traviss-Mac-596:46283] [12] 0   actors.so                           0x000000010aeabfec _ZL24__Pyx_PyObject_CallMethOP7_objectS0_ + 92
[Traviss-Mac-596:46283] [13] 0   actors.so                           0x000000010aeacffb _ZL47__pyx_pw_10espressomd_6actors_5Actor_7_activateP7_objectS0_ + 2907
[Traviss-Mac-596:46283] [14] 0   actors.so                           0x000000010aeabfec _ZL24__Pyx_PyObject_CallMethOP7_objectS0_ + 92
[Traviss-Mac-596:46283] [15] 0   actors.so                           0x000000010aeb3cef _ZL42__pyx_pw_10espressomd_6actors_6Actors_3addP7_objectS0_S0_ + 2159
```

**Comment by fweik** [comment]
They both do p3m tuning. That was the reason I added this test.

**Comment by fweik** [comment]
It is not clear to me what the problem is or how we can progress from here. I also don't have a mac to debug this.

**Comment by mkuron** [comment]
I believe you still have an account (like phy12345) to ssh.physcip.uni-stuttgart.de. You could try debugging there. I also tried debugging this issue a few weeks ago, but I don't really understand the P3M tuning code.

**Pull request merged**
