### PR TITLE
Utils: Increase tolerance of matrix vector product test

### PR DESCRIPTION
**Pull request by RudolfWeeber**
to 8 epsilon

### CODE REVIEW

**Review by fweik — APPROVED** [review]

**Comment by jngrad** [comment]
@junghans does this work for you?

**Comment by junghans** [comment]
Didn't help! see [log](https://github.com/espressomd/espresso/files/4091362/_log.txt)

**Comment by jngrad** [comment]
Oh no, `BOOST_CHECK_CLOSE` takes a percentage value as the tolerance, epsilon must be multiplied by 100! I thought all those wrong unit tests had been corrected in 4.1, but visibly some of them survived.

**Comment by jngrad** [comment]
@fweik I'll take care of it in #3426

**Comment by jngrad** [comment]
Issue resolved by #3427

**Pull request closed without merging**
