### PR TITLE
cmake: separate lib for pdbparser.

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Review by jngrad — APPROVED** [review]
Perfect

**Comment by fweik** [comment]
You should then move the code out of the core folder so that the folder layout reflects the dependencies. (This is so you can not just include the header without adding the dependency in cmake).

**Comment by fweik** [comment]
You should then also move the test :-)

**Comment by KaiSzuttor** [comment]
Have a unit test in the pdbparser directory?

**Comment by fweik** [comment]
Yes, why would it be in `core`?

**Comment by fweik** [comment]
Sorry to nag you again, but I think the folder layout should be either flat or have standard layout (include, src, tests, ...)

**Pull request merged**
