### PR TITLE
Update mmm2d.cpp

### PR DESCRIPTION
**Pull request by KonradBreitsprecher**
Added minus to fulfill F = -dE/dz/.

### CODE REVIEW

**Comment by jonaslandsgesell** [comment]
This change makes particle moves with monte carlo (energy dependent) with mmm2d and a capacitor and MD (using forces) consistent.

**Comment by fweik** [comment]
Test is missing

**Review by fweik — CHANGES_REQUESTED** [review]
Test is missing

**Comment by KonradBreitsprecher** [comment]
I suggest to test E vs F via integrating forces of a particle pair for the following combinations (that are allowed):
- dielectric contrasts: off, 100, inf
- neutral, non-neutral
- const.pot w/wo applied potential
Same for ELC. I'm a bit scared doing this though..

**Comment by fweik** [comment]
Do it, it's still better to know what is broken.

**Review by hmenke — APPROVED** [review]

**Comment by KonradBreitsprecher** [comment]
Changes and tests are part of #1638

**Pull request closed without merging**
