### PR TITLE
utils: Fixed warning from Utils::int_pow and made some math functions…

### PR DESCRIPTION
**Pull request by fweik**
… constexpr

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
could you please add unit tests for constexpr functionality?

**Comment by fweik** [comment]
That is not so easy because the std math functions are not constexpr.

**Comment by fweik** [comment]
(For reference: there is a constexpr math library https://github.com/kthohr/gcem which looks decent)

**Comment by KaiSzuttor** [comment]
I opened a PR with some static asserts plus a new ```constexpr abs```, please merge this or add comments

**Comment by fweik** [comment]
Why is this not fine? Adding just `abs` doesn't help anything.

**Review by KaiSzuttor — APPROVED** [review]

**Comment by fweik** [comment]
FYI: There was some technical issue with the CI: https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/88418

**Pull request merged**
