### PR TITLE
core: Removed MEMBRANE_COLLISION + out_direction

### LINKED ISSUE #2214: membrane_collision is broken
The oif membrane_collision relies on the `p.p.out_direction` being up-to-date. But the `out_direction` is updated by a bonded interaction, which are not guaranteed to be evaluated before the pair interactions are calculated.

### LINKED ISSUE #3416: Out_direction and membrane_collision can be removed
based on Skype discussions with the OIF team, a fix for #2214 has been merged into their code. The fix is too invasive for the main line of Es, though.
Therefore, we'll remove the not-fixed out_direction and membrane_collision from the dev branch.
We will then bring the functionallity back via virtual sites placed at the center of each surface triangle.

### PR DESCRIPTION
**Pull request by fweik**
Fixes #2214. Fixes #3416.

Description of changes:
 - Removed `membrane collision`
 - Removed `out_direction`

### CODE REVIEW

**Comment by jngrad** [comment]
Skimmed through the diff and the changes looked good to me. Can RBCs now cross each other?

**Comment by fweik** [comment]
> Can RBCs now cross each other?

Probably. But I'm not sure what to do about this.

**Comment by jngrad** [comment]
@fweik actually, the simulation crashes as soon as a RBC makes contact with a shape:
```
ERROR: Constraint violated by particle 3 dist -0.999825
Traceback (most recent call last):
  File "motivation.py", line 151, in <module>
    system.integrator.run(steps=2500)
  File "integrate.pyx", line 60, in espressomd.integrate.IntegratorHandle.run
  File "integrate.pyx", line 196, in espressomd.integrate.Integrator.run
  File "utils.pyx", line 264, in espressomd.utils.handle_errors
Exception: Encountered errors during integrate: ERROR: Constraint violated by particle 3 dist -0.999825
```
The bug was present before this PR. We might as well update the [espresso features table](http://espressomd.org/html/doc/introduction.html#available-simulation-methods) to mark OIF as experimental. The OIF Sphinx documentation was written as a walkthrough for the sample, so deleting the sample would make the docs difficult to follow.

**Review by jngrad — APPROVED** [review]

**Comment by fweik** [comment]
@jngrad This is potentially because the interaction with the wall is soft. But I see no point in fixing any of this. For me at least, this is far out of scope.

**Comment by jngrad** [comment]
> the interaction with the wall is soft

I used to be able to squeeze RBC through narrow geometries in the past, and they deformed without causing a crash. A regression was introduced at some point, but I won't look into it. This can be merged as is. Even though CI is red, kodiak won't mind and will pull in the `pint` fix during merging.

**Pull request merged**
