### PR TITLE
4.0.2rc

### PR DESCRIPTION
**Pull request by RudolfWeeber**
Description of changes:
 - 

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Comment by fweik** [comment]
This should be merged into the 4.0 branch, not 4.0.1-release, no?

**Comment by RudolfWeeber** [comment]
On Thu, Mar 14, 2019 at 10:47:28AM +0000, Florian Weik wrote:
> This should be merged into the 4.0 branch, not 4.0.1-release, no?
I had no intention of merging. I picked the base branch such that
the diff makes sense and can be checked.

**Comment by RudolfWeeber** [comment]
@jngrad could you please give the diff between 4.0.1 and this branch a final check and then set the release process in motion?
You can also make a decision about still including the visualizer corrections or deferring them for the next time. They will have to be tested manually in the 4.0.2 branch.

**Comment by mkuron** [comment]
I have confirmed that #2751 and #2677 are safe to cherry-pick.

**Comment by fweik** [comment]
@jngrad did you push to https://github.com/espressomd/espresso/tree/upstream/release-4.0.2 on purpose? Also if some of the ci pipelines are not actually needed please cancel them. They are running the emulated tests, an clog up the CI for hours.

**Comment by jngrad** [comment]
I know, will `git push upstream :upstream/release-4.0.2 release-4.0.2` fix it?

**Comment by fweik** [comment]
I *think* you can only push from local to remote, not remote to remote. But I guess you can just rename the branch on github?

**Comment by jngrad** [comment]
The GitHub interface only enable branch deletion, not renaming. Solved it by deleting then pushing again with the right name.

**Comment by fweik** [comment]
@KaiSzuttor @RudolfWeeber so far we only had branches for the minor versions, not sure how we want to go about this. I would have put the 4.0.2 on the 4.0 branch.

**Comment by RudolfWeeber** [comment]
On Fri, Apr 26, 2019 at 02:35:44PM +0000, Florian Weik wrote:
> @KaiSzuttor @RudolfWeeber so far we only had branches for the minor versions, not sure how we want to go about this. I would have put the 4.0.2 on the 4.0 branch.
For 4.0.1, we made a branch, I think.
If I checkout 4.0, that's what I'd expect to get.

**Comment by mkuron** [comment]
> so far we only had branches for the minor versions, not sure how we want to go about this. I would have put the 4.0.2 on the 4.0 branch.

I agree, but for some reason @KaiSzuttor insisted on keeping the 4.0 branch at 4.0.0 and introducing a branch release-4.0.1 which pointed to the same commit as the v4.0.1 tag. Common practice is that branches should be used for minor versions and tags for patch releases. That would have enabled useful things like allowing other people to post pull request against the release branch...

**Comment by mkuron** [comment]
> If I checkout 4.0, that's what I'd expect to get.

Actually, you should expect to get the latest 4.0.x release plus any further bug fixes that have been merged to that branch. If you check out the 4.0.0 tag, you would get precisely that release.

**Comment by fweik** [comment]
I agree with @mkuron, also I think in the end we did put 4.0.1 into the 4.0 branch (see https://github.com/espressomd/espresso/branches, no 4.0.1 branch).

**Comment by jngrad** [comment]
@fweik there is a 4.0.1 branch: https://github.com/espressomd/espresso/branches/stale

**Comment by fweik** [comment]
Ok, I still think that keeping patch level branches around is odd, after all the patch release should be compatible, and the previous version contains known bugs (hence the bugfix release), and should not be used anymore.

**Comment by RudolfWeeber** [comment]
> Ok, I still think that keeping patch level branches around is odd, after all the patch release should be compatible, and the previous version contains known bugs (hence the bugfix release), and should not be used anymore.
OK, let's implement @mkuron's suggestion for 4.1. Hopefully, this will be the last 4.0.x release.

**Pull request closed without merging**
