### PR TITLE
added minimalistic MDAnalysis support

### PR DESCRIPTION
**Pull request by Marcello-Sega**
Description of changes:
 - adds some basic support for online analysis with MDAnalysis

### CODE REVIEW

**Comment by Marcello-Sega** [comment]
Hi, as discussed at the LMC, here's the patch about MDAnalysis. Mind that I tested it only with MDAnalysis==0.15, not with newer ones. 
There's an example on how to use it here: 

[samples/python/MDAnalysisIntegration.py](https://github.com/espressomd/espresso/pull/1231/files#diff-05e8aa9a94c141701489a4fbbc3e3db0)

If you like the patch I will add tests / support for newer versions, and automate the exposure of espresso data to MDAnalysis, so that it becomes transparent to the user.

**Comment by fweik** [comment]
Thank you, I will fix the remaining macOS issues.

**Comment by fweik** [comment]
Sorry for the delay, we had some issues with updates in our test environment.
Ok, so this looks good. We'd like to have this. It would be nice if you could provide some minimal documentation on how to use it. If it would work with newer versions of MDA, this would of course also be very much appreciated.

**Comment by Marcello-Sega** [comment]
Hi, 
I ported the thing to the latest MDAnalysis version, and dropped support for the older one: the topology system of the two versions is so much different that it is not worth supporting both.

I condensed everything in the `__init__.py` of the MDA_ESP module, adding docstrings, and I polished the usage example in `samples/python/MDAnalysisIntegration.py` 

Let me please know if you need some other kind of documentation (manual, ..., ?)

**Comment by fweik** [comment]
Thank you, that looks good to me. I think the provided examples and in-code documentation is sufficient, but maybe you could mention the existence of this in the IO section of the sphinx docs and link to the appropriate inline docs, just so that people can find out about it.

**Comment by Marcello-Sega** [comment]
Ok will do that asap

**Review by hmenke — APPROVED** [review]
The example should be made compatible with Python 3 by doing
```python
from __future__ import print_function
```
and replaceing all istances of `print ...` by `print(...)`.

**Comment by Marcello-Sega** [comment]
Added the documentation to io.rst, merged last changes, fixed print fcuntion

**Review by fweik — APPROVED** [review]

**Comment by fweik** [comment]
Thank you!

**Pull request merged**
