### PR TITLE
core: thermostat: Removed heat_up/cool_down mechanism for Langevin ty…

### PR DESCRIPTION
**Pull request by fweik**
…pe thermostats

The Langevin-type thermostats (excluding LB), had broken initial forces.
They did still employ the heat_up/cool_down mechanism which is no longer
correct with the philox rng. This is potentially a serious bug, because it makes
the thermostat silently act with a different temperature than set for at least
parts of the time steps.

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
why hast that been caught by any testcase?

**Comment by fweik** [comment]
Because it was not tested.

**Comment by KaiSzuttor** [comment]
Shouldn't the DPD test for the velocity distribution fail if the noise magnitude is wrong?

**Comment by RudolfWeeber** [comment]
You have to trigger the heat_up/cool_down by forcing a recalculation of the initial foces, e.g., via

System.part[0].pos=system.part[0].pos

**Review by KaiSzuttor — APPROVED** [review]

**Pull request merged**
