### PR TITLE
Particle benchmarks

### PR DESCRIPTION
**Pull request by jngrad**
LJ and P3M benchmarks discussed in #2239 and extracted from #2296.

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
In the lj script, you're setting a force cap (20) and never remove it.
You don't need a force cap for steepest descent-based warmups.
Please remove the capping.

Please switch the command line handling to argparse in both test scripts.
I think the simplest solution would be to have
--volume_fraction and --particles_per_core 
and for p3m --bjerrum_length


Please also simplify the p3m script:
* please make use of reduced units 
  q=+1 and q=-1 on half of the particles each
  kT=gamma=1
  p3m accuracy=1E-4
  prefactor to give a Bjerrum length provided by the cmd line

Typical Bjerrum lengths would be on the order of ~4 sigma


The runner script should be written to time the currently checked out version.
Comparisson should than be handled by a separate script which uses the timing script twice.

**Comment by jngrad** [comment]
Good idea. `suite.sh` is now responsible for checking out older git revisions and calling `runner.sh`, which runs the benchmarks on the currently checked out version. I've also rewritten the benchmarking CMake file with CTest to avoid breaking the workflow when a benchmark fails. The LJ and P3M scripts were simplified.

Could you please have a look at the output of the LJ script? For volume fractions below 0.5 without force cap, the script sometimes crashes with this error message:
```
ERROR: particle coordinate out of range, pos = 2.22303e+13, image box = -2147483648
ERROR: particle coordinate out of range, pos = -2.19555e+13, image box = -2147483646
Traceback (most recent call last):
  File "lj.py", line 138, in <module>
    system.integrator.run(min(30 * measurement_steps, 60000))
  File "integrate.pyx", line 91, in espressomd.integrate.Integrator.run
  File "utils.pyx", line 269, in espressomd.utils.handle_errors
Exception: Encoutered errors during integrate: ERROR: particle coordinate out of range, pos = 2.22303e+13, image box = -2147483648
```
You may have to test different seed values at line 88 in lj.py until the error appears (cmd: `pypresso lj.py --particles_per_core 10000 --volume_fraction 0.02`). This also happens with your original script.

**Comment by RudolfWeeber** [comment]
Please add calls to tune_skin before and after p3m setup. The optimal skin is density dependent.
Also, please use particle type 0 for both positively and negatively charged particles, since having more particle types has a performance impact.

**Comment by fweik** [comment]
@RudolfWeeber

**Comment by RudolfWeeber** [comment]
Can be merged. 
Can we somehow schedule a CI job for this once a week at night?
It would have to occupy an entire build machine to be consistent.

**Comment by jngrad** [comment]
Are you sure? The LJ benchmark still fails on my machine depending on the parameters.

**Comment by KaiSzuttor** [comment]
i think we planned to buy CI machines. we need a dedicated one for such benchmarks.

**Comment by mkuron** [comment]
> Can we somehow schedule a CI job for this once a week at night?

Sure.

> It would have to occupy an entire build machine to be consistent.

That's difficult. Our runners are configured for multiple concurrent jobs. We would need to do something hacky that reconfigures the runner for a single job, via a cron job or something.

> I think we planned to buy CI machines.

That depends on whether the university administration gives us the money for it.

> we need a dedicated one for such benchmarks.

Not necessarily, we just need one that doesn't do other stuff at the same time.

**Comment by RudolfWeeber** [comment]
> Are you sure? The LJ benchmark still fails on my machine depending on the parameters.
What parameters precisely. I ran both of them, but did not vary parameters extensively.

**Comment by jngrad** [comment]
Try `mpiexec -n 8 pypresso maintainer/benchmarks/lj.py --particles_per_core=10000 --volume_fraction=0.02`

**Comment by RudolfWeeber** [comment]
I can't reproduce this. Can you please post the error msg?

**Comment by jngrad** [comment]
```
ERROR: particle coordinate out of range, pos = 2.22303e+13, image box = -2147483648
ERROR: particle coordinate out of range, pos = -2.19555e+13, image box = -2147483646
Traceback (most recent call last):
  File "lj.py", line 138, in <module>
    system.integrator.run(min(30 * measurement_steps, 60000))
  File "integrate.pyx", line 91, in espressomd.integrate.Integrator.run
  File "utils.pyx", line 269, in espressomd.utils.handle_errors
Exception: Encoutered errors during integrate: ERROR: particle coordinate out of range, pos = 2.22303e+13, image box = -2147483648
```

**Comment by RudolfWeeber** [comment]
I think I fixed the remaining issues. I'll merge this for now, so we can make use of it.

**Pull request merged**
