### PR TITLE
core: Made calc_non_bonded_pair_energy const-correct.

### PR DESCRIPTION
**Pull request by fweik**
Arguably the same should be done for the forces, making the forces on the particles `mutable`.

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
I think, you lost some multi timestep and possibly npt code

**Comment by fweik** [comment]
Oh, that was not intended... (Really!)

**Comment by fweik** [comment]
Should be good now...

**Comment by RudolfWeeber** [comment]
Can be merged

**Pull request merged**
