### PR TITLE
interaction_data: Recalc coulomb prefactor if temperature changes.

### PR DESCRIPTION
**Pull request by fweik**

### CODE REVIEW

**Comment by mkuron** [comment]
This may be insufficient. I believe the GPU-based electrostatics algorithms only copy the prefactor to the GPU when their setup routine is called from the interface.

**Comment by fweik** [comment]
Yes, they should react on the on_temperature_change hook. An easy way to fix this would be to let on_temp_chage call on_coulomb_change, but that does a lot of extra work...

**Comment by mkuron** [comment]
Looks like Ewald and MMM1D don't even react to `on_coulomb_change`...

**Comment by fweik** [comment]
U'd postpone that until after we have introduced signals.

**Pull request merged**
