### PR TITLE
testsuite: added gpu labels to tests that use the GPU.

### PR DESCRIPTION
**Pull request by KaiSzuttor**
maybe helps for the timeouts...

### CODE REVIEW

**Comment by fweik** [comment]
Did you cross-check that with a grep for usage of `gpu_available` ?

(This list is

```
dds-and-bh-gpu.py
dawaanr-and-dds-gpu.py
engine_lbgpu.py
ek_fluctuations.py
test_checkpoint.py
p3m_gpu.py
lb_stokes_sphere.py
lb_shear.py
lb_switch.py
coulomb_cloud_wall.py
lb_gpu_viscous.py
virtual_sites_tracers_gpu.py
dds-and-bh-gpu-perf.py
observable_cylindricalLB.py
lb_streaming.py
lb_get_u_at_pos.py
save_checkpoint.py
coulomb_cloud_wall_duplicated.py
dawaanr-and-bh-gpu.py
lb_thermostat.py
lbgpu_remove_total_momentum.py
coulomb_tuning.py
gpu_availability.py
lb_poiseuille.py
lb_interpolation.py
ek_eof_one_species_base.py
observable_profileLB.py
lb_boundary.py
lb_thermo_virtual.py
ek_charged_plate.py
lb.py
```
for me, I haven't compared)

**Review by fweik — APPROVED** [review]

**Comment by KaiSzuttor** [comment]
I now did and all of those are labeled

**Comment by jngrad** [comment]
bors retry

**Comment by fweik** [comment]
bors retry

**Pull request merged**
