### PR TITLE
Remove SD

### LINKED ISSUE #233: Remove code duplication in integrate function
Integration loop is duplicated between integrate.cpp (velocity verlet/langevin, stepest descend) and integrate_sd.cpp (BD/SD). This will break within weeks. Needs some thoughts because one and two step integrators. Maybe new hooks (on_...).

### LINKED ISSUE #1091: Decide faith of Stokesian Dynamics (SD)
I'm pretty sure nobody ever used this.  It is not part of any predefined feature set (like `maxset.hpp`), has no tests, no Python interface, and it is unkown whether this even compiles.  Please remove.

### PR DESCRIPTION
**Pull request by hmenke**
Fixes #233, #624, and #1091

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
Please, also for this one, wait for the next Espresso meeting

**Review by fweik — CHANGES_REQUESTED** [review]
Requires offline discussion

**Comment by hmenke** [comment]
I heard that in the meeting a few weeks ago SD was scheduled for removal.  What is blocking the merge of this one?

**Comment by fweik** [comment]
The duplicated main loop that comes with SD is very hard to maintain and has already diverged quiet a bit from the other stuff. If @dschwoerer or somebody else is willing to integrate the method with the normal main loop I will remove it.

**Comment by dschwoerer** [comment]
I am slightly sad to see SD go. I am not using espresso any more, and if there is nobody else who uses it ...

If there would be use for the SD/BD integrators, I could be bothered, but I don't think that this is currently the case ...

**Comment by hmenke** [comment]
Can this be merged?

**Review by fweik — APPROVED** [review]

**Comment by fweik** [comment]
We would also be more happy if we had SD, but we can not fix it at the moment. The code is not lost, and if we find a student in the future we will pick this up again.

**Pull request merged**
