### PR TITLE
Re-enable pylint in CI

### LINKED ISSUE #3194: Python3 linter
`pylint` was recently removed (b720b5c1) because it only checked for one warning that had become a false positive in Python3. We can re-enable it (and move it to the style check job) if there is a need for rules that cannot be enforced by `autopep8`. A few candidates: `class-naming-style`, `const-naming-style`. Feel free to propose more rules here. The full list can be found in [Pylint features](http://pylint.pycqa.org/en/latest/technical_reference/features.html).

### PR DESCRIPTION
**Pull request by jngrad**
Fixes #3194

Rules: `W0102,W0401,W0611,W0612,W0613,W0614,W1505,R0401,R1707,C0202,E0602`

* `W0102`: dangerous-default-value
* `W0401`: wildcard-import
* `W0611`: unused-import
* `W0612`: unused-variable
* `W0613`: unused-argument
* `W0614`: unused-wildcard-import
* `W1505`: deprecated-method
* `R0401`: cyclic-import
* `R1707`: trailing-comma-tuple
* `C0202`: bad-classmethod-argument
* `E0602`: undefined-variable

### CODE REVIEW

**Comment by jngrad** [comment]
espresso-ci correctly posted a message with a excerpt of the pylint report

**Review by christophlohrmann — APPROVED** [review]
I don't really understand what's going on here but I cannot see anything wrong

**Review by fweik — APPROVED** [review]

**Comment by jngrad** [comment]
bors r=fweik

**Comment by jngrad** [comment]
bors r=fweik

**Pull request merged**
