### PR TITLE
test: electrophoresis sampel increase tolerance

### LINKED ISSUE #3816: CI build failed for merged PR
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/12630

### PR DESCRIPTION
**Pull request by RudolfWeeber**
Fixes #3816 

Description of changes:
Increase tolerance for polymer persistence length to mitigate flaky test.

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
shouldn't we make the test deterministic instead of increasing the tolerance?

**Comment by RudolfWeeber** [comment]
Not trivial. Coulomb tuning is involved. The outcome of that is somewhat random.

One would have to figure out how to inject tuning parameters without bloating the sample script so much that it gets confusing to new users.

 

I don’t have time to take that up right now.

**Comment by KaiSzuttor** [comment]
okay, but at which delta do we stop?

**Comment by RudolfWeeber** [comment]
>okay, but at which delta do we stop?

Cannot be answered in the abstract.

**Comment by KaiSzuttor** [comment]
fixed in #3821

**Pull request closed without merging**
