### PR TITLE
Cuda10compat

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
:cry:  seems like hip does not support ``__all_sync``

**Comment by fweik** [comment]
This increases the cuda requirement to cuda 9. What is needed for c++ 14?

**Comment by KaiSzuttor** [comment]
We need cuda9 for c++14

**Review by mkuron — DISMISSED** [review]

**Comment by KaiSzuttor** [comment]
@mkuron can you again tell why we only require cuda 7 but need cuda 9 for c++14?

**Comment by mkuron** [comment]
This should actually be changed to 9:
https://github.com/espressomd/espresso/blob/d9f7826f0a9b99d88b8942ab8511bccea2974ed1/CMakeLists.txt#L201

Then these lines can be deleted:
https://github.com/espressomd/espresso/blob/d9f7826f0a9b99d88b8942ab8511bccea2974ed1/CMakeLists.txt#L218-L220

However, don‘t touch the following lines, which are only used when clang++ is used instead of nvcc (in this case, only Clang needs to support C++14, which it did even before it supported CUDA).
https://github.com/espressomd/espresso/blob/d9f7826f0a9b99d88b8942ab8511bccea2974ed1/CMakeLists.txt#L152-L154

**Comment by RudolfWeeber** [comment]
What is the status, here?

**Review by fweik — APPROVED** [review]

**Pull request merged**
