### PR TITLE
Fix rare failures in CI

### LINKED ISSUE #4126: ScaFaCoS tuning fails (fftw: planner.c:891: assertion failed: flags.u == u)
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/14307

### LINKED ISSUE #4144: CI build failed for merged PR
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/14338

### LINKED ISSUE #4158: CI build failed for merged PR
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/14382

### PR DESCRIPTION
**Pull request by jngrad**
Description of changes:
- remove or replace ScaFaCoS P3M checks due to a bug in the FFTW library (fixes #4126, fixes #4158)
- make raspberry electrophoresis test deterministic (fixes #4144, follow-up to #3842)

### CODE REVIEW

**Comment by jngrad** [comment]
Great, `ewald` is not compiled in, and `p2nfft` won't do in `scafacos_interface.py` due to the cutoff value...

**Comment by RudolfWeeber** [comment]
What’s it with the cutoff? It should be possible to specify it for p2nfft. See the dipolar tests.

 

Otherwise, we’d have to update the Scafacos build script in the Docker repo.

**Comment by jngrad** [comment]
The Coulomb p2nfft returns an interaction range of 11.5, when the box size is only 5. Changing the box size to 12 causes an issue with the number of cells ("1 instead of minimum 8"). I'll update the docker image to compile the ewald method.

**Comment by jngrad** [comment]
Nevermind, I was actually using incorrect p2nfft parameters...

**Review by reinaual — APPROVED** [review]

**Pull request merged**
