### PR TITLE
core: remove angle_dist bond.

### LINKED ISSUE #2330: BOND_ANGLEDIST: Undefined symbol
Myconfig: lj, partial_periodic, BOND_ANGLEDIST.
    
    
    import espressomd._init
ImportError: /scratch/weeber/guards/build/src/core/libEspressoCore.so.4: undefined symbol: _Z16angledist_energyP8ParticleS0_S0_P20Bonded_ia_parametersPd

### PR DESCRIPTION
**Pull request by KaiSzuttor**
Fixes #2330 

Description of changes:
 - removed bonded interaction angle_dist because it's not documented, not tested and not interfaced

### CODE REVIEW

**Comment by pkreissl** [comment]
```
$ ack ANGLEDIST src
src/core/pressure_inline.hpp
191:  case BONDED_IA_ANGLEDIST:
429:    else if (type == BONDED_IA_ANGLEDIST) {

src/core/bonded_interactions/bonded_interaction_data.hpp
41:  BONDED_IA_ANGLEDIST,

src/python/espressomd/interactions.pxd
582:        BONDED_IA_ANGLEDIST,
```
I think you missed these.

**Comment by KaiSzuttor** [comment]
thanks @pkreissl

**Review by pkreissl — APPROVED** [review]
lgtm

**Review by fweik — APPROVED** [review]

**Comment by RudolfWeeber** [comment]
On Sat, Oct 27, 2018 at 01:14:30PM +0000, Florian Weik wrote:
> Merged #2338 into python.
This doesn't go into 4.0.1, does it?

**Comment by fweik** [comment]
It should because it is the fix for #2330, otherwise a different solution for that is needed.

**Comment by RudolfWeeber** [comment]
This cannot be cherry-picked well
* it pulls in some of the re-shuffled bond code, which should definitely not go into 4.0.1
* It may let builds with myconfig.hpps fail, which worked for 4.0.0 if they defined hte feature

**Comment by fweik** [comment]
Ok, then we need some fix for #2330.

**Pull request merged**
