### PR TITLE
Anisotropic rotational diffusion test

### PR DESCRIPTION
**Pull request by bogdan-tanygin**
Description of changes:
 - I've added the anisotropic rotational diffusion test. It is similar to a translational one which we already have in the `mass-and-rinertia_per_particle.py`. I've taken some measures to avoid a performance impact: limited loops for this specific calc and only 1 test case. Compare to overall bunch of python tests run, probably, there is not significant increase now: 17 minutes vs 15 minutes before. However, of course, up to the team to decide whether it is worth that. In my opinion: the rotational diffusion is a critically important physical process in Langevin Dynamics and its variance should be validated.
- Refactoring in the lab<->body frame of reference transformation: now it is tests common based script.

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Comment by bogdan-tanygin** [comment]
Maybe, it makes sense to have some tests (like this one) commented out or removed from the file `testsuite/CMakeLists.txt`. This test is performance consuming. However, the existing rotational motion algorithm is well developed and barely will fail some tests. Such tests are probably needed for some long period validations during significant MD changes. Particularly, I've planned to use it to show that the new Brownian Dynamics passes the same tests as existing LD. This is why I've opened this pull request (in a test driven way).

**Comment by bogdan-tanygin** [comment]
This is one of tests which validate both Velocity Verlet LD and future BD. Hence, it indirectly relates to https://github.com/espressomd/espresso/issues/1360.

**Comment by bogdan-tanygin** [comment]
It is already a part of #1842.
I've not closed it only because I was not sure about the future of #1842. If it is already approved for the release 4.1 then we can close this PR.

**Comment by RudolfWeeber** [comment]
The mass and rinertia test reached a complexity so that I don't really understand it anymore.
Could you please clarify in which way this pr goes beyond what is already tested in the Langevin thermostat testcase?
That  tests roational and translatioal diffusion coefficients with global and per particle gamma and temperature via Green-Kubo and also it tests Maxwell-Boltzmann velocity distributions.

For rotation, only isotropic inertia tensors are tested.
Does this test go beyond that?

**Comment by bogdan-tanygin** [comment]
@RudolfWeeber thanks for the feedback. I agree regarding the complexity, I already have the corresponding task #1905. The tests improvement here are tightly connected to the BD and LD results match comparison. I also need to backport the latest changes from the #1842.

> Does this test go beyond that?

1. Yes it does, this is an anisotropic rotational diffusion test. However, it requires too much of the test runtime. This is why I've relocated this part to the non-automically run test mass-and-rinertia_per_particle_rotdiff-longrun.py in the #1842.

2. Except the anisotropic rotational diffusion, by a physical nature, you are right. The Langevin thermostat testcase, indeed, validates fundamentally the same things. The mass and rinertia test does the same but as an integrated (/summed/averaged) practical result (variance = 2 * D * time).

Shortly, a relation is like this:

[langevin_thermostat.py] + [Es. VV integrator] + statistical rules = [mass-and-rinertia_per_particle]

If we are fully sure that the VV integrator is properly tested by other tests then, indeed, we could consider a removal of the test mass-and-rinertia_per_particle with a check that all test parameters are ported to the langevin_thermostat.

**Comment by bogdan-tanygin** [comment]
This PR depends on #2021.

**Comment by bogdan-tanygin** [comment]
For more durable runs I've detected the instability of the test. It could be either a technical or a conceptual issue. In the latter case extra theoretical/bibliography study is needed. Anyway, the present PR is not consistent anymore. I'll work on this separately (#2029).. Propose to close it.

**Pull request closed without merging**
