### PR TITLE
Pre commit plus new images

### PR DESCRIPTION
**Pull request by KaiSzuttor**
Contains #3619 #3606

Description of changes:
- pulled out tool version checking to separate files
- added configuration file for `pre-commit`
- added `cmake-format` configuration and style fix
- use new docker images created using GitHub Actions

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
``` bash
$ maintainer/CI/fix_style.sh
clang-format.............................................................Passed
autopep8.................................................................Passed
cmake-format.............................................................Passed
executable flags.....................................(no files to check)Skipped
```
Works now... have to look at the last check tough

**Comment by KaiSzuttor** [comment]
> Works now... have to look at the last check tough

Checked, there is no file because no non-script file is executable

**Review by jngrad — APPROVED** [review]

**Comment by jngrad** [comment]
The new workflow is now documented in the CI docs.

**Comment by KaiSzuttor** [comment]
thanks @jngrad

**Pull request merged**
