### PR TITLE
Remove PDB parser feature

### PR DESCRIPTION
**Pull request by jngrad**
The consensus offline at the ICP and online in #1441 is to drop support of the PDB parser feature in favor of the dedicated python package MDAnalysis.

### CODE REVIEW

**Comment by fweik** [comment]
LGTM, @RudolfWeeber what do you think?

**Comment by fweik** [comment]
Do you thinks we should consider adding more docs/examples on how to use Espresso with MDAnalysis? I'd think a lot of hours and hand-rolled code could be avoided if this was more well known...

**Review by fweik — APPROVED** [review]

**Comment by jngrad** [comment]
Should this be part of 4.1.1? MDAnalysis is far more reliable than the pdbparser, which would break on the first occurrence of two values not separated by a whitespace (typical cases: large atom ids for ions in PDB frames extracted from Gromacs trajectories, altLoc or iCode fields in protein models).

**Comment by fweik** [comment]
Thats a breaking change in a bugfix release, I think we should refrain from that.

**Comment by jngrad** [comment]
bors r=fweik

**Comment by jngrad** [comment]
bors r-
(failed merge on staging)

**Comment by jngrad** [comment]
bors r=fweik

**Pull request merged**
