### PR TITLE
Compilation fix for the GAUSSRANDOM* features

### PR DESCRIPTION
**Pull request by psci2195**

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
A more complete solution is in #465. 
It adds test coverage via Travis CI, it fixes the errors that the Travis build uncovered and it adds the various noise shapes in features.def, such that they should be visible in "code_info"

**Comment by fweik** [comment]
You mean #468 ?

**Comment by RudolfWeeber** [comment]
Yes

**Comment by fweik** [comment]
Closed by #468

**Pull request closed without merging**
