### PR TITLE
LE docu + addition to LB docu

### PR DESCRIPTION
**Pull request by bindgens1**
There will be a second pull request if the new part of the LB is finished. I suggest to merge both at the time. 

Fixes #

Description of changes:
 - 

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
CUDA build should be green according to the pipelines on gitlab. I don't know why the status here was not updated.

**Comment by bindgens1** [comment]
It was green when I left office yesterday

**Comment by hmenke** [comment]
The “Details” button is gone as well.

**Comment by KaiSzuttor** [comment]
I "repaired" it manually by rerunning the result stage on gitlab.

**Review by rempferg — APPROVED** [review]

**Pull request merged**
