### PR TITLE
More robust test for ferrofluid tutorial

### LINKED ISSUE #2891: Ferrofluid tutorial part3 sometimes fails test
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/7570

### PR DESCRIPTION
**Pull request by RudolfWeeber**
@jngrad 
fixes #2891

### CODE REVIEW

**Review by jngrad — DISMISSED** [review]

**Comment by fweik** [comment]
bors r=jngrad

**Comment by jngrad** [comment]
I'm removing the chi_L check for now, it's too unpredictable. Feel free to re-introduce it in a future PR.

**Review by jngrad — APPROVED** [review]

**Comment by jngrad** [comment]
bors cancel
bors retry

**Pull request merged**
