### PR TITLE
core: particle_data: Made external forces/torques deactivable again

### PR DESCRIPTION
**Pull request by fweik**

### CODE REVIEW

**Comment by fweik** [comment]
@KaiSzuttor  The clang-tidy warning is a false positive, this is why this was broken.

**Comment by jngrad** [comment]
is it just a matter of removing this line?
https://github.com/espressomd/espresso/blob/1645121ee47d6a5cb12222f753e0adc36411f09a/.clang-tidy#L28

**Comment by fweik** [comment]
Yes, but the original change was made automatically by `clang-tidy -fix`, which means all places where this was changed with `Utils::Vector` have to be checked. The replaced version is not equivalent...

**Comment by fweik** [comment]
The offending PR was #2632. The rest looks fine. This is arguably a bug in the clang tidy rule. We could also mark this two place `NOLINT`, I think in general the rule is useful. @KaiSzuttor what do you think?

**Comment by fweik** [comment]
For the record: This has been fixed in clang tidy, as far as I can tell...

**Comment by jngrad** [comment]
it doesn't look too bad:
```bash
git diff -U1 454d62036f^ HEAD | grepdiff 'Vector3d{}' --output-matching=hunk | colordiff | less -R
```
then `/Vector3d\{\}` and `/\.empty` show only 3 occurences: the two you already fixed, and one in `src/core/unit_tests/field_coupling_fields_test.cpp` that is fixed with `Vector3d{0.0, 0.0, 0.0}`.

**Comment by fweik** [comment]
No, it's fine; I checked.

**Comment by fweik** [comment]
@RudolfWeeber

**Comment by RudolfWeeber** [comment]
Please add a corresponding test to particle.py

**Comment by fweik** [comment]
It's not observable.

**Review by RudolfWeeber — APPROVED** [review]
Right.

**Pull request merged**
