### PR TITLE
Torus shape testcase

### LINKED ISSUE #2686: Implement test for torus shape

### PR DESCRIPTION
**Pull request by itischler**
Fixes #2686 

Description of changes:
 - torus shape distance vector fixed
 - torus shape added is now testes

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
This seems to contain ek checkpointing stuff not pertaining to the torus shape.

**Comment by fweik** [comment]
@RudolfWeeber

**Comment by RudolfWeeber** [comment]
Please use Shape.calc_distance() rather than the indirect way via constraints, non bonded interactions and particles.
Does this test points inside and outside the torus? If not, please add that.

**Review by RudolfWeeber — APPROVED** [review]

**Pull request merged**
