### PR TITLE
Automatic closing of CI created issues part 2

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
depends on https://github.com/espressomd/docker/pull/75

**Comment by KaiSzuttor** [comment]
How do we test this?

**Comment by fweik** [comment]
You mean continuously? We probably don't.

**Comment by KaiSzuttor** [comment]
actually also just for now

**Comment by fweik** [comment]
idk, I also think this is not terribly important and we shouldn't spend much time on it.

**Comment by KaiSzuttor** [comment]
@mkuron you are invited to contribute... otherwise I will close this PR

**Review by fweik — APPROVED** [review]

**Pull request merged**
