### PR TITLE
Move developer's guide to the GitHub wiki

### LINKED ISSUE #2160: Integrate stuff from wiki into documentation
https://github.com/espressomd/espresso/wiki/Development

### LINKED ISSUE #2690: Move developer guide to Wiki on Github

### PR DESCRIPTION
**Pull request by jngrad**
Fixes #2690, fixes #2160

The developer's guide (DG) was moved section by section to the wiki, to the Doxygen documentation or combined into `contributing.rst`, depending on the relevance. Its content was also updated.

### CODE REVIEW

**Comment by fweik** [comment]
We should consider adding an overview page as front-page for the wiki. At the moment this looks very empty.

**Comment by jngrad** [comment]
I've updated it just now. There isn't much to say, the side bar is already self-explanatory. More general information can already be found on the repository main page and in `CONTRIBUTING.md`.

**Comment by RudolfWeeber** [comment]
Please put a link to the developr wiki somewhere easily findable. E.g., the index page.
Then, its ready.

**Comment by jngrad** [comment]
Links to the wiki are already provided in the introduction page (section 1.2. Basic program structure) and in the contributing page (section 18.2. Contributing your own code). Is the index page the right place for an external link?

**Comment by RudolfWeeber** [comment]
On Tue, Apr 23, 2019 at 01:07:43AM -0700, Jean-Noël Grad wrote:
> Links to the wiki are already provided in the introduction page (section 1.2. Basic program structure) and in the contributing page (section 18.2. Contributing your own code). Is the index page the right place for an external link?
Yes, I'd say so. Otherwise people who don't konw it exists, will have a hard tiem finding it.

**Comment by fweik** [comment]
Is that on purpose that the link called "developer's guide" on the wiki start page points to doxygen?

**Comment by jngrad** [comment]
Depends on our plans with Doxygen. I've changed it to "core documentation", which is more appropriate at the moment. With time, more pages like `bondedIA.html` (in the state of `jngrad:fix-2690`) will be added, providing the theory, implementation and script interface of core features, and the core documentation will evolve into a developer's guide.

**Comment by fweik** [comment]
I see. I still think that the start page could be made more friendly by having two sentences explaining which types of documentation exist combined with a link to them. I think this sill can be rather confusing for somebody who does not already know what they are looking for.

**Comment by jngrad** [comment]
Are you referring to the wiki or sphinx start page?

**Comment by fweik** [comment]
[wiki](https://github.com/espressomd/espresso/wiki)

**Review by fweik — APPROVED** [review]

**Pull request merged**
