### PR TITLE
cmake: Fixed doxy-config generation

### PR DESCRIPTION
**Pull request by fweik**
Fixes #

Description of changes:
 - 

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
Could you please add a check similar to the sphinx check

**Comment by fweik** [comment]
Where/what is the sphinx check?

**Comment by fweik** [comment]
You mean the `doctest` target?

**Comment by KaiSzuttor** [comment]
no, the check_sphinx job in the CI

**Comment by fweik** [comment]
It's also not installed, but I'm not sure how to use the install tests? @jngrad how do I add a new install test?

**Comment by jngrad** [comment]
See [testing.rst#installation-tests](https://github.com/espressomd/espresso/blob/352fca2d24d9d525e15afbc6da1f7c09c1afcedb/doc/sphinx/testing.rst#installation-tests). For the bash script:
```bash
#!/usr/bin/env bash
source BashUnitTests.sh
function test_doxygen() {
  assert_file_exists "@CMAKE_BINARY_DIR@/doc/doxygen/html/index.html"
  assert_file_exists "@CMAKE_BINARY_DIR@/doc/doxygen/html/particle__data_8hpp.html"
}
run_test_suite
```
Don't forget to `chmod +x` the script. In CMakeLists.txt:
```cmake
add_custom_target(setup_compile_doxygen COMMAND make doxygen WORKING_DIRECTORY ${CMAKE_BINARY_DIR})
cmake_test(FILE test_doxygen.sh DEPENDENCIES BashUnitTests.sh)
set_tests_properties(test_doxygen PROPERTIES DEPENDS setup_compile_doxygen)
add_dependencies(setup_install setup_compile_doxygen)
```

**Comment by fweik** [comment]
Thank you! I think we'll discuss the installing in a separate issue though.

**Comment by fweik** [comment]
@KaiSzuttor

**Review by KaiSzuttor — APPROVED** [review]

**Pull request merged**
