### PR TITLE
CI: make errors in the build script visible.

### PR DESCRIPTION
**Pull request by KaiSzuttor**
man bash:
```
Exit immediately if a simple command (see SHELL GRAMMAR above) exits with a non-zero status.  The shell does not exit if the command that fails is part of the command  list  immediately  following a while or until keyword, part of the test in an if statement, part of a && or || list, or if the command's return value is being inverted via !.  A trap on ERR, if set, is executed before the shell exits.
```

### CODE REVIEW

**Comment by mkuron** [comment]
This won't work. Many of the lines of the script are allowed to fail. E.g. `[ -z "$insource" ] && insource="false"` evaluates to false if `$insource` is set already. You'll need to add `|| true` in many places or use proper `if`s.

**Comment by KaiSzuttor** [comment]
right, I will look into that. But I think it's worth the effort.

**Comment by KaiSzuttor** [comment]
~~~@mkuron works for me~~~ it does not fail although it should

**Comment by mkuron** [comment]
I find that hard to believe. If I try out lines like the `[ -z "$insource" ] && insource="false"` or `grep -q suse /etc/os-release` in a terminal, I see that they return nonzero exit codes. It almost seems like your `set -e` does not have the intended effect.

**Comment by KaiSzuttor** [comment]
it does not help since it only captures simple statements and not the ones that are piped or are in an if statement... argh

**Comment by mkuron** [comment]
Should be possible though. You just need to add a bunch of `|| true` in the right places. Or rewrite this script in Python and do the termination logic yourself.

**Comment by KaiSzuttor** [comment]
this should now fail...

**Comment by mkuron** [comment]
Odd, it fails only on Travis but not on GitLab.

**Comment by KaiSzuttor** [comment]
Seems to do the job! I really ~~~like~~~ love bash! @mkuron happy with this solution?

**Comment by KaiSzuttor** [comment]
it fails only if ```make_check``` because I put a non-existing command behind the if

**Comment by mkuron** [comment]
I guess that does it. Can you explain `trap abort 0` to me? What does `abort` include and what is `0`?

**Comment by KaiSzuttor** [comment]
https://mywiki.wooledge.org/SignalTrap

**Review by mkuron — APPROVED** [review]

**Comment by KaiSzuttor** [comment]
hm, doesn't work yet

**Pull request merged**
