### PR TITLE
4.1.4rc

### PR DESCRIPTION
**Pull request by jngrad**
4.1.4 bugfix release. See [release notes](https://github.com/espressomd/espresso/wiki/es-414-release-notes).

### CODE REVIEW

**Comment by jngrad** [comment]
The macOS X image was changed recently for the 4.2 branch and is no longer suitable for the 4.1 branch. Here is the segfault:
```
64/69 Test #64: scatter_buffer_test ..............***Exception: SegFault  2.40 sec
Running 2 test cases...
Running 2 test cases...
Running 2 test cases...
Running 2 test cases...
*** No errors detected
*** No errors detected
*** No errors detected
*** No errors detected
[testaccounticps-MacBook-Pro:03781] *** Process received signal ***
[testaccounticps-MacBook-Pro:03781] Signal: Segmentation fault: 11 (11)
[testaccounticps-MacBook-Pro:03781] Signal code: Address not mapped (1)
[testaccounticps-MacBook-Pro:03781] Failing at address: 0x0
[testaccounticps-MacBook-Pro:03781] [ 0] 0   libsystem_platform.dylib            0x00007fff674c15fd _sigtramp + 29
[testaccounticps-MacBook-Pro:03781] [ 1] 0   ???                                 0x000070000bf287f0 0x0 + 123145502754800
[testaccounticps-MacBook-Pro:03781] [ 2] 0   mca_rml_oob.so                      0x000000010e55bcfc orte_rml_oob_send_buffer_nb + 942
[testaccounticps-MacBook-Pro:03781] [ 3] 0   libopen-rte.40.dylib                0x000000010bc11bb6 pmix_server_log_fn + 457
[testaccounticps-MacBook-Pro:03781] [ 4] 0   mca_pmix_pmix3x.so                  0x000000010e413915 server_log + 850
[testaccounticps-MacBook-Pro:03781] [ 5] 0   mca_plog_default.so                 0x000000010e50c856 mylog + 503
[testaccounticps-MacBook-Pro:03781] [ 6] 0   mca_pmix_pmix3x.so                  0x000000010e488fe7 pmix_plog_base_log + 992
[testaccounticps-MacBook-Pro:03781] [ 7] 0   mca_pmix_pmix3x.so                  0x000000010e456fd2 pmix_server_log + 1933
[testaccounticps-MacBook-Pro:03781] [ 8] 0   mca_pmix_pmix3x.so                  0x000000010e43f741 pmix_server_message_handler + 5041
[testaccounticps-MacBook-Pro:03781] [ 9] 0   mca_pmix_pmix3x.so                  0x000000010e491075 OPAL_MCA_PMIX3X_pmix_ptl_base_process_msg + 750
[testaccounticps-MacBook-Pro:03781] [10] 0   libopen-pal.40.dylib                0x000000010bccce86 opal_libevent2022_event_base_loop + 1543
[testaccounticps-MacBook-Pro:03781] [11] 0   mca_pmix_pmix3x.so                  0x000000010e461bb1 progress_engine + 30
[testaccounticps-MacBook-Pro:03781] [12] 0   libsystem_pthread.dylib             0x00007fff674cd109 _pthread_start + 148
[testaccounticps-MacBook-Pro:03781] [13] 0   libsystem_pthread.dylib             0x00007fff674c8b8b thread_start + 15
[testaccounticps-MacBook-Pro:03781] *** End of error message ***
```

This error is reproducible in CI but not reproducible in VirtualBox (with a slightly older snapshot of the CI image). I've backported the GitHub Actions from the 4.2 branch to solve the issue.

**Comment by mkuron** [comment]
> This error is reproducible in CI

There is one other report about it on the internet, https://github.com/BlueBrain/CoreNeuron/pull/307#issuecomment-630632862. Probably just another example of OpenMPI's poor recent software quality.

**Comment by jngrad** [comment]
I already looked into this error and found a post on the OpenMPI: https://github.com/open-mpi/ompi/issues/5798#issuecomment-425487640. There are multiple solutions, e.g. https://github.com/conda-forge/openmpi-feedstock/pull/58 or lssfau/walberla@ec487929866a, but my patience for troubleshooting 4.1-related CI issues is running out.

**Comment by mkuron** [comment]
Those are actually a different issue that only comes up when you have a large number of MPI ranks. Our failing test only has four, so that can't be it. If it works on GitHub Actions, that's a sensible solution. I've spent way too much time working around OpenMPI bugs over the past few years.

**Comment by jngrad** [comment]
@mkuron there are 4 python tests that hang reproducibly in the ROCm 3.3 image: [256817](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/256817), [256868](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/256868), [256870](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/256870). They pass within 30 seconds on the ROCm 3.0 image: [256816](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/256816).

**Comment by jngrad** [comment]
`mpiexec` is toast for the emulated `armhf` architecture on coyote 2, 7, 8:
```
espresso@95acae3363b2:~$ mpiexec -n 2
/usr/bin/mpiexec: Error: unknown option "-n"
```
coyote 10 has been incompatible with `armhf` for almost a year.

OpenMPI is still working for `armhf` on coyote 1, 6, 11 and 12.

**Comment by mkuron** [comment]
> `mpiexec` is toast

The 32-bit QEMU builds (i386 and armhf) fail since we switched the Docker filesystem driver from aufs to overlay2 a few months ago. This was necessary because of https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26618. To make overlay2 work with 32 bits, https://github.com/espressomd/docker/pull/115 would have been needed but was never merged.

**Comment by jngrad** [comment]
If code review doesn't find anything to change, we can update the version number and release it.

**Comment by jngrad** [comment]
(putting it back to draft, because we don't use merge commits on releases)

**Review by KaiSzuttor — APPROVED** [review]

**Comment by jngrad** [comment]
@junghans: merged, tagged and released. The official announcement will me made shortly.
https://github.com/espressomd/espresso/releases/tag/4.1.4

**Pull request merged**
