### PR TITLE
H5md testcase

### PR DESCRIPTION
**Pull request by KaiSzuttor**
Remove unnecessary static members.

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
oops, sth went wrong with the merge

**Comment by RudolfWeeber** [comment]
I think, it can be merged.

**Comment by fweik** [comment]
I've restarted the two failing travis checks, will merge if they pass.

**Comment by fweik** [comment]
@KaiSzuttor You still need to deal with some python3 issues....

**Comment by fweik** [comment]
Also I think you should check if the test file exists in setUp and delete it if so.

**Comment by KaiSzuttor** [comment]
Ready for review @fweik

**Review by fweik — APPROVED** [review]

**Comment by KaiSzuttor** [comment]
I made it broken again, yeah

**Pull request merged**
