### PR TITLE
doc: make it work with texlive-2016 (fixes #768)

### LINKED ISSUE #768: Documentation doesn't build with texlive-2016
See https://build.opensuse.org/public/build/home:cjunghans:branches:Education/openSUSE_Factory/i586/espresso/_log:
```
! Class scrreprt Error: undefined old font command `\bf'.
```

I think there are two solutions:

1. replace `{\bf ...}` by `\textbf{...}`
2. Use class option `enabledeprecatedfontcommands`

### PR DESCRIPTION
**Pull request by junghans**
Replace \bf -> \textbf, \tt -> \texttt, \it -> \textit
        \rm -> \textrm

### CODE REVIEW

**Comment by fweik** [comment]
@hmenke Do we like that?

**Comment by hmenke** [comment]
@fweik No, we don't like that, because this is just mindless search-and-replace.  For example `{\bf v}` in math mode should be replaced by `\mathbf{v}` (even nicer would be `\bm{v}` with the `bm` package, but that might entail a complete overhaul of the manual).  It might also cause error in the future when people copy-and-paste this stuff.  Try for instance `$\textbf{\epsilon}$`.

**Comment by junghans** [comment]
I did another round with `\mathbf{}`.

**Comment by hmenke** [comment]
@junghans Looks good.  Thanks for the effort.  @fweik Can be merged.

**Pull request merged**
