### PR TITLE
Remove legacy debug macros

### PR DESCRIPTION
**Pull request by jngrad**
Fixes partially #3095

Remove debug macros that are unused, trivial, or preventing further energy/force kernel refactoring.

### CODE REVIEW

**Comment by fweik** [comment]
Can you please also check for now-unneeded includes of `debug.hpp`, this should be almost all of them, so I think you can just automatically remove all of them, and re-add where needed. (My best guess is that it's only needed in `cells.cpp` for the sorting check).

**Comment by jngrad** [comment]
Unfortunately the majority of them still need to include `debug.hpp` because of this global variable:
https://github.com/espressomd/espresso/blob/852b1a0c4728041ffce660a6bb7071176b13508f/src/core/debug.hpp#L49

**Comment by fweik** [comment]
Files that use this should include `communication.hpp`, also `s/this_node/comm_cart.rank()/g'. But maybe not in this PR.

**Comment by jngrad** [comment]
Let's do this change in another PR, I need this PR merged to move on with kernel refactoring.

**Comment by fweik** [comment]
Agreed.

**Review by fweik — APPROVED** [review]

**Comment by jngrad** [comment]
bors r=fweik

**Pull request merged**
