### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Review by jngrad — APPROVED** [review]

**Comment by RudolfWeeber** [comment]
Please hold off on this one til next week.

**Comment by fweik** [comment]
@RudolfWeeber why?

**Review by fweik — CHANGES_REQUESTED** [review]
Wait until next week

**Comment by RudolfWeeber** [comment]
I took a look. Can go ahead from my side.

**Review by fweik — APPROVED** [review]

**Pull request merged**
