### PR TITLE
Disable P3M benchmark test

### LINKED ISSUE #2924: P3M benchmark randomly fails CI
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/7734

### PR DESCRIPTION
**Pull request by jngrad**
Closes #2924

### CODE REVIEW

**Comment by fweik** [comment]
Hm, if you just comment it out, than it will decay and stop working. I think it would be better to either make it deterministic by fixing the parameters or remove it altogether.

**Comment by jngrad** [comment]
> I think it would be better to either make it deterministic by fixing the parameters

All the information I got from coworkers, from code introspection and from debugging sessions where parameters and random seeds are fixed, are consistent with a non-deterministic P3M tuning algorithm, for a continuous period of 6 months. More specifically, the bisection uses a heuristic that depends on the exact timing of all previous iterations, and these timings are affected by all other threads running on the same CI machine. I don't see what you have in mind here. Didn't you once suggest we should re-implement the P3M tuning in Python with a different algorithm to make it more deterministic?

> it will decay and stop working

True. Let's wait until #3326 is merged, then we can disable the benchmark tests only on the subset of CI jobs where it fails.

**Comment by fweik** [comment]
I meant fixing the P3M parameters instead of tuning them. The tuning as it stands is non-deterministic  because it depends on the (uncontrolled) run time.

**Comment by jngrad** [comment]
That could work on a single machine. Getting the P3M parameters once and re-using them for all other myconfig files would make the benchmark actually useful. But can we come up with P3M parameters that would work on any machine?

**Pull request closed without merging**
