### PR TITLE
Replaced some manual memory allocations

### PR DESCRIPTION
**Pull request by reinaual**
Partially adresses #2900

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
@reinaual please make the static analysis happy

**Comment by jngrad** [comment]
@reinaual Let's discuss it tomorrow, it might be a bug that went un-noticed by Clang until now. Also, the Clang version on the ICP machines seems to output different errors.

**Comment by jngrad** [comment]
Summary of Wednesday's offline discussion: the change from an array of pointers to a vector of vectors helped Clang detect a scenario where the array would be used un-initialized. The exact sequence of conditional branches that leads to this scenario is however complex to analyze in the current state of `fft.cpp`, and the path doesn't seem to be taken in the multiple tests of the testsuite (probably due to the low coverage of the `if (not group)` branch).

@reinaual if you run out of ideas, I suggest you partially revert b867d6a831, e.g. by merging 06122545c4. This way your contribution will remain in the history and can be restored in the future, when the code that initializes the FFT arrays becomes more readable.

**Review by jngrad — APPROVED** [review]
Thanks! This makes the code more readable.

**Pull request merged**
