### PR TITLE
core: dd: Obey min num cells.

### LINKED ISSUE #1897: Setting CellSystem.min_num_cells has no effect
For the DD, this eventually triggers`dd_topology_init`, which resets `min_num_cells` to its default value.
Also, the topology reinit should only be run if if current number of cells is smaller than the new `min_num_cells`.

### LINKED ISSUE #1971: Domain decomposition does not obey min_num_cells
```python
from __future__ import print_function
import espressomd

system = espressomd.System(box_l = [10,10,10])

print(system.cell_system.get_state())
```
shows `'min_num_cells': 8`, but `'cell_grid': array([1, 1, 1])`, which are incompatible.
Also it chooses the largest possible cell size, which results in poor performance, because
it maximizes the size of the the ghost layer to the whole box (in every direction).

### PR DESCRIPTION
**Pull request by fweik**
Fixes #1971.Fixes #1897.

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
At first glance, it looks like you are removing the cells in
LEES_EDWARDS y direction =1, when min_num_cells >1.
Is that intended?

Otherwise looks good.

**Comment by fweik** [comment]
I don't understand your comment.

**Comment by RudolfWeeber** [comment]
Took a closer look. This pr can be merged.

**Comment by KaiSzuttor** [comment]
NPT test seems not to converge independent of architecture see failing Mac test now.

**Comment by fweik** [comment]
I'll have a look, apparently there is still something  wrong.

**Comment by RudolfWeeber** [comment]
Does this go into 4.0?

**Comment by fweik** [comment]
If we can somehow manage this would be good as it contains two bug fixes.

**Comment by fweik** [comment]
@RudolfWeeber @KaiSzuttor I'm not really sure what to do about the failing npt tests. I don't feel qualified to judge if there is a problem. Also this is not really related to the changes in the PR, which only influence how the cell grid is chosen (which might of course influence NPT with it's constant box changes).

**Comment by KaiSzuttor** [comment]
is this related to #2057 ?

**Comment by fweik** [comment]
No, #2057 was because of the external field/constraints.

**Pull request merged**
