### PR TITLE
cmake: add soversion to libH5mdCore

### PR DESCRIPTION
**Pull request by junghans**
Found on Fedora package.

This fix might not be needed on master as libs get installed in python directory if I recall correctly.

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
CI is broken for 4.0

**Comment by RudolfWeeber** [comment]
Since we will not provide another bugfix release for 4.0, we might as well disable all checks except ubuntu with python 2/3 on x86_64.

**Comment by jngrad** [comment]
There is no `bors.toml` file on 4.0.

**Comment by fweik** [comment]
Ah of course. Thank you!

**Comment by jngrad** [comment]
I would have made the same mistake, actually :smile:

**Pull request merged**
