### PR TITLE
Constant pH ipython notebook

### LINKED ISSUE #3087: Update and IPython conversion of reactions tutorial

### LINKED ISSUE #3122: Reaction ensemble sstill depends on global seed
in ReactionEnsemble::ConstantpHEnsemble::get_random_valid_p_id() calls i_random().
@jonaslandsgesell, please obtain a random int from the reaction ensemble's private generator, otherwise things can become non-deterministic in a complicated way.

This might be the cause of #2755

### PR DESCRIPTION
**Pull request by jonaslandsgesell**
Fixes #3122 and fixes partially #3087 via simplifying the tutorial. We now do not perform reaction ensemble simulations or simulations with p3m in the tutorial.
This makes the tutorial easy and super fast.

What needs to be done is the integration with tests. @jngrad could you do this?
Also the old tutorial needs to be deleted and the folder renamed to 10-constant_pH_method

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
>\# ## 1 Introduction
>\# 
>\# This tutorial introduces the basic features for simulating titratable systems via the constant pH method.
>\# The constant pH method is a Monte-Carlo method.

Please add one sentence along the lines of ... which models reactions by splitting a particle into two or vice versa. The probabilities are chose such, that the pH value of the system is, on average, constant.

>\# System parameters
>\#############################################################
>box_l = 35

Why this size?

>system.time_step = 0.02
>system.cell_system.skin = 0.4

Why are these needed?

>\# Particle setup
>\#############################################################
>\# type 0 = HA
>\# type 1 = A-
>\# type 2 = H+
>
>N0 = 50  # number of titratable units
>K = 1e-4

Please mention the meaning of K, and why you chose this value

>for i in range(N0):
>    system.part.add(id=i, pos=np.random.random(3) * system.box_l, type=1)
>for i in range(N0, 2 * N0):
>    system.part.add(id=i, pos=np.random.random(3) * system.box_l, type=2)

Does the method place requirements on the ids (such as contiguous numbering?) If so, pls mention.
Otherwhsie, the id key can be omitted.


>RE = reaction_ensemble.ConstantpHEnsemble(
>        temperature=1, exclusion_radius=0, seed=77)

Please explain your choice of exclusion radius.

>RE.add_reaction(gamma=K, reactant_types=[0], reactant_coefficients=[1],
>                product_types=[1, 2], product_coefficients=[1, 1],
>                default_charges={0: 0, 1: -1, 2: +1})

Please link to the doc of this function. Why are you assigning target charges without activating an electrostatics solver?


>\# Next we perform simulations at different pH values. The system must be equilibrated before taking samples.
>
>for pH in pHs:
>    print("pH is {:.1f}".format(pH))
>    RE.constant_pH = pH
>    RE.reaction(2 * N0) # warmup
>    numAs = []
>    for i in range(num_samples):
>        RE.reaction(3 * N0)

Is that enough to assume the samples are uncorrelated'ish for all pHs?
Deos re.reaction attempt a reaction or do a reaction. If the first, what is the acceptance rate?

>\# ## 3 Results
>\# Finally we plot our results and compare it to the well-known result for an ideal reacting system. 

Please specify the equation of the well-known result and a citation.

**Comment by jonaslandsgesell** [comment]
The tutorial states the chemical reaction taking place in the sytem; HA <-> A- +H+
The pH is by definition constant in an equilibrium system where you are allowed to apply this monte carlo method.

**Comment by jngrad** [comment]
@RudolfWeeber I've edited your message to make the questions more visible, the Markdown highlighting was counter-intuitive. The tutorial now shows how the equation of the sigmoid curve is obtained, and has a sentence in the first paragraph explaining the Monte-Carlo algorithm. I'm leaving your other points to @jonaslandsgesell.

**Comment by jngrad** [comment]
please check style before pushing, my mailbox is already flooded :)

**Comment by jonaslandsgesell** [comment]
In the test the std error is to be calculated via dividing by sqrt(num_samples)

**Comment by jngrad** [comment]
I was thinking about removing the std error check, actually. Because of the small sample size, it varies a lot depending on hardware. I had to revert 0132abb to pass CI on a coyote.

**Comment by jonaslandsgesell** [comment]
Hey Jean-Nöel,

I think writing 
simulated_values_error = tutorial.std_dev_degree_of_dissociation/np.sqrt(tutorial.num_samples)
Fixes this as it effectively reduces the error by a factor 10 compared to the standard deviation.

I can do it on monday when I have access to a terminal :)

**Comment by RudolfWeeber** [comment]
Ready for review?

**Comment by jngrad** [comment]
I still have to discuss the statistical analysis with @jonaslandsgesell

**Comment by jonaslandsgesell** [comment]
I come to your office :)

**Comment by jonaslandsgesell** [comment]
Looks above normal to me :) Feel free to merge.

**Review by jngrad — APPROVED** [review]

**Pull request merged**
