### PR TITLE
Icc fix

### PR DESCRIPTION
**Pull request by fweik**
Description of changes:
 - Moved icc ghost comm into right place
 - Don't trigger a resort if only particle charges have changed.
 - Removed unneeded initialization pass form icc force calc.

### CODE REVIEW

**Comment by KonradBreitsprecher** [comment]
I think I got the problem:
`add_non_bonded_pair_force_iccp3m()` won't initialize the forces of 'isolated' particles that don't appear in the loop. Putting back in the force reset for particles and ghosts fixes it. Not sure if there's a way out of doing so.
Apart from that, the speedup for a plate cap test system (with the quick init forces fix) with 100 ions and 200 icc particles is definetly **>2** (in ns/day)!

**Comment by fweik** [comment]
Yes, the initializations have to go back in, is just realized that. Will
do, then it should be correct again.

**Comment by fweik** [comment]
@KonradBreitsprecher should work now.

**Comment by fweik** [comment]
@KonradBreitsprecher

**Review by KonradBreitsprecher — CHANGES_REQUESTED** [review]
We should throw an error if convergence is not reached after the given max iterations.

**Review by KonradBreitsprecher — APPROVED** [review]

**Pull request merged**
