### PR TITLE
CPU Thermostat

### PR DESCRIPTION
**Pull request by mkuron**
This pull request implements a CPU thermostat. This gives Espresso the ability to thermalize the CPU, which is quite a unique feature in MD simulation software, which typically only allows for thermalization of the objects simulated (particles, fluids, ...), but not of the hardware running the simulation.

### CODE REVIEW

**Comment by mkuron** [comment]
You're right about the error message, it doesn't compile on my AIX 7.1 laptop. I'll see what I can come up with.

**Comment by rempferg** [comment]
I won't pull this without documentation.

**Comment by mkuron** [comment]
Give this update a try. The CPU thermostat now integrates with the other thermostats much more nicely. Here's an example that heats your simulation machine to a comfy 60°C:
```
thermostat cpu [expr 60+273]
setmd skin 0
setmd time_step 1
part 0 pos 0 0 0 type 1
integrate 1
```

**Comment by fweik** [comment]
This is a portability nightmare. Needs some serious improvement in the future.

**Pull request merged**
