### PR TITLE
WIP utils: Make some math functions constexpr and mark them as side-effec…

### PR DESCRIPTION
**Pull request by fweik**
…t free.

`__attribute__((const))` means that the function is pure and side-effect free.

### CODE REVIEW

**Comment by jngrad** [comment]
I would have expected the compiler to figure out this attribute by itself in the case of inline and template functions. But when compiling with `-Wsuggest-attribute=pure` and `-Wsuggest-attribute=const` to flag suitable candidates, the results surprised me at first glance:
```c++
template <typename T> double sqrlen(T const &v) { return scalar(v, v); }
```
is a candidate for pure, but
```c++
template <typename T> T sqr(T x) { return x * x; }
```
isn't, even with `-O3`. Looking at the documentation for attributes, this result is not so surprising, though. Should we use the const attribute in general, or only in situations where there is a gain in performance?

**Comment by fweik** [comment]
I don't think that it will make a huge difference. I wouldn't expect the codegen to change for templates, but I haven't checked. There's a [c++ weekly episode](https://www.youtube.com/watch?v=8ZxGABHcu40) about this :-)

**Comment by fweik** [comment]
I think this won't make a difference and is just confusing. I'll take it out. The change that I actually wanted was the one to `int_pow` to avoid the compiler warnings in debug mode.

**Comment by jngrad** [comment]
Why won't gcc and clang throw a warning at this code?
```c++
int i = 0;
template <typename T> __attribute__((const)) T sqr(T x) { i += 1; return x * x; }
```

**Comment by fweik** [comment]
It's a contract: you promise to the compiler that this function does not mutate global state (and therefore has referential transparency), the attribute is usefol exactly for situations where the implementation is not visible.

**Pull request closed without merging**
