### PR TITLE
Cmake update

### LINKED ISSUE #528: Skipped tests in CTest register as Error
Seems to be an upstream issue:
https://cmake.org/Bug/bug_relationship_graph.php?bug_id=15431

### PR DESCRIPTION
**Pull request by fweik**
Fixes #528 #537 #541. And parts of #540.

### CODE REVIEW

**Comment by mkuron** [comment]
I think removing TK breaks all of the demos we show for _Kids Week_, _Girls' Day_, _Tag der Wissenschaft_, etc.

**Comment by rbardak** [comment]
is there a reason not to use an older release version for the demos?

**Comment by fweik** [comment]
We need annother plan for that anyway because we want to drop tcl (end hence won't work anymore).

**Comment by mkuron** [comment]
I suppose that plan consists of using the Mayavi visualization and putting a custom GUI around it. But we're not there yet (the Mayavi visualization is not in the master yet because the boundaries are not in the Python interface yet), so I think it's a bit early to drop Tk.

**Pull request merged**
