### PR TITLE
cleanup of LB interface.

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
Please keep the
```
throw std::runtime_error("LB not activated.");
```
if no LB takes responsibility for ansering in get_viscosity().

Please check that the throws you added to replace parameter validation in Python are converted to Python exceptions when passing invalid parameters.
The tracebacks of uncaught C++-exceptions are hared to read and cannot be tested for from Python.

**Review by jngrad — APPROVED** [review]
LGTM, once the issues are fixed

**Comment by KaiSzuttor** [comment]
ready to merge?

**Review by jngrad — APPROVED** [review]

**Pull request merged**
