### PR TITLE
Move c_analyze.pxd into analyze.pxd

### LINKED ISSUE #1835: Move c_analyze.pxd to also existing analyze.pxd

### PR DESCRIPTION
**Pull request by jngrad**
Fixes #1835

Description of changes:
- merged the two analyze.pxd files
- cleaned up documentation in analyze.pyx
- discovered and fixed an issue in a Sphinx plugin (3fb7824)

### CODE REVIEW

**Review by jonaslandsgesell — APPROVED** [review]
Looks good to me! Thanks for fixing

**Comment by jngrad** [comment]
bors r=jonaslandsgesell

**Comment by jngrad** [comment]
bors retry

**Review by KaiSzuttor — APPROVED** [review]

**Pull request merged**
