### PR TITLE
Switching from deprecated property syntax to decorator based.

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Comment by fweik** [comment]
LGTM, but this should than also be done in particle_data.pyx.

**Comment by KaiSzuttor** [comment]
cython version partially too old (0.24 needed)

**Comment by fweik** [comment]
I'm not sure that we can bump the cython version at this point.

**Comment by RudolfWeeber** [comment]
Since the old synatx still works with py2 and py3, I don't think, this is a sufficient reason to require a newer Cython version.
Should we de-milestone this?

**Comment by fweik** [comment]
I agree.

**Pull request closed without merging**
