### PR TITLE
Remove tutorial 10 and unused LaTeX files

### LINKED ISSUE #3211: Check reaction ensemble tutorial with current HEAD

### PR DESCRIPTION
**Pull request by jngrad**
Closes #3211

Description of changes:
- removed tutorial 10
- removed unused LaTeX preambles

### CODE REVIEW

**Comment by jonaslandsgesell** [comment]
I just did the same, see #3255

**Review by jonaslandsgesell — APPROVED** [review]

**Review by fweik — APPROVED** [review]

**Comment by jngrad** [comment]
bors r=fweik

**Comment by jngrad** [comment]
bors r-
(failed merge on staging)

**Comment by jngrad** [comment]
bors r=fweik

**Pull request merged**
