### PR TITLE
cmake: add so version to libs

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by fweik** [comment]
Wouldn't it be more ... idiomatic to set the project version and have cmake set the shared object versions accordingly?

**Comment by junghans** [comment]
Sure! That makes sense!

**Comment by junghans** [comment]
Do you want to keep whole version or just the first digit, e.g.
https://github.com/votca/tools/blob/master/CMakeLists.txt#L6

**Comment by fweik** [comment]
I think major and minor is the usual way, but it does not really matter because we don't guarantee anything about API/ABI stability

**Comment by junghans** [comment]
Using the full version only makes sense if we guarantee API/ABI stability, which we don't. So, I just derived the version from the `PROJECT_VERSION`.

**Pull request merged**
