### PR TITLE
Fix tests with Python 3

### LINKED ISSUE #826: Some python tests fail with python 3
https://travis-ci.org/espressomd/espresso/jobs/156591475

### PR DESCRIPTION
**Pull request by mkuron**
These changes were present in 5b0909bcbcbd8cf5c4f7ca8ea0b30238c167287e, but got lost in 6daf4e85da43c3891ec25f2e711799b975d23ae0

Closes #826

### CODE REVIEW

**Comment by mkuron** [comment]
Now it's a different error, but that one also comes from merging @RudolfWeeber's code:
```
  File "bondedInteractions.py", line 82, in func
    **params).type_name() + ": value set and value gotten back differ for bond id " + str(bondId) + ": " + params.__str__() + " vs. " + outParams.__str__())
AssertionError: False is not true : TABULATED: value set and value gotten back differ for bond id 0: {'type': 'distance', 'filename': 'lj1.tab'} vs. {'maxval': 1.12246, 'minval': 0.0, 'invstepsize': 890.9003438875327, 'type': 'distance', 'npoints': 1001, 'filename': b'lj1.tab'}
```
To me this looks ok. SetParams added a couple extra attributes to the dict, but the ones set are still there.

**Comment by mkuron** [comment]
I think I've finally fixed it. There were some reads of uninitialized memory that tripped Python 3's conversion of C-strings to Unicode strings. While fixing those, I noticed that `make_bond_type_exist` couldn't safely be re-run, which I've also fixed now.

**Comment by mkuron** [comment]
Yup, this is it. Please merge, @fweik.

**Comment by fweik** [comment]
Thank you for fixing this, I messed this up. Good that we have python 3 checks now.

**Pull request merged**
