### PR TITLE
testsuite: Made dpd test deterministic and faster.

### PR DESCRIPTION
**Pull request by fweik**
Fixes #

Description of changes:
 - 

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Review by KaiSzuttor — APPROVED** [review]

**Comment by fweik** [comment]
@KaiSzuttor where can I find the intel docker image?

**Comment by KaiSzuttor** [comment]
```docker pull gitlab.icp.uni-stuttgart.de:4567/espressomd/docker/ubuntu-intel:latest```

**Comment by fweik** [comment]
Can not reproduce the intel issue locally.

**Comment by KaiSzuttor** [comment]
me neither

**Pull request merged**
