### PR TITLE
Make has_features throw if testing for a not-feature

### LINKED ISSUE #2784: has_features allows checking for non-existing features

### PR DESCRIPTION
**Pull request by fweik**
- Made has_features throw if checking for features that do not exist
- Fixed dead code paths in tests caused by wrong feature checks

Fixes #2784.

### CODE REVIEW

**Review by jngrad — APPROVED** [review]

**Comment by fweik** [comment]
bors retry

**Comment by jngrad** [comment]
`bors` merge queue:
```
5/2/2019, 11:05:18 AM | Batch | Running | #2785
5/2/2019, 11:05:07 AM | Batch | Waiting to run | #2783
```
CI currently has no pipeline for the bors commit. Is there some delay, or is 2785 stuck and blocking 2783?

**Comment by jngrad** [comment]
the entire merge queue is blocked
bors retry

**Comment by jngrad** [comment]
good, 2759 is now running, conflicts in 2785 and 2783 might have to be resolved manually

**Pull request merged**
