### PR TITLE
engine_lbgpu test should use LB_GPU

### LINKED ISSUE #1355: engine_lbgpu test does not use gpu lb
Line 63 should read
```python
lbm = espressomd.lb.LBFluid_GPU(agrid=1.0, tau=S.time_step, fric=0.5, visc=1.0, dens=1.0, couple="2pt")
```
but is
```python
lbm = espressomd.lb.LBFluid(agrid=1.0, tau=S.time_step, fric=0.5, visc=1.0, dens=1.0, couple="2pt")
```
If turned to GPU, the test fails.

### PR DESCRIPTION
**Pull request by hmenke**
Fixes #1355

### CODE REVIEW

**Comment by hmenke** [comment]
The ICP Cuda build [#782](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/782) was auto-cancelled because it was deemed redundant by the bot.  Can someone please trigger it manually?

**Comment by KaiSzuttor** [comment]
Thats currently not possible (because of forced push onto the branch)

**Comment by mkuron** [comment]
@KaiSzuttor, just create a new branch for every pull request. Should be simple enough to do that. You don't even need to clean up the old ones, they won't take up much space.

**Comment by mkuron** [comment]
@KaiSzuttor, how about this?

github.php:
```diff
function process_pull_request($data) {
    echo "Processing pull request event.\n";
    $url = $data['pull_request']['head']['repo']['clone_url'];
    $commit = $data['pull_request']['head']['sha'];
    $username = $data['pull_request']['user']['login'];
    if (is_espressomd_member($username)) {
        echo "Calling run_update_script with args: $url, $commit pullrequest.\n";
-       run_update_script($url, $commit, "pullrequest");
+       run_update_script($url, $commit, "pullrequest " . $data['pull_request']['number']);
    }
}
```

update_repo.sh
```diff
else
-    echo git push -f git@gitlab.icp.uni-stuttgart.de:espressomd/espresso.git python:python
-    git push -f git@gitlab.icp.uni-stuttgart.de:espressomd/espresso.git python:python
+    echo git push -f git@gitlab.icp.uni-stuttgart.de:espressomd/espresso.git python:PR-$4
+    git push -f git@gitlab.icp.uni-stuttgart.de:espressomd/espresso.git python:PR-$4
fi
```

**Comment by KaiSzuttor** [comment]
Seems to work...

**Pull request merged**
