### PR TITLE
Remove unused files from the project

### PR DESCRIPTION
**Pull request by jngrad**
Delete files that have become obsolete since release 4.0.

### CODE REVIEW

**Comment by jngrad** [comment]
There are other candidates:
- Python scripts processing Tcl blockfiles, untested and probably outdated: [tools/blockfile2pickle.py](https://github.com/espressomd/espresso/blob/python/tools/blockfile2pickle.py),  [tools/blockfile.py](https://github.com/espressomd/espresso/blob/python/tools/blockfile.py), [tools/mpiio2blockfile.py](https://github.com/espressomd/espresso/blob/python/tools/mpiio2blockfile.py)
- empty [config/CMakeLists.txt](https://github.com/espressomd/espresso/blob/python/config/CMakeLists.txt) and unused [config/header.txt](https://github.com/espressomd/espresso/blob/python/config/header.txt) (superseded by [maintainer/header_template.txt](https://github.com/espressomd/espresso/blob/python/maintainer/header_template.txt) + [maintainer/add_missing_headers](https://github.com/espressomd/espresso/blob/python/maintainer/add_missing_headers))

Should we remove them too?

**Review by pkreissl — APPROVED** [review]
I am also in favor of removing the other unused files, too.

**Comment by RudolfWeeber** [comment]
I also think, the other files can be removed, but do check against the scripts mentioned in the release checklist. I'm not sure, if one of those uses the header template or similar.

**Comment by jngrad** [comment]
Don't worry, the script from the release checklist uses another template header.
I've made sure all deleted files in this PR weren't used anywhere with grep.

**Review by fweik — APPROVED** [review]

**Comment by KaiSzuttor** [comment]
bors r=fweik

**Pull request merged**
