### PR TITLE
Resort flag

### LINKED ISSUE #1637: interactions_non-bonded.py broken with 3 cores
with 3 cores. To reproduce:
```bash
(set -e; while true; do mpirun -np 3 ./pypresso ../testsuite/interactions_non-bonded.py; done)
```
The repetition is only needed because the testcase picks a random starting point. If the interaction crosses a periodic boundary in the direction of the node grid it always fails. The reason seems to be
that the positions in the ghost cell that takes part in the interaction are not shifted as they should be.
This leads to a wrong distance and the pair is discarded, resulting in a missing interaction. This is actually pretty severe, as it means that Espresso can not do MD correctly with this node layout.

### PR DESCRIPTION
**Pull request by fweik**
Fixed #1637.

Description of changes:
 - Introduce different levels for resort_particles.
 - Do global resort if the user has moved particles.

### CODE REVIEW

**Comment by fweik** [comment]
Ready for review.

**Comment by RudolfWeeber** [comment]
Can we prevent write acces to resort particles, so no-one reduces the resort level by accident by using
= instad of |=?
i.e., have functions
void need_local_resort()
void need_global_resort()
or the like?

Apart from that:

announce_resort_particles():
  please rename `sum` which no longer is a sum

cells_update_ghosts():
  Why is the behavior the same, if LEES_EDWARDS is compiled in, eventhough the ifdef block was removed?

**Comment by fweik** [comment]
> Can we prevent write acces to resort particles, so no-one reduces the resort level by accident by using
> = instad of |=?
> i.e., have functions
> void need_local_resort()
> void need_global_resort()
> or the like?

Done. There is now a setter for resort_particles that can only increase the level.

> announce_resort_particles():
> please rename sum which no longer is a sum

Done.

> cells_update_ghosts():
> Why is the behavior the same, if LEES_EDWARDS is compiled in, eventhough the ifdef block was 
> removed?

Because the proper resort level is now set in integrate_vv.

**Comment by RudolfWeeber** [comment]
Can be merged

**Pull request merged**
